### PR TITLE
fix FS reconnecting

### PR DESCRIPTION
**Pull request by JyeSmith**
This was picked up by @CapnBry and the bug was introduced in PR https://github.com/ExpressLRS/ExpressLRS/pull/754

https://discord.com/channels/596350022191415318/733424557636976692/875483337983131648

### CODE REVIEW

**Review by CapnBry — APPROVED** [review]

**Comment by CapnBry** [comment]
As with the PR that included these changes, I approve removing them as well! Sorry about missing the bug in my initial review. 😔

**Comment by NemesisXB** [comment]
> As with the PR that included these changes, I approve removing them as well! Sorry about missing the bug in my initial review. 😔

Can't be expected to never miss anything. And at least you noticed a couple of possible improvements. So overall I would consider this a win.

**Comment by NemesisXB** [comment]
Also, wasn't this supposed to close #776 ?

**Comment by CapnBry** [comment]
> Also, wasn't this supposed to close #776 ?

No this bug was only present in master, not 1.0. I'm still experimenting with new stuff though, so I'll have a separate PR for faster resync behavior.

**Pull request merged**
