### PR TITLE
Fix config upgrade

### PR DESCRIPTION
**Pull request by pkendall64**
Fixes the config upgrade for receivers where it would lose the model match and all other settings 😢

### CODE REVIEW

**Comment by Pelado-Mat** [comment]
Tested on two HM EP1 running elrs 3.0.0. Worked perfect. Kept all the configuration including the ModelID and ModelMatch status

**Comment by JyeSmith** [comment]
Flashed a Dual with 3.0.1 and changed the tlm power and model number. Flashed with a mashup of current PRs and all setting were preserved.

**Review by JyeSmith — APPROVED** [review]

**Comment by wvarty** [comment]
Seems to still be broken on STM based RXs.

1. Flashed 3.0.1 to STM RX and set model match on
2. Flash PR to RX
3. Model mismatch

**Comment by wvarty** [comment]
Discussed the STM config issues with @pkendall64 today, and we discovered that the reason mine was failing on STM, but @pkendall64 and @deadbytefpv were not was because they were using RXs with dedicated EEPROM chips, whereas I used an older Namimno RX which does not have an external EEPROM. On RXs with no EEPROM, we store config in a "fake EEPROM" (reserved read/write flash space on the STM itself). There appears to be a separate bug that has broken the fake EEPROM stuff, which is why my upgrade failed.
The EEPROM bug is separate to PKs fix, so I am going to tick this since it works fine on ESP and some STM targets, and we can look into the other bug in a new PR.

**Review by wvarty — APPROVED** [review]

**Pull request merged**
