### PR TITLE
Always use flashed options after a new flash

### LINKED ISSUE #2121: Binding phrase set in configurator not applied after flashing.
## Current Behavior

Binding phrase not applied.

Background: I ended up with a binding phrase mismatch between the TX (old phrase) and 2 new RX's (new phrase) when upgrading TX from 3.x.x to 3.2 using and flashing 3.2 to two never-previously-configured RXs.  Likely this scenario will happen to anyone else purchasing new RX's, and flashing them for the first time with a previously used TX.

## Steps to Reproduce

1. Binding phrase set in TX via Wifi Web UI.
image

Firmware: [UNIFIED_ESP32_2400_TX_3.x.x-maintenance (dfa7d8).zip](https://github.com/ExpressLRS/ExpressLRS/files/10962101/UNIFIED_ESP32_2400_TX_3.x.x-maintenance.dfa7d8.zip)

2. Later...
3. Different binding phrase set in ELRS Configurator (1.5.5) (new install, no previous firmware built)

image

Log: [ExpressLRSBuildLog_20230313181407382.txt](https://github.com/ExpressLRS/ExpressLRS/files/10962096/ExpressLRSBuildLog_20230313181407382.txt)

Firmware: [RadioMaster_Boxer_2400_TX-3.2.0.zip](https://github.com/ExpressLRS/ExpressLRS/files/10962099/RadioMaster_Boxer_2400_TX-3.2.0.zip)

```
UID bytes: 137,14,68,83,145,153
```

4. Firmware flashed to TX module using Wifi.

UI says: 'target mismatch' -> 'flash anyway', 'force update' -> OK.

5. Old binding phrase still present.

image

## Your Environment

- TX hardware: Radiomaster Boxer
- RX hardware: Radiomaster EP1
- Handset model:
- OpenTX version (including nightly number) (see screenshots)
- ExpressLRS version (TX & RX MUST MATCH): (see screenshots)
- Packet Rate: N/A
- Telemetry Ratio: N/A
- user_defines: N/A

### PR DESCRIPTION
**Pull request by pkendall64**
When flashing a device, it should always use the options supplied in configurator.

When flashing we now generate a random string which is written to the option JSON object. If this is different to the one on the SPIFFS partition then we use the flashed one. This means a user can modify their settings in the web UI and the new discriminator string is written to the SPIFFS and will use the SPIFSS options until the device is flashed again.

Check the "device-id" when saving options and if it is different it will return an error telling the user they need to refresh.
Disables the "Save & Reboot" button until a config has been read from the device.

Also fixes airport settings not being done when using the binary_configurator (for cloudbuilds).

This required an upgrade to the base ESP8266 platform as there was a bug when serialising JSON to the SPIFFS filesystem! It would write the correct number of bytes, but the last few were 0xFF ?! The code change was required because we now check the device-id on options save.

Fixes #2121 and #2120

## Test 1
1. Flash a TX or RX with or without a passphrase
2. Go to the web-UI and change the passphrase
3. Reboot the TX or RX and check in the web-UI that the new UID for the passphrase is shown
4. Flash the TX or RX again, with the original passphrase
5. Verify that the web-UI shows the UID for the original passphrase

## Test 2
1. Flash 2 TX or RX modules without home network
2. Start device 1, and connect to the web UI
3. Leave the web-page open and power off device 1 and power on device 2
4. Connect to the AP of device 2 making sure not to refresh the browser
5. Try to save settings and you should get an error about a mismatched device and to refresh the browser

### CODE REVIEW

**Comment by JyeSmith** [comment]
Test 1 and 2 both work as expected.
image

**Review by JyeSmith — APPROVED** [review]

**Comment by CapnBry** [comment]
This is an interesting solution to the confusion people are having with the webui options overrides. However, in the interest smaller code and less RAM, isn't a 32-bit random integer as functionally effective as 16 bytes of random data? Someone calculate the odds of getting the exact same 32 bits of random _twice in a row_ AND also having edited their config.

* In code it is just uint32_t, 4 bytes instead of 25. Also note that the variable needs a comment. `firmware-differentiator` of course, everyone knows what those are and what it is used for 😄 
* No need for constructing convenience String classes to compare the values
* Simple assignments work
* More secure (lols) because dealing with strings etc etc

### Confusion
Back to the confusion of the webui overrides, what's missing from this is information. The user is presented with a box with no other information, so of course they think they're editing the actual value and not overriding it. Under "Runtime Options" on the webui how about something like:
> Use the form below to **override** the options provided when firmware was flashed. These changes will persist across reboots, but **will be reset** if the firmware is updated with different values.

Additionally, the indicator of `uidtype` is virtually invisible on casual glance. I believe it would be beneficial if it stood out more with color. Ideally I'd like to see it right before the UID value itself, same font size, in a colored box proudly displaying what the user is working with. The standard blue for Flashed, orangey for On Loan, red for Overriden / Not set, green for Traditional bind? If the CSS is too hard to make that work, just changing the text in the label is fine, with 5px padding each side so the color stand out more.

### Issues
I'm testing this and when I override the UID, the value changes after reboot but is always says "Flashed" as the UID type. Also, should the "& Reboot" be removed from the Save & Reboot button? It only saves, not reboots. The reboot comes on the followup dialog.

That's all I got for now because I gotta get on a callllll!

**Comment by pkendall64** [comment]
@CapnBry I did most of the things you mentioned above. With the exception of the styling around the UID type.
I think that would be a bit more work than I want to do at this stage.

**Comment by pkendall64** [comment]
Ok a few more changes:
A note block at the top of the options about the reset and bind-phrase.

Screenshot 2023-04-28 at 12 46 20 PM

Also, colors/badges and text around the UID
Screenshot 2023-04-28 at 12 47 59 PM
Screenshot 2023-04-28 at 12 49 16 PM
Screenshot 2023-04-28 at 12 49 45 PM
Screenshot 2023-04-28 at 12 50 15 PM
Screenshot 2023-04-28 at 12 52 02 PM

**Review by CapnBry — APPROVED** [review]

**Comment by pkendall64** [comment]
Thanks @CapnBry. I removed the panel around the descriptive text as you are right it takes up too much space.

**Comment by hydra** [comment]
Great work guys, I'll give feedback as appropriate when I next update my TX firmware.  This should definitely cut-down on the support requests and users being unable to bind after upgrading.

**Pull request merged**
