### PR TITLE
Config Fixes

### PR DESCRIPTION
**Pull request by JyeSmith**
Looks like this was the real culprit!

... Fingers crossed :sweat_smile:

### CODE REVIEW

**Review by pkendall64 — APPROVED** [review]

**Comment by SunjunKim** [comment]
PWM RX reboot problem appeared again.

Tested on: 
TX: (doesn't matter)
RX: BETAFPV PWM RX
Packet Rate: all rates


image

**Comment by pkendall64** [comment]
This is not the root cause of the problem (i.e. the reboots on PWM receivers) but I think it should be merged anyway as it does fix some problems with the config upgrade.

**Comment by SunjunKim** [comment]
I confirm the PWM fix works! GJ PK!

**Review by SunjunKim — APPROVED** [review]
Working OK so far

**Pull request merged**
