### PR TITLE
Add LDARC target

### PR DESCRIPTION
**Pull request by tuy7988**
Add a support of "LDARC"

### CODE REVIEW

**Comment by pkendall64** [comment]
These targets can just be aliases in the configurator repository and no changes are required to the firmware repository.

**Comment by JyeSmith** [comment]
@tuy7988 can we please arrange some samples to Devs first. Users then know the hardware has been tested and supported.

Please jump on Discord and we can start a chat.

**Comment by AlessandroAU** [comment]
Please also correct user_defines.txt, there shouldn't be any changes to that file.

**Comment by JyeSmith** [comment]
@tuy7988 Im closing this PR.  But we can reopen it when LDARC is ready.

**Pull request closed without merging**
