### PR TITLE
STM32 removal

### PR DESCRIPTION
**Pull request by pkendall64**
This is part one of whole series of PRs to expunge the code base of STM32 and to cleanup the ifdefs/defines.

I know this one is massive looking, but it's ~95% deleting files. Anyone reviewing might find it easier to look at the individual commits.

### CODE REVIEW

**Review by JyeSmith — COMMENTED** [review]
Scrolling through the deletions all looks good.

Ill do some smoke testing before approval.

**Review by JyeSmith — APPROVED** [review]

**Review by wvarty — APPROVED** [review]

**Comment by DrakoshaNarkosha** [comment]
Why -DUNLOCK_HIGHER_POWER flag has been removed?

**Comment by pkendall64** [comment]
Because it's no longer required as all modules that support the highest power should also have a fan!

**Comment by dancollins** [comment]
Oh no! I just finished designing a board with an STM32L432! I guess I will have to make the next PCB revision use an ESP32?

**Comment by pkendall64** [comment]
> Oh no! I just finished designing a board with an STM32L432! I guess I will have to make the next PCB revision use an ESP32?

We've been saying for quite some time that STM32 will no longer be supported from the next major version.

**Comment by dancollins** [comment]
I'm not blaming you at all! My mistake for not noticing :)

**Pull request merged**
