### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Moksh-2000**
Sorry I guess this is not place to put my resume.

I have an idea , there is too many pilots need this feature like how to find quad without gps or lost video signal there is way to find out your quad getting using telemetry data we can use as tx to low power or telemetry data packrate with timestamp (like package rate with changeable time sending depend how far) so we can calculate how far away quad , like satellites and gps units works together "I'm not sure how to but maybe future is here" 
My explanation is little hard so sorry 😅

### CODE REVIEW

**Comment by CapnBry** [comment]
I have absolutely no idea what you're trying to do or what you're saying.

**Comment by JyeSmith** [comment]
Please jump over to issues and describe your feature request there.

https://github.com/ExpressLRS/ExpressLRS/issues

**Comment by Moksh-2000** [comment]
> I have absolutely no idea what you're trying to do or what you're saying.

See when enable this mode then receiver send a package and inside of packeged a timestamp like 12:1:34:456[x1] and tx received this packaged at 12:1:23:478 [x2] (hour:min:sec:microseconds) now calculate the distance x2-x1= 22microsec now 
m=cs so distance = 6600m = 6.6km this is example and isn't perfect 😅

I hope you are understand

**Comment by deadbytefpv** [comment]
This is the wrong way to do this, imho. 

You can get started with an Issue, but not this sort of PR. There's discord too, or the FB group page.

**Comment by Moksh-2000** [comment]
> This is the wrong way to do this, imho.
> 
> You can get started with an Issue, but not this sort of PR. There's discord too, or the FB group page.

Yeppp i was declare my resume on discord , thank you 🙂

**Pull request closed without merging**
