### PR TITLE
Simpler FHSS Generation

### PR DESCRIPTION
**Pull request by redfiveau**
Updated the `void FHSSrandomiseFHSSsequence(const uint32_t seed)` function so that it's smaller, less prone to dumping random error messages, and hopefully easier to understand.

### CODE REVIEW

**Comment by CapnBry** [comment]
I'll give this a test, but did the FHSS generator ever generate an error message from failing to fill the hop table? I've never seen it fail but I've always used one of a handful of bind phrases.

**Comment by redfiveau** [comment]
I've seen this message printed.
```
                if (index == NR_FHSS_ENTRIES)
                {
                    // This should never happen
                    Serial.print("FAILED to find the available entry!\n");
```
I can try and replicate it if you want?

The current implementation seems to be a very complex method for randomising an array.

**Comment by AlessandroAU** [comment]
Can you print out an example list of FHSS freqs that are generated?

**Comment by CapnBry** [comment]
It looks good to me and saves 108 bytes on a STM32 TX. I'd still be interested in knowing what seed you used that generated the FAILED message though on the existing code, just to see what broke it.

> Can you print out an example list of FHSS freqs that are generated?

```
New bind phrase "frog a damp gear"
40 71 1 45 61 58 31 39 64 41
8 37 43 9 17 38 67 36 27 72
23 76 51 46 53 15 25 74 73 12
32 10 3 28 42 22 59 29 66 19
57 56 4 49 24 33 78 54 18 47
35 6 48 65 75 70 30 14 7 62
11 13 60 52 26 68 34 2 77 0
50 44 55 79 5 16 63 20 69 21
40 71 44 45 37 31 52 4 19 68
66 78 16 9 13 36 6 54 28 50
15 79 14 11 10 17 0 76 29 49
42 70 67 65 21 27 22 25 73 43
32 48 3 2 33 20 56 46 64 23
5 39 47 60 26 35 72 77 24 38
75 8 57 55 51 58 63 61 74 7
41 62 12 1 69 30 53 59 34 18
40 26 72 52 50 67 45 29 6 58
65 49 3 24 54 31 10 62 30 76
11 70 25 34 46 2 20 19 51 57
61 18 71 48 32 0 27 28 59 16
17 14 75 63 7 44 68 36 77 22
23 33 74 43 78 8 69 73 1 12
13 21 60 47 41 15 37 42 38 4
56 9 53 55 5 64 79 35 66 39
40 30 39 48 57 59 17 24 13 74
1 10 76 19 33 32

New bind phrase "frog a damp gearxxxxxxxxxxx"
40 47 17 15 45 51 25 26 34 53
76 2 18 36 19 65 32 64 6 55
12 37 38 54 1 67 33 72 13 4
31 44 75 69 22 41 11 3 66 30
74 46 49 0 5 61 57 56 14 70
39 62 50 28 63 71 60 79 35 10
68 16 73 9 77 20 52 24 29 78
21 23 58 59 42 8 48 27 7 43
40 30 64 79 53 59 46 48 44 71
62 10 12 19 58 7 52 1 69 72
5 74 45 78 60 24 18 15 14 67
13 57 50 55 23 63 0 54 4 27
75 26 38 51 9 31 6 65 28 73
2 16 25 43 36 77 21 37 33 20
35 47 17 32 34 29 41 22 8 68
3 39 56 76 11 61 42 49 66 70
40 26 67 15 6 21 13 48 75 12
58 20 27 7 39 31 17 5 23 25
47 32 42 76 54 18 50 55 11 74
79 45 36 49 10 46 44 16 65 41
56 19 14 28 62 43 38 22 52 51
24 35 60 0 30 1 66 57 73 61
63 33 77 29 37 34 69 68 71 2
8 70 4 78 53 64 3 59 72 9
40 17 56 45 46 70 3 15 10 34
27 72 78 55 16 54

Master bind phrase "frog a damp gear"
40 65 68 44 55 57 19 36 63 2
64 27 48 3 61 31 69 12 75 52
79 47 45 17 49 29 28 14 73 43
26 5 25 74 38 50 11 8 66 54
56 7 78 10 51 24 20 72 71 76
58 39 42 0 35 41 70 34 37 22
67 1 46 15 21 4 13 62 77 53
32 6 16 30 33 60 18 59 23 9
40 76 70 14 46 13 58 41 56 21
27 3 18 11 28 7 1 65 42 71
26 74 8 60 0 73 67 29 38 69
35 24 17 53 79 43 64 55 10 66
36 75 16 72 61 78 39 49 33 34
68 12 37 54 15 63 6 45 57 4
44 59 19 62 9 5 30 47 20 32
2 22 52 31 77 23 25 50 48 51
40 54 56 2 18 31 3 71 16 65
33 28 43 59 17 34 53 61 48 25
57 50 19 20 46 42 26 55 6 67
70 15 58 39 72 51 49 14 78 37
38 21 64 29 74 60 68 47 52 62
63 12 73 66 45 69 77 22 76 9
32 35 24 5 10 44 27 41 23 75
13 1 79 30 4 7 11 36 0 8
40 17 79 32 74 37 46 38 60 51
12 30 21 25 53 23

Master bind phrase "frog a damp gearxxxxxxxxxxx"
40 60 16 23 52 50 29 70 33 53
46 14 28 36 17 19 39 43 9 58
1 78 13 71 69 27 34 12 51 55
54 44 11 4 32 45 47 21 68 3
26 56 30 25 35 66 79 0 74 73
6 20 37 72 77 57 49 48 76 59
15 2 61 65 75 8 62 64 18 31
41 42 67 38 22 10 5 7 24 63
40 3 56 58 28 73 41 23 37 54
27 61 67 72 11 7 12 0 19 76
44 39 1 69 17 50 74 32 52 6
48 68 18 20 26 29 45 33 4 78
30 64 2 10 63 51 59 13 34 47
62 65 35 79 36 8 71 24 70 42
75 14 46 15 55 49 22 21 60 66
25 31 5 43 9 53 16 38 57 77
40 41 66 33 17 56 6 5 38 12
10 76 42 36 47 48 18 63 32 54
16 65 77 22 61 53 25 30 74 64
3 70 24 57 68 27 34 21 43 0
7 37 75 45 9 13 2 58 62 46
50 35 67 49 31 14 60 1 44 11
4 52 20 72 8 15 59 78 69 51
28 23 55 26 71 39 29 73 79 19
40 15 7 5 19 65 62 61 34 67
11 38 51 73 36 17
```

**Comment by pkendall64** [comment]
Bearing in mind that any change to the output of FHSS table generation will affect TX, RX and the AIO FC's with ELRS. And will not be backward compatible. This is not a problem if we expect 1.1 to only work with other 1.1 devices, which I think is OK, but the AIO PR will need to be updated.

**Comment by JBKingdon** [comment]
This looks like a nice approach to me. Thanks! (I'm also curious to know how the original version ever got to the failure point, but it's a moot point now we have something better)

**Comment by redfiveau** [comment]
The following 2 UIDs generate an error for me:
```
UID[2] = 0xB6;
UID[3] = 0x4A;
UID[4] = 0x44;
UID[5] = 0xE7;

```
```
UID[2] = 0x36;
UID[3] = 0x4A;
UID[4] = 0x44;
UID[5] = 0xE7;
```

**Comment by pkendall64** [comment]
I think you just found a bug in the random number generator!
https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lib/FHSS/random.cpp#L28
is wrong. If x is `RNGMAX`, which it can be then the result will equal max, which is not the contract for this function!

**Comment by JBKingdon** [comment]
Yup, my bad. We'll need to fix that as rngN is still being used in the new code.

**Comment by redfiveau** [comment]
Why is it not just this?

~~~
// returns 0 <= x < max where max <= 256
// (actual upper limit is higher, but there is one and I haven't
//  thought carefully about what it is)
uint32_t rngN(const uint32_t max)
{
    return rng() % max;
}
~~~

vs current implementation

~~~
// returns 0 <= x < max where max <= 256
// (actual upper limit is higher, but there is one and I haven't
//  thought carefully about what it is)
uint32_t rngN(const uint32_t max)
{
    const uint32_t x = rng();
    const uint32_t result = (x * max) / RNG_MAX;
    return result;
}
~~~

Could probably change the size of the types here also, `max` can be `uint8_t`, `rng()` should probably return `uint16_t`.

**Comment by pkendall64** [comment]
Agrees, except max is excluded so has to be `uint16_t` as `uint8_t` only goes to 255!

**Comment by redfiveau** [comment]
In the new FHSS sequence generator, `max` is `NR_FHSS_ENTRIES`, so at most 80 I think, so we can probably get away with uint8_t.

**Comment by pkendall64** [comment]
Then the comment should be updated to reflect that then too. Do you want to fix the implementation of the rng as part of your PR?

**Comment by redfiveau** [comment]
> Then the comment should be updated to reflect that then too. Do you want to fix the implementation of the rng as part of your PR?

Sure, can do.

**Comment by JBKingdon** [comment]
> Why is it not just this?

Clearly because I'm an idiot. Mod makes far more sense there. I don't remember the context of when I wrote that, but judging by the comment about not figuring out what the limit of max was I'd guess it was something I hacked up late at night and never got around to revisiting. Sorry for that.

**Comment by JBKingdon** [comment]
There's a comment on rng() about rngN depending on the output range that will no longer apply once we fix rngN and so can be deleted.

**Comment by CapnBry** [comment]
Awesome work you all. Found a bug, fixed it, smaller implementation, everything about this is a win. Look forward to seeing the rng change and it has my approval.

Also thanks for providing the UIDs that were breaking the existing algorithm which lead to finding the bug I think.

**Comment by CapnBry** [comment]
haha Oh looks like fixing the spelling of `FHSSNumEntriess()` has caused some problems that will need to be find-and-replaced also.

**Comment by redfiveau** [comment]
Looks like it's just rx_main.cpp, there are some references in SX127x.cpp, but they're in comments.
Do you want me to update them in this pull request @CapnBry?

**Comment by CapnBry** [comment]
> Looks like it's just rx_main.cpp, there are some references in SX127x.cpp, but they're in comments.
> Do you want me to update them in this pull request @CapnBry?

Yes please 🙂 Update both the code that's causing the tests to fail as well as those commended out to the new fixed spelling. Thanks!

**Review by pkendall64 — APPROVED** [review]

**Comment by JyeSmith** [comment]
> 
> 
> Looks perfect! I'll ask around about the sentiment over when to merge this since it breaks compatibility especially with the SPI receivers. Thanks for the updates.

Im ok with this since we have V1.0 release. But ifwe drop V1.1 before BF4.3 then I think the SPI rx should be updated.

**Comment by CapnBry** [comment]
I was thinking that we've already broken compatibility with 1.0 by moving the sync channel, so the two can no longer connect to each other at all with master vs 1.0. Therefore I think we should merge this now since both require an update to the SPI code and there's no use waiting on getting this in.

**Pull request merged**
