### PR TITLE
fixes not resetting sx1280 module

### PR DESCRIPTION
**Pull request by freasy**
My module doesnt reset properly, i dont know why. But if i try to read something beforehand, it works and the module initilizes successfull.

I talked with JamesK (Discord) and this could be just my module!

The state of my module:
```
first: i bridged dio3 to gnd once and powered it (fixed that)
second: i havnt soldered every gnd pad of the module
third: i did second, because some pads ripped of that module
fourth: i had to use some jumper wire to get the top pads soldered to the pcb pads
```

### CODE REVIEW

**Comment by freasy** [comment]
After some thinking, jamesK came up with the idea, that my module defaults to UART mode. My code secures spi mode on reset.

**Comment by JyeSmith** [comment]
I also came across this very thing yesterday... and James saved my bacon!

Any SPI command will work.  So in stead of adding an extra command why dont we shuffle the existing commands.  Plus a comment to say why its out of place.  Below is an example of moving SetMode early.

```

bool SX1280Driver::Begin()
{
    hal.init();
    hal.IsrCallback = &SX1280Driver::IsrCallback;

    hal.reset();
    DBGLN("SX1280 Begin");
    delay(100);

    // SPI command immediately after reset to prevent the sx1280 from entering UART mode. https://github.com/ExpressLRS/ExpressLRS/pull/1543
    SetMode(SX1280_MODE_STDBY_RC);                                                                                                //Put in STDBY_RC mode
   
    uint16_t firmwareRev = (((hal.ReadRegister(REG_LR_FIRMWARE_VERSION_MSB)) << 8) | (hal.ReadRegister(REG_LR_FIRMWARE_VERSION_MSB + 1)));
    DBGLN("Read Vers: %d", firmwareRev);
    if ((firmwareRev == 0) || (firmwareRev == 65535))
    {
        // SPI communication failed, just return without configuration
        return false;
    }

    // SetMode(SX1280_MODE_STDBY_RC);                                                                                                //Put in STDBY_RC mode
    hal.WriteCommand(SX1280_RADIO_SET_PACKETTYPE, SX1280_PACKET_TYPE_LORA);                                                       //Set packet type to LoRa
    ConfigModParamsLoRa(SX1280_LORA_BW_0800, SX1280_LORA_SF6, SX1280_LORA_CR_4_7);                                                //Configure Modulation Params
    hal.WriteCommand(SX1280_RADIO_SET_AUTOFS, 0x01);                                                                              //Enable auto FS
    hal.WriteRegister(0x0891, (hal.ReadRegister(0x0891) | 0xC0));                                                                 //default is low power mode, switch to high sensitivity instead
    SetPacketParamsLoRa(12, SX1280_LORA_PACKET_IMPLICIT, 8, SX1280_LORA_CRC_OFF, SX1280_LORA_IQ_NORMAL);                          //default params
    SetFrequencyReg(currFreq);                                                                                                    //Set Freq
    SetFIFOaddr(0x00, 0x00);                                                                                                      //Config FIFO addr
    SetDioIrqParams(SX1280_IRQ_RADIO_ALL, SX1280_IRQ_TX_DONE | SX1280_IRQ_RX_DONE);                                               //set IRQ to both RXdone/TXdone on DIO1
#if defined(USE_SX1280_DCDC)
    hal.WriteCommand(SX1280_RADIO_SET_REGULATORMODE, SX1280_USE_DCDC);     // Enable DCDC converter instead of LDO
#endif
    return true;
}
```

**Comment by freasy** [comment]
> I also came across this very thing yesterday... and James saved my bacon!
> 
> Any SPI command will work. So in stead of adding an extra command why dont we shuffle the existing commands. Plus a comment to say why its out of place. Below is an example of moving SetMode early.
> 
> ```
> 
> bool SX1280Driver::Begin()
> {
>     hal.init();
>     hal.IsrCallback = &SX1280Driver::IsrCallback;
> 
>     hal.reset();
>     DBGLN("SX1280 Begin");
>     delay(100);
> 
>     // SPI command immediately after reset to prevent the sx1280 from entering UART mode. https://github.com/ExpressLRS/ExpressLRS/pull/1543
>     SetMode(SX1280_MODE_STDBY_RC);                                                                                                //Put in STDBY_RC mode
>    
>     uint16_t firmwareRev = (((hal.ReadRegister(REG_LR_FIRMWARE_VERSION_MSB)) << 8) | (hal.ReadRegister(REG_LR_FIRMWARE_VERSION_MSB + 1)));
>     DBGLN("Read Vers: %d", firmwareRev);
>     if ((firmwareRev == 0) || (firmwareRev == 65535))
>     {
>         // SPI communication failed, just return without configuration
>         return false;
>     }
> 
>     // SetMode(SX1280_MODE_STDBY_RC);                                                                                                //Put in STDBY_RC mode
>     hal.WriteCommand(SX1280_RADIO_SET_PACKETTYPE, SX1280_PACKET_TYPE_LORA);                                                       //Set packet type to LoRa
>     ConfigModParamsLoRa(SX1280_LORA_BW_0800, SX1280_LORA_SF6, SX1280_LORA_CR_4_7);                                                //Configure Modulation Params
>     hal.WriteCommand(SX1280_RADIO_SET_AUTOFS, 0x01);                                                                              //Enable auto FS
>     hal.WriteRegister(0x0891, (hal.ReadRegister(0x0891) | 0xC0));                                                                 //default is low power mode, switch to high sensitivity instead
>     SetPacketParamsLoRa(12, SX1280_LORA_PACKET_IMPLICIT, 8, SX1280_LORA_CRC_OFF, SX1280_LORA_IQ_NORMAL);                          //default params
>     SetFrequencyReg(currFreq);                                                                                                    //Set Freq
>     SetFIFOaddr(0x00, 0x00);                                                                                                      //Config FIFO addr
>     SetDioIrqParams(SX1280_IRQ_RADIO_ALL, SX1280_IRQ_TX_DONE | SX1280_IRQ_RX_DONE);                                               //set IRQ to both RXdone/TXdone on DIO1
> #if defined(USE_SX1280_DCDC)
>     hal.WriteCommand(SX1280_RADIO_SET_REGULATORMODE, SX1280_USE_DCDC);     // Enable DCDC converter instead of LDO
> #endif
>     return true;
> }
> ```

With the current reset code, this wont work, because a SPI command must be issued before the reset code runs. Otherwise the reset loop goes on for infinite. I rewrote the reset code (thanks to JamesK).

I had a different idea, and thats just reading the firmware version before reset. I will test your idea, and rework it so that it works for my broken module.

**Comment by freasy** [comment]
@JyeSmith 

I tested it and this was the result:
if i move up `SetMode` it works but 
image

If i move the WriteCommand for the Standby command into the hal init method, the module goes into a bootloop.

What works best for me is issuing a read command in `hal.init`, this is what i have commited right now. Please take a look into that.
image

**Comment by freasy** [comment]
Copied from discord:

@Jye i have a "cleaner" solution now, but the WaitOnBusy method has a 1000LU timeout, so even if it gets called, it does not wait for BUSY = LOW. According to docs GET_STATUS should not be the first issued command. So what you suggested earlier is to move SetMode. What i did, and it works too. I extracted the bits, that makes my module work, which doesnt include WaitOnBusy, but for readability and no duplicate code i just moved SetMode up.
I commited the better code.

What i think is, due to my bad soldering or a bad SX1280 module or something up with the ESP32 dev board, somehow a command got issued and not finished due to noise.

To make sure of that, i need a oscilloscope.

**Comment by JyeSmith** [comment]
Essentially you will get 2ms of waiting for Busy to go low after a reset.  1ms from the WaitOnBusy() after the reset, and then another WaitOnBusy() before NSS goes low.  The below trace shows that Busy will go low about 1.5ms after the reset.  It wouldnt hurt to have a fixed delay after a reset of 10ms just to be sure.  Which probably why the delay(100) is in there after a reset as a safeguard.

I have a few of these changes changes in this PR https://github.com/ExpressLRS/ExpressLRS/pull/1555.  Do you mind testing it?

image

**Comment by freasy** [comment]
After more tinkering, Jye said, i should remove the can and connect the RST pin to the chip side of the RST chip pin, which works like a charm, so the result is: my module is broken, and i the RST high never went to the chip.

The takeway: you cant reset the module initialy with any valid `SPI.transfer`.

**Comment by JyeSmith** [comment]
Closing since we found the HW problem.

**Pull request closed without merging**
