### PR TITLE
Web UI refresh

### PR DESCRIPTION
**Pull request by pkendall64**
This is a major overhaul of the Web UI to match the tabbed material-UI like the backpack.
As part of this I took the opportunity to run eslint over the javascript code and get that cleanup (it also found a few errors 😲 !)

One small change to WiFi scanning was also done, where the wifi network scanning is triggered by loading the page and if a scan has not been performed in the last 30 seconds.  This has the benefit of not doing a scan if you are starting the wifi to use the MSP over WiFi feature.

## EDIT:
Massive refactoring/restructuring after talking to @CapnBry.

The options page has been merged into the main UI so new users to ELRS will be able enter their binding-phrase on the main page, hit save, and go!

The RX & TX html pages have been merged as we're using a template processor for the html processing now.

The wifi information has been removed from the EEPROM config and is now attached to the firmware if done via configurator or updated and saved on the SPIFFS partition.

The hardware page has a banner if the configuration is coming from the SPIFFS partition stating that it is a "customised configuration", and provides links to download the configuration and reset back to defaults.

## EDIT 2:
More refactoring on the network tab.

The model match and PWM have been joined as "Model Settings"

Option and Model Settings pages have a reset link to "reset to defaults".

### CODE REVIEW

**Comment by CapnBry** [comment]
Oh wow it looks so clean and the lack of scrolling scrolling scrolling is a real thing of beauty.

## PWM
In the original PWM table the headers were centered and I think it brings things together better, here's what it looks like in this PR:
image

Can we add a th.center class and apply it to the `Invert? 750us? Failsafe` headers and the Output number column, or some other method to center them? If you think it is ok, I can add that.

## Options.html
Keep this separate with no link to it either? I thought you might merge that into the main page in this PR, or is that for future work? I love the UID generator built in as the main feature there, but not having to recompile to change this is a major feature that I'd hate for people to not know that you added that. Having a button to reset the SPIFFS options.json would be good too.

## Various config clears
In addition to the ability to delete the SPIFFS options.json, a way to delete the hardware.json to go back to the built-in hardware.json would be helpful (for developers or DIYers). I couldn't figure out why switching from a PWMP to a regular RX or an DUPLEX_ESP TX wasn't working, because the SPIFFS had a hardware.json I edited, and the only solution is chip erase or upload a firmware that formats SPIFFS.

Finally, I'd love a way to reset the internal EEPROM/nvram config object to default from the webui. All three of these can be one POST reset handler, with a post param saying to reset config if "config" passed, otherwise delete a file from spiffs with the param name ("hardware.json" or "options.json"). ha HA!  Look at me not caring about directory traversal in a web filesystem command!

Obviously these are all just suggestions as you always go above and beyond expectations. 😃

**Comment by pkendall64** [comment]
I fixed the PWM page, I forgot some MUI classes and wrappers 😦 
Yes, I think options should move to a panel on the main page with a button to reset (remove the json file from spiffs) is a great idea.
Reset config to defaults will be awesome too.

WRT to the hardware file, I was thinking that we could write the MD5/SHA of the the one built into the firmware and put that in the json on the spiffs if it's edited, and on boot checked the SPIFFS stored SHA vs the actual SHA of the firmware one and if they are different (delete the spiffs version) as an upload must have happened. Then we won't stuff ourselves up!

**Comment by CapnBry** [comment]
> I think we can just have a flag that is set by the hardware loader if it loads from SPIFFS. So no need to add anything extra to the JSON.

If the loader sets a flag, that means when the JSON is served it has to be put into the JSON (since the request is to download a json response) which means it has to be somehow rebuilt with the flag in it. If the builder just slaps it in, that flag is already there. Because there won't be a "builtin" edit field in the hardware.html form, the "builtin" field won't be added to the JSON sent to the SPIFFS for storage. It all _just works_ automatically by changing the build process and no code on the MCU.

**Comment by pkendall64** [comment]
> > I think we can just have a flag that is set by the hardware loader if it loads from SPIFFS. So no need to add anything extra to the JSON.
> 
> If the loader sets a flag, that means when the JSON is served it has to be put into the JSON (since the request is to download a json response) which means it has to be somehow rebuilt with the flag in it. If the builder just slaps it in, that flag is already there. Because there won't be a "builtin" edit field in the hardware.html form, the "builtin" field won't be added to the JSON sent to the SPIFFS for storage. It all _just works_ automatically by changing the build process and no code on the MCU.

True! Good thinking.

**Comment by CapnBry** [comment]
I'm not sure that everything got checked in here? I see no way of resetting config or deleting SPIFFS (also `<br>` should be `<br/>` technically)
image

For the Network tab, there's "Forget" and "Disconnect", both of which create AP mode, but I was hoping it would still have the ability to connect right to a new network without an intermediate AP step.
* Radio select:
  * Set new Nome network
  * One-time connect to network, retain Home network setting
  * Start AP mode, retain Home network setting
  * Forget Home network setting, always use AP mode
* SSID and Password fields
* Button: [Confirm]

The top two radio items show the SSID and password fields, the bottom two hide those fields. "Set new Home network" would be the default.

The PWM options looks perfect, we're done there.

**Review by CapnBry — APPROVED** [review]
Looks great. Tested options, hardware, and model reset. Also tested connect to new home, switch to AP mode, and permanent AP mode.

ModelID setting works, but setting ID=0 would prevent the box from being displayed since `if (data.modelid ...` was false, so I fixed that with a hasOwnProperty call.

This doesn't have the ability to tell if you're running defaults for options or hardware, but I dunno if we need that since it doesn't really matter since they can just be wiped. If that's something we need we know how to do it.

**Comment by deadbytefpv** [comment]
Can we have the Runtime Options in two columns to minimize the scroll further?
We have a flexible/responsive template here we can utilize for this so page looks good not just on desktop but also on mobile.
https://www.muicss.com/docs/v1/css-js/grid

**Comment by pkendall64** [comment]
> Looks great. Tested options, hardware, and model reset. Also tested connect to new home, switch to AP mode, and permanent AP mode.
> 
> ModelID setting works, but setting ID=0 would prevent the box from being displayed since `if (data.modelid ...` was false, so I fixed that with a hasOwnProperty call.
> 
> This doesn't have the ability to tell if you're running defaults for options or hardware, but I dunno if we need that since it doesn't really matter since they can just be wiped. If that's something we need we know how to do it.

Good call.

**Comment by CapnBry** [comment]
Glob dammit, mobile! (the tabs)
image

The Runtime Options looks fine to me, but how about we ditch welcoming people to their device that has to be scrolled by every time. I know you already slimmed this down, which is certainly appreciated, but how about just "ExpressLRS" at the top and the target name is just the target name instead of explaining what the user is there to do already, and grouping the revision with it to save space.

image

**Comment by deadbytefpv** [comment]
16040Model
16040Update

Might be ideal to add a line break (`<br />`) before the text in these links here so they are uniform across viewports. they are of small importance, but they'll sure gonna be nitpicked.

1604-footerLinks

Mobile viewport looks good on my side, though I don't have the pwm receiver that has 5 tabs.

**Comment by pkendall64** [comment]
You guys are just taunting me now! Making me do web stuff when you know I don't like it! 😆 

The PWM settings are actually merged into the Model tab if they are there, so no new tabs will appear.
With the model match we wanted to make it a single inline-form so as not to waste vertical space.

**Review by deadbytefpv — APPROVED** [review]
Sorry PK!
Capn started it.. LOL

Great work, as always!

**Pull request merged**
