### PR TITLE
Allow config of RX initial packet rate

### PR DESCRIPTION
**Pull request by CapnBry**
Adds RX Lua config item to set which rate it starts rate cycling with on boot (no config change needed). Refactors common rxtx Lua code to one file instead of copypasta.

### Details
For people not running the fastest rates, it takes **forever** for the rate cycling to get around to their chosen rate, such as 100Hz Fullres. This adds an RX config parameter to set which rate the receiver starts at on boot, and makes that chosen rate feel instantaneous on plug in. It is like magic how fast my PWM RX connect now, and gets around some [shitty] ESCs requiring a PWM signal within a second of boot. The initial rate is used for 5 "cycles" to allow plenty of time to connect before beginning rate cycling.

By default, the RX still will start on F1000 as before. The user must change it to take effect. I'd :heart: to have the RX remember the last connection it got and always start there. However, the RX must disconnect to save its config, so there's never a good time to do that, since updating it would happen by definition while connected. The user also will unplug their RX typically before the TX, so it will still be connected with power is lost. Committing the "last used" to this config property on Disconnect seems dicey considering it may do this in the air during a failsafe and that feels like a bad idea.

* The default packet rate stored in TX config is now 250Hz for Team 2.4. F1000 doesn't work on a lot of hardware, and now that the initial RX rate is configurable and defaults to F1000, there's no need to force the most incompatible mode to be the default on both ends.

### Refactor
There was clearly a lot of copy paste happening to create the rx_devLua. I've consolidated that code into one unit instead of having them be in both the RX and TX Lua units. This doesn't save any flash space or anything, there was always only one copy, but now we won't ever have to worry about changing one but not the other by mistake.
* The common header items are now collected into the shared header
* luadevGeneratePowerOpts() is now common as is the string it works on
* The string representing the packet rates was moved to common as well

### Unrelated
* `DVR AUX` renamed to `DVR Rec` to describe what it does not what the options are
* Fixed the DVR AUX using `!` instead of arrows in the Lua, this now uses a shared define so they match
* Identified in 3.x.x-maint, but not an issue yet, setting the RX TLM Power via Lua will save an incorrect value if MinPower is not 10mW. Everything still has MinPower = 10mW but I've fixed this so config properly stores the correct power level requested

### CODE REVIEW

**Comment by pkendall64** [comment]
Just needs master merged in, but otherwise looks good. I tested it in conjunction with #1763

**Comment by CapnBry** [comment]
> Just needs master merged in, but otherwise looks good. I tested it in conjunction with #1763

I meant to! I waited for the 3.x.x merge specifically before I applied this. Apparently I fetched master before I built on top of it, but forgot to merge master before I branched. You're getting what you paid for when you hired me as an ExpressLRS developer. 😖

**Comment by pkendall64** [comment]
> > Just needs master merged in, but otherwise looks good. I tested it in conjunction with #1763
> 
> I meant to! I waited for the 3.x.x merge specifically before I applied this. Apparently I fetched master before I built on top of it, but forgot to merge master before I branched. You're getting what you paid for when you hired me as an ExpressLRS developer. 😖

😆 So you get paid the BIG bucks too!

**Comment by P-I-Engineer** [comment]
tested on my bench stuff this morning. supa fast connection now.
100hz full - old way - 9 seconds
100hz full - loofa - 1-3 seconds.

*time was estimated by counting in my head

thanks for this change.

**Review by pkendall64 — APPROVED** [review]

**Review by schugabe — APPROVED** [review]
Yee another feature uses the "other devices menu" of the rx. Works great!

**Pull request merged**
