### PR TITLE
SIYI FR Mini RX as TX

### PR DESCRIPTION
**Pull request by CapnBry**
This PR adds support for the SIYI FR Mini (FM30 Mini) RX to be used as a TX module. The RX is well-suited for this application as it has the same hardware as the FM30 TX module, with a PA/LNA so we can get the same 100mW output from it. The only caveat is that the poor LDO gets really hot (80C+) at even 5V input so the input voltage needs to be very close to 3.3V to prevent it from burning out.

This feature has been requested by several people looking for a cheap or tiny TX module that can fit inside a T-Lite or something.

A hardware mod is required because the input UART TX line has a pullup on it that causes errors when flashing firmware from OpenTX. The mod is just to remove the pullup and then the data gets as clean as half duplex inverted serial at 400kbaud can be. I've documented the connections needed [in the wiki already](https://github.com/ExpressLRS/ExpressLRS/wiki/SIYI-FM30-TX-and-FR-Mini-RX-Hardare#fr-mini-rx-as-tx).

The PR also includes a bootloader for upgrade flashing from OpenTX, but the initial flashing is a one-way trip from stock using STLINK.

### Changes to the bootloader code
* Initializing the UART pins to ALT mode in the STM32F3 wasn't setting some of the bits so I thought it would be better to be explicit and set the UART up the same way Arduino does for the rx_main / tx_main.
* There was a bug in the UART RX ISR where if the UART threw an interrupt indicating a framing error, we'd use the byte anyway. The contents of the RX register is undefined if the framing error bit is set so it should not be used. This was causing some NoSync errors with OpenTX as I was toggling inversion as the first "byte" was actually just a framing error interrupt and it would throw off the STK500 code when it tried to process the byte.

### Changes to the Configuration storage structure
* The RX and TX config structures stored in EEPROM only have a version number, which is currently the same value, so an RX config parses as a valid TX config and vice versa. I've modified this so that two bits of the version are used to indicate RX or TX to prevent this from happening. It would happen fairly often that a user would take an existing RX and convert it to a TX.

I've also moved the pin initialization in CRSF.cpp up a bit to use the standard `setHalfDuplex()` function in a more logical place. This sets the HDSEL bit of CR3, so I _believe_ the Ghost-specific CR3 setting of HDSEL can also be removed, but I do not have hardware to test that.

### Targets added
* `FM30_RX_MINI_AS_TX_via_STLINK`
* `FM30_RX_MINI_AS_TX_via_UART`

### CODE REVIEW

**Comment by JyeSmith** [comment]
Is there anyone else we can line up to test?

**Comment by mituritsyn** [comment]
> Is there anyone else we can line up to test?

Hi flashed it yesterday, not field tested yet. 
Is lua scripts TX dependent or version only? Can't connect to RX as TX with lua generated from Configurator for Siyi TX module

**Comment by CapnBry** [comment]
> Is lua scripts TX dependent or version only? Can't connect to RX as TX with lua generated from Configurator for Siyi TX module

The Lua script is the standard 1.0 release ELRS.lua. Just tested it again right now with the latest merged master branch and it works fine on my Q X7 with the Crossfire inverter mod at 400000 baud / Normal sampling on OpenTX 2.3.14.

Did you remove the 4.7k resistor? Is the TX working at all (connects to receiver)?

**Comment by mituritsyn** [comment]
> Did you remove the 4.7k resistor? Is the TX working at all (connects to receiver)?
image
RX as TX is working. At least I have no FS - RQly 100 accross my room while with my siyi TX I have less than 40 and even FS... Will test lua again later.
P.S. I have q7 with edgeTX and onebit sample mode enabled. Probably should play with bauds and sample mode options

**Comment by mituritsyn** [comment]
photo1627635705
photo1627635475 (1)
photo1627635475
Lua script from 1.0.0

**Comment by CapnBry** [comment]
> Lua script from 1.0.0
> same errors on q7 with tbs inverter and OTX 2.3.13

Ah well that's certainly weird. Did you flash this as an RX first before it became a RX as TX? I wonder if the config is wonky because it is interpreting the RX config as a valid TX config (which is something I'll probably have to fix). Try making this change to the source to see if it fixes the issue.

```
diff --git a/src/src/config.cpp b/src/src/config.cpp
index 4d18640..1f2333b 100644
--- a/src/src/config.cpp
+++ b/src/src/config.cpp
@@ -14,7 +14,7 @@ TxConfig::Load()
     m_eeprom->Get(0, m_config);

     // Check if version number matches
-    if (m_config.version != TX_CONFIG_VERSION)
+    if (true || m_config.version != TX_CONFIG_VERSION)
     {
         // If not, revert to defaults for this version
         Serial.println("EEPROM version mismatch! Resetting to defaults...");
```
This will reset the TX configuration on every boot, but should give you a clean config to start with. If it works, you can revert the change and then the config will store properly and it shouldn't be an issue after that.

If it works I can work up a change to the config system so RX configs aren't valid TX configs and vice-versa.

**Comment by mituritsyn** [comment]
Last changes fixed the problem. Thanks!

**Comment by CapnBry** [comment]
I switched this to do not merge because a T-Lite user needed me to disable the internal pullup on TX2 to get it to work bidirectionally. That is in the platform variant pin definition, so I just need to get this working for both TX and RX versions on the same variant before we merge it.

**Comment by Dropsleutel** [comment]
Please find below my schematic ,it is very compact and it can even fit under the 5in1 module.  It is powered direct from Liion and Enabled by Transmitter.


SiYi_RxASATx_ELRS_T-Lite

**Comment by jurgelenas** [comment]
@CapnBry, @Dropsleutel FR30 Mini Rx as Tx support will be added in the upcoming configurator release :)

**Pull request merged**
