### PR TITLE
Allow user to specify range for Ch5 armed position

### PR DESCRIPTION
**Pull request by MrD-RC**
By default, ExpressLRS specifies that arming must be on Channel 5; and when armed the channel must be above 1500us. This PR adds the optional ability for the user to define the range for **ARMED** on Channel 5. This can be changed in the `user_defines.txt` file, and must be the same on the TX and all RX bound to it. This adds flexibility to Ch 5 for advanced pilots. But for basic set-ups, it will work as it does now.

### CODE REVIEW

**Comment by froqstar** [comment]
I wonder whether we should add more complexity on top of the channel5 special handling, or try and get rid of it completely? 
If I got the conversations in previous PRs right, I think people are trying to get rid of it. Personally I think especially for fixed wing applications without an FC this is one of the most common causes of problems.

**Comment by pkendall64** [comment]
The devs would rather get rid of requiring any special arm features in the transmitter. We've already removed all requirements from the receiver.

**Comment by MrD-RC** [comment]
> The devs would rather get rid of requiring any special arm features in the transmitter. We've already removed all requirements from the receiver.

That would be cool. Not needing arm to be on a specific channel would be useful. Unfortunately it seems there are a few things bound to arming in the firmware including dynamic power and backpack. I would 100% support getting rid of a specific arm channel. But until then, would more flexibility not be beneficial?

**Comment by MrD-RC** [comment]
> I wonder whether we should add more complexity on top of the channel5 special handling, or try and get rid of it completely?
> If I got the conversations in previous PRs right, I think people are trying to get rid of it. Personally I think especially for fixed wing applications without an FC this is one of the most common causes of problems.

I don’t really see it a complexity. Especially when there are other parts to the firmware, like telemetry rates, which are far more complex to comprehend. 

As I mentioned above. I’d 100% welcome removing the “arm” channel completely. But, there aren’t any solutions being presented. Until they are, wouldn’t the flexibility be beneficial? 

I mean, the fixed wing RC only guys could set the range from 988 to 2015. So effectively the system is always armed. Then they could use channel 5 for anything they want. The limiting factor is that this is not per model. So if they were also flying things with a flight controller, it wouldn’t make much sense.

At the end of the day. It doesn’t bother me either way. I have my own fork with this change. I just thought that others may also find it useful. If it gets added to the main project or not is fine with me.

**Comment by flux242** [comment]
@MrD-RC Didn't you call ELRS `a hype` couple of months ago? Wanna jump onto the `hype wagon` now or what?

**Comment by MrD-RC** [comment]
> @MrD-RC Didn't you call ELRS `a hype` couple of months ago? Wanna jump onto the `hype wagon` now or what?

I actually said it had a lot of hype. Which is true. I never said “its all hype” or “its only hype”. Fact is there were a lot of clickbait videos on when it first came out. There are also a load of “Jock” supporters, who jumped ship from Crossfire. Who don’t do ELRS any favours. The fact is that ELRS is getting better for a wider audience now. Due to changes to make it more inclusive. Something that I was looking to add to here.

**Comment by arthurson** [comment]
IMG_20230731_142633

lately i try to mod my exvacator, the mainboard has 8ch esc,  i use sbus>ppm convertor to connect it. ch5 becoms unusable, if rx has option to change ch5 to other place like pwm rx does, then i can use it, for rc car armed is meaningless.

**Comment by SunjunKim** [comment]
> IMG_20230731_142633
> 
> lately i try to mod my exvacator, the mainboard has 8ch esc, i use sbus>ppm convertor to connect it. ch5 becoms unusable, as ch5 just force the motor to fully run all the time. if rx has option to change armed to other place like pwm rx does, then i can use it for extra function, for rc car armed is meaningless.

If you use one of the Full modes (333Hz Full or 100Hz Full), they'll allow ch5 the full 10 bit resolution, even with SBUS outputs. 
Could you try?

**Comment by arthurson** [comment]
> > IMG_20230731_142633
> > lately i try to mod my exvacator, the mainboard has 8ch esc, i use sbus>ppm convertor to connect it. ch5 becoms unusable, as ch5 just force the motor to fully run all the time. if rx has option to change armed to other place like pwm rx does, then i can use it for extra function, for rc car armed is meaningless.
> 
> If you use one of the Full modes (333Hz Full or 100Hz Full), they'll allow ch5 the full 10 bit resolution, even with SBUS outputs. Could you try?

yes, i idid . both tx and rx are 333hz with 8ch,  ch5 just has -100% or 100%   output no matter how i set mapping.

**Comment by arthurson** [comment]
both tx rx use 3.3, you can see ch5 just use full power on both side, for long term it will burn esc without fans installed, thus i wont use it for safety

**Comment by arthurson** [comment]
both tx rx use 3.3, you can see ch5 just use full power on both side, for long term it will burn esc without fans installed, thus i wont use it for safety

> > IMG_20230731_142633
> > lately i try to mod my exvacator, the mainboard has 8ch esc, i use sbus>ppm convertor to connect it. ch5 becoms unusable, as ch5 just force the motor to fully run all the time. if rx has option to change armed to other place like pwm rx does, then i can use it for extra function, for rc car armed is meaningless.
> 
> If you use one of the Full modes (333Hz Full or 100Hz Full), they'll allow ch5 the full 10 bit resolution, even with SBUS outputs. Could you try?

both tx rx use 3.3, you can see ch5 just use full power on both side, for long term it will burn esc without fans installed, thus i wont use it for safety

**Comment by arthurson** [comment]
> > IMG_20230731_142633
> > lately i try to mod my exvacator, the mainboard has 8ch esc, i use sbus>ppm convertor to connect it. ch5 becoms unusable, as ch5 just force the motor to fully run all the time. if rx has option to change armed to other place like pwm rx does, then i can use it for extra function, for rc car armed is meaningless.
> 
> If you use one of the Full modes (333Hz Full or 100Hz Full), they'll allow ch5 the full 10 bit resolution, even with SBUS outputs. Could you try?


https://youtu.be/3ND0tNzfaDM

both tx rx use official  3.3, 333hz and 8ch resolution, you can see ch5 just use full power on both side on video, for long term it will burn esc without fans installed, thus i wont use it for safety

**Comment by arthurson** [comment]
> > IMG_20230731_142633
> > lately i try to mod my exvacator, the mainboard has 8ch esc, i use sbus>ppm convertor to connect it. ch5 becoms unusable, as ch5 just force the motor to fully run all the time. if rx has option to change armed to other place like pwm rx does, then i can use it for extra function, for rc car armed is meaningless.
> 
> If you use one of the Full modes (333Hz Full or 100Hz Full), they'll allow ch5 the full 10 bit resolution, even with SBUS outputs. Could you try?
https://youtu.be/3ND0tNzfaDM

yes, i did, both tx and rx use official 3.3, 333hz and 8ch full resolution, you can see ch5 just run full power to rotate the toy on both side on video, and you can't stop the motor, for long term it will burn esc without fans installed, thus i wont use ch5 for safety at the moment .

making a option to change armed posituation to other place, like ch17 will be a pleaure movement on ppm sbus crsf. elrs should not be limited to play with fpv and drone only, people play rc car truck tank excvacator robotic etc as well.

i have robotics that run 25 servos, still thinking if we can control it on elrs
IMG_20230816_004332

**Comment by arthurson** [comment]
> > IMG_20230731_142633
> > lately i try to mod my exvacator, the mainboard has 8ch esc, i use sbus>ppm convertor to connect it. ch5 becoms unusable, as ch5 just force the motor to fully run all the time. if rx has option to change armed to other place like pwm rx does, then i can use it for extra function, for rc car armed is meaningless.
> 
> If you use one of the Full modes (333Hz Full or 100Hz Full), they'll allow ch5 the full 10 bit resolution, even with SBUS outputs. Could you try?

yes, you are right,  problem fixed, after setting 16ch/2, ch5 becomes usable,  8ch and 12 mixed cant use in my case, thx

**Comment by flux242** [comment]
> I actually said it had a lot of hype. Which is true. I never said “its all hype” or “its only hype”.

yeah dude, if we call you a dick we don't mean you're 100% a dick...

**Pull request closed without merging**
