### PR TITLE
Add Matek R24-P6

### LINKED ISSUE #2049: Add Mateksys R24-P6 2400 PWM Target
Mateksys ELRS-R24-P6 PWM Is still using DIY_2400_RX_PWMP_EX target.
http://www.mateksys.com/?portfolio=elrs-r24-p6

This receiver needs the firmware gzip compression in order to update via WIFI to v3.1.2

### PR DESCRIPTION
**Pull request by CapnBry**
Fixes #2049

Who knows how long I've had this hardware, but I never looked closely enough to notice it was not an R24-P, and nobody said anything about new hardware. Anyway, tests out perfectly (results in the google drive).
http://www.mateksys.com/?portfolio=elrs-r24-p6

I've also uncapsed all the MATEK in the names, because they are not "MATEK SYSTEMS" they are "Matek Systems". Also the configurator already has it right.

Configurator PR coming next.

### CODE REVIEW

**Review by pkendall64 — APPROVED** [review]
No one else got the hardware for testing!

**Comment by CapnBry** [comment]
Oops apparently when I was asked "Does anyone have this hardware?" and I said I did and would do testing on it, the silence that followed meant "NO! DON'T!" 😆 

Holding off on this until samples are sent out to more than one dev.

**Comment by MartinHugh** [comment]
I recently reflashed a R24-P6 from 3.1.2 to 3.2.1 using target **DIY_2400_RX_PWMPEX**, but I got a repeatable error where the link would drop out and come back in a cycle every 15s or so.   I eventually reinstalled 3.1.2 and the fault dissappeared.

I would like to understand if I am using the correct target, as advice on the ELRS discord is to use "**Generic ESP8285 6xPWM 2.4Ghz RX (from generic targets used as a base)**"

The manufacturers product page says to use the **DIY_2400_RX_PWMPEX** target

Also I note that in the ELRS configurator there is a **Matek 2.4Ghz / Matek 2400 RX PWM target.**

Which one of the three options should I be using with this RX?

**Comment by CapnBry** [comment]
I've just flashed my test unit with Configurator 1.6.0-rc1 and ExpressLRS 3.2.1
Generic targets used as a base 2.4 GHz > Generic ESP8285 6xPWM 2.4Ghz RX (this is `DIY_2400_RX_PWMPEX`)
The Matek target is the 5ch R24-P, not the R24-P6 (and that's how it is displayed in the latest Configurator)

I do not have any issue with connection, both on 250Hz Std Wide or Hybrid, or 100Hz Fullres 8ch modes. No disconnection at all.

**Comment by MartinHugh** [comment]
> I've just flashed my test unit with Configurator 1.6.0-rc1 and ExpressLRS 3.2.1 Generic targets used as a base 2.4 GHz > Generic ESP8285 6xPWM 2.4Ghz RX (this is `DIY_2400_RX_PWMPEX`) The Matek target is the 5ch R24-P, not the R24-P6 (and that's how it is displayed in the latest Configurator)
> 
> I do not have any issue with connection, both on 250Hz Std Wide or Hybrid, or 100Hz Fullres 8ch modes. No disconnection at all.

Thank you for your comments

**Comment by MartinHugh** [comment]
> I've just flashed my test unit with Configurator 1.6.0-rc1 and ExpressLRS 3.2.1 Generic targets used as a base 2.4 GHz > Generic ESP8285 6xPWM 2.4Ghz RX (this is `DIY_2400_RX_PWMPEX`) The Matek target is the 5ch R24-P, not the R24-P6 (and that's how it is displayed in the latest Configurator)
> 
> I do not have any issue with connection, both on 250Hz Std Wide or Hybrid, or 100Hz Fullres 8ch modes. No disconnection at all.

I have now followed your procedure and used  :
Configurator 1.6.0-rc1 and ExpressLRS 3.2.1, "Generic targets used as a base" 2.4 GHz > Generic ESP8285 6xPWM 2.4Ghz RX 
And I have updated both problem RXs without a hitch and the link seems solid.

Also noticeable was the fact that there was no refusal to upload over 3.1.2 because of "no space" and, that the process did not completely scramble my PWM settings (as the normal DIY_2400_RX_PWMPEX from configurator 1.5 did.

Thank you for your help.

**Comment by CapnBry** [comment]
image

**Comment by MATEKSYS** [comment]
https://github.com/ExpressLRS/ExpressLRS/pull/1724

> No one else got the hardware for testing!

https://github.com/ExpressLRS/ExpressLRS/pull/1724

**Comment by deadbytefpv** [comment]
> > No one else got the hardware for testing!
> 
> #1724

But I didn't get mine..

**Comment by pkendall64** [comment]
> > No one else got the hardware for testing!
> 
> #1724

I also have absolutely zero hardware from Mateksys.

**Pull request closed without merging**
