### PR TITLE
Reduce screen update frequency when running Lua

### PR DESCRIPTION
**Pull request by CapnBry**
This reduces the redraw frequency when running the Lua script. Currently we redraw the whole thing every call, and it takes so long on colorlcd that it nearly doubles the amount of time it takes for the screen to fully load (since EdgeTX 2.8) and it sucks. The screen will be updated:
* Every time the bad/good counter is updated (every second)
* If there is an input event to react to
* While in edit mode (so the field can blink properly)
* When loading completes
* When the title bar needs to switch between normal and warning modes (!!ARMED!! or Model Mismatch)
* When each remote config item fully loads

For discussion because: Which do we want, twice as fast or the progress bar to go more smoothly?

### Details
Drawing the screen on colorlcd takes about 60ms, which is a ton of missed telemetry intervals that could have been used to actually transfer data. Load times for B&W screens are in the neighborhood of 3-3.5s because drawing text happen an order of magnitude faster, compared to around 6s on colorlcd. Ideally we would only update the portions of the screen that have changed, but that's pretty complex and we can not add much to the Lua as it is teetering on the edge of running out of memory on some handsets.

Methods tested (on colorlcd)
* Unmodified: 44 calls to update() completed in 5.43s, starting from after the deviceInfo is received
* Update only if new data was received via `crossfireTelemetryPop()`: 44 calls / 5.4s. Literally every time there was new data
* Update every time a new config item is fully received: 42 updates / 5.2s. Almost every pop contains a whole new item
* Don't draw if telemetryPushed, so it can be sent without delay: 2 updates in 2.9s but did not update the screen at all while loading
* Update every 400ms: 7 updates / 3.24s
* Update only every Bad/Good update: 4 updates / 3.0-3.2s

I've gone with the last option there as the main trigger, with the full list at the top of the PR. **This code is used on B&W screens too**, which now can load in ~2.5s. It isn't really needed, but it is faster and I don't want to add more code just to see 44 progress bar updates. 😄 There's only like 5 lines of changes in this PR, so I kept it toight! It does appear that there's less RAM being used on B&W thanks to not redrawing every loop too, so this may help with that as well.

Where the code reads the `crossfireTelemetryPop()` has also been changed to a loop, because multiple packets can be queued up and we can handle them all in one `update()` without delaying 100ms/160ms in between.

### Timing (colorlcd)
* lcd.clear() ~10ms
* lcd_title() ~20ms
* Just not drawing any config items (but still iterating through them ~20ms
* Full screen draw 50-60ms

### Tested
* TX16S internal module
* ES900TX external module on colorlcd
* Taranis Q X7 on OpenTX 2.3.12 w/ SIYI FM30 external
* Boxer internal
* Jumper T-Pro AION TX
* DUPLETX_ESP running as an internal module on EdgeTX 2.6

### Unrelated changes
I removed our binary error code from the warning title bar. This was confusing people who thought `Model Mismatch       8` meant that they needed to set their model number to 8. Nobody needs that number. Less code too!

_Thanks to @pkendall64 for suggesting "I think drawing the screen every loop is what makes it take so long", and I frowned my disbelief frown because drawing 10 lines of text can't take 3 seconds right?! He was right_

### CODE REVIEW

**Comment by pkendall64** [comment]
Damn! That's a lot quicker. Whats to discuss, tag it for 3.3 👍

**Comment by ajjjjjjjj** [comment]
Hi, this can be optimized further to forceRedraw only when folderAccess matches parsed field data (only same folder matters to redraw), also should title error code be also changed for B/W screens?

**Comment by CapnBry** [comment]
> Hi, this can be optimized further to forceRedraw only when folderAccess matches parsed field data (only same folder matters to redraw), also should title error code be also changed for B/W screens?

I'm not sure I follow your first point? The code you included doesn't consider folders, and I'm not sure where you're putting that line, maybe some context about where you're suggesting to add it. I don't think either of these two things would make any difference in behavior though? You're right about removing the error code from B&W screens though, thanks.

Can't remove int16 stuff, because I could see us using int16s. We might consider adding back in floats as well because I believe Ardupilot uses them (and definitely uses int16).

**Comment by ajjjjjjjj** [comment]
Sorry, I have updated my comment with code.
It probably won't improve things a lot but it will skip refreshing when loading fields hidden in folders.

I got your point related to U/INT16 tho.

**Comment by CapnBry** [comment]
> Sorry, I have updated my comment with code.
> It probably won't improve things a lot but it will skip refreshing when loading fields hidden in folders.

Now I see what you're saying, but it will not refresh after parseParameterInfoMessage() when loading from the TX module so this wouldn't save any load time there. When loading a remote config, it doesn't really matter because the delay of receiving the item is so much longer that there's not really much performance advantage to warrant adding the other condition.

I'd like to change the loading procedure to lazy load items in folders but I haven't come up with a way to do that which would use less code than we have currently. Then it wouldn't be an issue and also it would appear to load a lot faster too, due to only pulling 12 items instead of 31.

**Comment by JyeSmith** [comment]
> Damn! That's a lot quicker. Whats to discuss, tag it for 3.3 👍

Agree!

image

**Review by pkendall64 — APPROVED** [review]

**Comment by froqstar** [comment]
Maybe we could replace the loading bar with filling segments to indicate how many "redraws" are still to go, instead of having the loading bar filling up very irregularly?
Or do we not know yet at the beginning of loading how many redraws there will be?

**Comment by JyeSmith** [comment]
I would be for removing the bar all together as I dont think it takes long enough to have one.

Also tested on the X7, which does throw a memory error on the first load.  Pretty sure this is only due to compiling the first time.  Refreshes, or loading after a reboot, are all ok.

**Review by JyeSmith — APPROVED** [review]

**Comment by JyeSmith** [comment]
> It does make sense to keep it, as rates like 250Hz at 115k baud

115k... Who are these monsters!

**Pull request merged**
