### PR TITLE
Hybrid channels

### PR DESCRIPTION
**Pull request by r1000ru**
2.4 It is too good not to use it on airplanes and copters with camera pantilt. But this requires two more full-fledged channels.
I have reduced the bit depth of the throttle channel to 8 bits. This allowed the mask to be transmitted for an additional three channels. The channel values are transmitted by the following queue: throttle, ch13, throttle, ch14. Thus, the frequency of transmission of the gas value decreased by 2 times. The frequency of transmission of additional channels is 4 times lower than the frequency of sending packets.
I think it's worth discussing whether to use the throttle channel or the rudder channel to send additional channels.

### CODE REVIEW

**Comment by pkendall64** [comment]
I think this should be a whole new switch mode as the TX sends the switch mode to the RX and there can be up to 4 modes as we are currently only using 2 of them.

**Comment by r1000ru** [comment]
> I think this should be a whole new switch mode as the TX sends the switch mode to the RX and there can be up to 4 modes as we are currently only using 2 of them.

First of all, I will add a check for the coincidence of the encoding of the receiver and the transmitter. 
Can I follow next logic?
1. synchronization packets are transmitted with a certain frequency. All packets with channels that came in the time interval between synchronization packets are subject to decoding according to the mask in the last synchronization packet.
2. If the packets arrived outside the synchronization time (the synchronization packet did not arrive), consider the decoding method undefined and do nothing (failsafe occurs). Thus, we could change the decoding method on the receiver on the fly.
But it is better to allow this until the first arm

**Comment by pkendall64** [comment]
Yes, that's pretty much the approach I have taken in PR #750 where the RX is told what switch configuration to use by the transmitter in the sync packet.

**Comment by CapnBry** [comment]
I feel like this has to be a **hard hard hard hard hard NO** on not sending the throttle position on every packet. There is no guaranteed delivery of packets so there's a chance that 0% of your throttle packets will ever be received and this is a completely terrible idea with regards to safety. Sending the throttle more frequently is not a solution because 2x a non-zero chance of the throttle not being received is still a non-zero chance of the throttle not being received.

ELRS should guarantee safety above all else and "sometimes you're not really in control of your model" should NEVER be an option.

**Comment by JBKingdon** [comment]
> I feel like this has to be a **hard hard hard hard hard NO** on not sending the throttle position on every packet. There is no guaranteed delivery of packets so there's a chance that 0% of your throttle packets will ever be received and this is a completely terrible idea with regards to safety. Sending the throttle more frequently is not a solution because 2x a non-zero chance of the throttle not being received is still a non-zero chance of the throttle not being received.
> 
> ELRS should guarantee safety above all else and "sometimes you're not really in control of your model" should NEVER be an option.

Yes, that's how I feel too. Primary RC channels 0 through 3 shouldn't be made less reliable. My preference for more channels is to add a larger packet for carrying additional channels. I do like the idea of multiplexing the extra channels though, that at least keeps the packet size somewhat under control.

**Comment by r1000ru** [comment]
Of course, I would like to increase the size of the package, but I solved the problem within the size of the existing one. I have been thinking a lot about whether it is appropriate to choose the gas channel or whether it is better to choose the rudder channel. And I chose gas, because it can be turned off by arm in every packet.

I will put the code in order, but for security, you do not need to merge it now. Such channels and settings are needed on a limited number of aircraft/copters, which means they must be stored on the receiver of this aircraft and arrive at the transmitter when connecting. Changing the receiver should return the classic channels.

**Comment by CapnBry** [comment]
The other problem is that you say that you've selected "the throttle channel" but that is not accurate. You have selected CH3, which is only the throttle channel if the user is running AETR and not TAER. We already have one channel that is dedicated to a specific function and I do not want to have more channels that are locked to a specific function or channels that sometimes have different resolution, which causes hidden gotchas to the user.

**Comment by r1000ru** [comment]
Is it possible to increase the packet size to 8 bytes in the future, or is its size already limited by the lora packet or timings?

**Comment by CapnBry** [comment]
> Is it possible to increase the packet size to 8 bytes in the future, or is its size already limited by the lora packet or timings?

No the packet is already at max size we can fit in the transmission window for all rates except 500Hz, and is 8 bytes currently but some of that is taken up by CRC and packet type, etc.

**Comment by JyeSmith** [comment]
I feel like we need just a `FULL_8_CHANNEL` and/or another `FULL_16_CHANNEL` option.  These packets would contain no switch magic, just straight forward channels.  It would also be easier just to lock these modes to a single lower rate since the high rates we currently use may not be possible. 100Hz would fit a 23B packet (16 x 10b channels and ideally a 17b CRC) and maintain a sensitivity of -112.

**Comment by JyeSmith** [comment]
It doesnt look like you gain much dropping from 16 to 8 full channels.  12 channels will actually be in the sweet spot to make the most of the OTA time.

image

**Pull request closed without merging**
