### PR TITLE
add dynamic MAVLink SysID v2

### PR DESCRIPTION
**Pull request by LupusTheCanine**
This is rework of #2891 using event system.

IMHO we should expand event system with enum or bitmask that would contain information on event reason (can multiple events be triggered at once (before previous one is cleared).
Right now there are the following event triggers
* change to AUX1 (channel 5) in CRSF_Handset (I guess arming trigger on tx)
* luaparamMappingChannelOut in rx_devLUA (changes to PWM Mapping as far as I can tell)
* bluetoothTelem registration in tx_devLUA for TX_FM30
* POWERMGNT::setPower (change to power level)
* button functions in devScreen (registration of VTX band and channel)
*  VtxTriggerSend in devVTX
* MspReceiveComplete for MSP_SET_VTX_CONFIG in rx_main
* EnterBindingMode in rx_main
* ExitBindingMode in rx_main
* CheckConfigChangePending in rx_main
* ModelUpdateReq in tx_main
* ConfigChangeCommit in tx_main

I think we need
* config change (pending in rx commit in tx)
* model change (probably can be a specific case of config change)
* binding mode entry
* binding mode exit
* power change
* PWM mapping (we probably should consider channel mapping change  in general for future sbus... mixing)
* Arming 

VTX_CONFIG received
* VTX TriggerSend
* button registration

### CODE REVIEW

**Comment by pkendall64** [comment]
Yes, I agree that we should have a bitmask for the event which says which event has occurred so the devices subscribe to a subset of events.

**Comment by pkendall64** [comment]
I would put the event modifications into a seperate PR. And you should target the master branch.

**Comment by LupusTheCanine** [comment]
> I would put the event modifications into a seperate PR. And you should target the master branch.

That would require reordering git history or leave overly active event handler here (anything happens and sysIDs are updated).
3.x.x is targeted for historic reasons (I took a long time to finish this 😅).

**Comment by LupusTheCanine** [comment]
Moved to #3031 and #3032

**Pull request closed without merging**
