### PR TITLE
Configurable OLED/TFT startup splash screen

### PR DESCRIPTION
**Pull request by pkendall64**
The transmitter module color LCD code had a hard coded Axisflying logo and anyone else adding a color LCD would be blessed with the Axisflying logo on boot!

This adds the ability to add a logo bitmap to the end of the firmware, in the same manner as the options.json and hardware.json files. It also changes the OLED and TFT code to use the splash logo from the end of the firmware.

Logos have been added for Axisflying, BETAFPV, EMAX, Jumper, Namimno and Radiomaster.

### CODE REVIEW

**Comment by JyeSmith** [comment]
Nice!
image

**Review by JyeSmith — APPROVED** [review]

**Comment by mr-sour** [comment]
Works great! TYSM 😁!

**Review by brandonrc — APPROVED** [review]

**Comment by XH-FPV** [comment]
If I want to customize how the boot picture should be done, I didn't find the "const unsigned short vendor_logo[0x2120] PROGMEM" code in "logo.h". I've converted the picture into an array file. I'm using a TFT screen.

**Comment by pkendall64** [comment]
> If I want to customize how the boot picture should be done, I didn't find the "const unsigned short vendor_logo[0x2120] PROGMEM" code in "logo.h". I've converted the picture into an array file. I'm using a TFT screen.

Look in the targets repository for how it's done now. Theres some basic instructions. You will of course need to add a custom target pointing to your logo binary.

**Comment by XH-FPV** [comment]
> > 如果我想自定义启动图片应该如何完成，我在“logo.h”中没有找到“const unsigned short vendor_logo[0x2120] PROGMEM”代码。我已将图片转换为数组文件。我正在使用 TFT 屏幕。
> 
> 在目标存储库中查看它现在是如何完成的。有一些基本说明。当然，您需要添加指向徽标二进制文件的自定义目标。

How should this work, I only have a bmp file with 160*53 pixels now?

**Comment by XH-FPV** [comment]
> > 如果我想自定义启动图片应该如何完成，我在“logo.h”中没有找到“const unsigned short vendor_logo[0x2120] PROGMEM”代码。我已将图片转换为数组文件。我正在使用 TFT 屏幕。
> 
> 在目标存储库中查看它现在是如何完成的。有一些基本说明。当然，您需要添加指向徽标二进制文件的自定义目标。

I found that when I select the "DIY ESP32-S3 DevKit Gemini 2.4Ghz TX" target compilation, no matter how I modify the json file in the "hardware" or "targets" folder, it doesn't seem to affect the compilation result. Can I get him to load the local json file to compile it?

**Comment by pkendall64** [comment]
You would need to add
```json
"logo_file": "logo.bin",
```
To the targets.json file in the "DIY ESP32-S3 DevKit Gemini 2.4Ghz TX" section.
Then build your file put it in the `hardware/logo` directory.

**Comment by XH-FPV** [comment]
> You would need to add
> 
> ```json
> "logo_file": "logo.bin",
> ```
> 
> To the targets.json file in the "DIY ESP32-S3 DevKit Gemini 2.4Ghz TX" section. Then build your file put it in the `hardware/logo` directory.

I downloaded the 3.4.1 firmware in the targets folder only have these files, do I need to download the targets folder from the official website and replace these files?

**Comment by pkendall64** [comment]
No, the targets repo.

**Comment by XH-FPV** [comment]
> 不，目标存储库。如果在 platformio 中构建，则目标存储库将签出到 hardware 文件夹中。因此，请查看硬件/徽标，这是您将放置徽标文件的位置。并编辑 hardware/targets.json 以添加我之前发送的 json 代码段。

I put this code in and the compilation failed, did I do something wrong?

**Comment by XH-FPV** [comment]
> 不，目标存储库。如果在 platformio 中构建，则目标存储库将签出到 hardware 文件夹中。因此，请查看硬件/徽标，这是您将放置徽标文件的位置。并编辑 hardware/targets.json 以添加我之前发送的 json 代码段。

I put this code in and the compilation failed, did I do something wrong?

**Comment by XH-FPV** [comment]
> 不，目标存储库。如果在 platformio 中构建，则目标存储库将签出到 hardware 文件夹中。因此，请查看硬件/徽标，这是您将放置徽标文件的位置。并编辑 hardware/targets.json 以添加我之前发送的 json 代码段。

Still doesn't work.,The boot screen is still blank.

**Comment by pkendall64** [comment]
That is not where the line goes! It goes in the section for the TX module you are flashing, like I said above.
Screenshot 2024-06-03 at 8 39 36 AM

**Comment by XH-FPV** [comment]
> 那不是线路去的地方！就像我上面说的那样，它位于您正在闪烁的 TX 模块的部分中。 屏幕截图 2024-06-03 at 8 39 36 上午

After the change, the compilation is still the same, I used "Img2Lcd v2.9" to convert the logo.jpg image to a logo.bin file and put it in the ExpressLRS-3.4.2/src/hardware/logo directory, but the boot screen of the TFT screen is still blank.

**Comment by pkendall64** [comment]
If the screen is blank and dis displaying random pixels or a logo then you have a wiring problem with your display.

**Comment by XH-FPV** [comment]
> 如果屏幕是空白的并且不显示随机像素或徽标，则您的显示器存在接线问题。

No, I mean that the boot screen is blank, and then the high-frequency head parameters can be displayed normally.

**Comment by pkendall64** [comment]
Then I would say that your conversion of the image to the bin format is not working.

**Comment by XH-FPV** [comment]
> 然后我会说您将图像转换为 bin 格式不起作用。

Can you tell me a workable way to convert?

**Comment by pkendall64** [comment]
There is information in the directory where the logo files are...
https://github.com/ExpressLRS/targets/blob/master/logo/README.md

**Pull request merged**
