### PR TITLE
PIC32MX Support

### PR DESCRIPTION
**Pull request by brandonrc**
Currently working on pic32mx support. 

Adding Targets:

## 2.4ghz PIC32 hardware
- [ ] Tracer TX
- [ ] Tracer RX

### Add sx1272
- [ ] sx1272 (Make separate PR request for this???)
### Add the TBS hardware
- [ ] CRSF TX Full/LITE (Require sx1272 support)
- [ ] CRSF TX Micro (Require sx1272 support)
- [ ] CRSF RX (Require sx1272 support)

### CODE REVIEW

**Comment by brandonrc** [comment]
Maybe this should be broken down into several different PRs???

1. Add PIC32 2.4ghz TX Support (Starting base for basic pic32 support)
2. Add PIC32 2.4ghz RX support
3. Add sx1272 support
4. Add PIC32 900mhz TX support
5. Add PIC32 900mhz RX support

We will need to nock out the 3rd pr before we can continue with 4th and 5th.

**Comment by AndreaCCIE** [comment]
@brandonrc are you still working on this PR?

**Comment by brandonrc** [comment]
@AndreaCCIE I am still working on it. I promise 🤣 

Just not working fast :/

**Comment by AndreaCCIE** [comment]
> @AndreaCCIE I am still working on it. I promise 🤣
> 
> Just not working fast :/

That’s good enough, thanks for your effort! (and don’t forget we are really waiting for this 😎 )

**Comment by Junnicutt** [comment]
I think TBS changed the chipset on the new crossfire rx's a few months back. It might still be a pic32 though. Trappy mentioned it in a Livestream a while ago that there was a firmware update just to support new chips. You probably already know this but I figured I'd mention it since this PR had been around for a while.

**Comment by howels** [comment]
Sorry, I never made any headway on this despite buying a couple of pickits. The WiFi on ESP based modules is so useful that I lost interest in flashing tracer kit.

**Pull request closed without merging**
