### PR TITLE
Proper fix for OLED rate change

### PR DESCRIPTION
**Pull request by pkendall64**
# Problem
Testing has found that changing the rate via the OLED was still causing the TX to drop connection.

# Solution
Because the OLED was running on the second core, so when calling `config.SetRate` the main core would commit the change and the second core would then call `SetSyncSpam` which would not do the work because the config had not changed (i.e. it had been committed).

The fix is to use `deferExecution` to call `config.SetRate` and `SetSyncSpam` from the main core and then the commit would happen in the correct sequence.

### CODE REVIEW

**Comment by Unvented6195** [comment]
Tested and working. The packet rate changes via OLED, and the link doesn’t drop.

**Review by JyeSmith — APPROVED** [review]
Tested EMax OLED.  Looks good... but still dont do this in flight 😅

**Comment by pkendall64** [comment]
> Tested EMax OLED. Looks good... but still dont do this in flight 😅

It's cool, we disable the 5-way when armed 😄

**Review by deadbytefpv — APPROVED** [review]
Tested on a NamimnoRC Flash OLED and EMAX 900 OLED

**Pull request merged**
