### PR TITLE
A switch to enable/disable the dynamic tx power 

### PR DESCRIPTION
**Pull request by SunjunKim**
This is a feature requested from some pilot users of Dynamic Transmit Power, including myself.

Someone may want to enable/disable the dynamic TX power feature on demand. For example, when a model is suddenly lost without single telemetry received for the power raise, or when a user prepares to enter a risky spot, the (configured) max power is needed immediately.

When assigned a switch to CH16 on a radio, that switch will instantly enable/disable the dynamic TX power feature. When CH16 is set "HIGH", it disables the dynamic power and TX power is fixed to the configured power. When CH16 is set "LOW", it restarts lowering/raising the TX power following the algorithms.

I assigned CH16 arbitrarily. Maybe there's a better way to choose which channel to use, but I have no better idea yet.

* Switch feature demo: https://www.youtube.com/watch?v=wdPWw2xu8Ig

### CODE REVIEW

**Comment by CapnBry** [comment]
I bet we could make a case for it if you make a user_define for it.
```
# The aux channel used to indicate power should be boosted to max. Value <1500 = Dynamic Power, >1500=Max configured power
-DDYNAMIC_POWER_BOOST=AUX12
```

And your code would go
```
#if defined(DYNAMIC_POWER_BOOST)
  // if a user selected to disable dynamic power 
  if(CRSF_to_BIT(crsf.ChannelDataIn[DYNAMIC_POWER_BOOST])) {
    POWERMGNT.setPower((PowerLevels_e)config.GetPower());
    return;
  }
#endif
```

**Comment by CapnBry** [comment]
Great! One more thing, can go into the VS Code preferences and turn on the setting "Files: Trim Trailing Whitespace", save tx_main, and commit the whitespace changes as well? Either that or remove them by some other means and commit the changes, we're getting a lot of trailing whitespace sneaking in on these PRs.

**Comment by SunjunKim** [comment]
> Great! One more thing, can go into the VS Code preferences and turn on the setting "Files: Trim Trailing Whitespace", save tx_main, and commit the whitespace changes as well? Either that or remove them by some other means and commit the changes, we're getting a lot of trailing whitespace sneaking in on these PRs.

No problem!
I don't use VS Code but regex did the work.

**Review by CapnBry — APPROVED** [review]

**Comment by CapnBry** [comment]
Looks great. Testing in SIFI FM30 TX / FR Mini RX. Hit the switch, power jumps up. Flip it off, it dynamically lowers.

**Comment by pkendall64** [comment]
Since I'm working on per model configuration would this option make sense to be configurable in the LUA screen like I have done for switch mode, and model matching? I guess we could either update this PR after mine is merged or merge this and create a new PR after mine is merged.

**Comment by CapnBry** [comment]
I think there's going to be a LOT of options added to the Lua config and dynamic power can definitely be one. I feel like we can take this now though and add a Lua setting for it once that's available.

**Comment by pkendall64** [comment]
Sounds like a plan!

**Pull request merged**
