### PR TITLE
Wireless Head Tracker

### PR DESCRIPTION
**Pull request by pkendall64**
This PR builds on PR #2041 "Backpack version command" and adds the following features
1. adds a command to enable VRx head tracking messages to be sent from the VRx (goggles) to the TX module
2. adds Lua configuration (at the model level) in the Backpack menu to configure a channel to enable/disable the head tracking and which channel(s) to use for Pan/Tilt/Roll (specify the start channel (Pan) and Tilt/Roll are the subsequent channels).

To test this PR you currently need to have HDzero goggles flashed with this PR (https://github.com/hd-zero/hdzero-goggle/pull/135), the HDzero backpack and TX backpack flashed with the wireless head-tracking PR (https://github.com/ExpressLRS/Backpack/pull/83) as well.

### CODE REVIEW

**Comment by brandonrc** [comment]
I NEED ME SOME GOGGLES TO TEST!!!

My goggles should get here in March sometime.. hopefully?

**Review by wvarty — APPROVED** [review]

**Comment by brandonrc** [comment]
Still waiting for my hdzero goggles :(

**Review by brandonrc — APPROVED** [review]

**Comment by brandonrc** [comment]
Tested on my new HDZ goggles today :) AMAZING!!!

**Comment by obucklin** [comment]
Is there any development for a head tracker module? Can't afford the HDZero goggles at the moment :-P

I guess that would be dependent on using a larger ESP (or similar) module based Backpack with more UARTS. I could definitely see a VRX Backpack module that has built in sensors for head tracking...

Thanks for all the great work!!

**Comment by pkendall64** [comment]
> > Tested on my new HDZ goggles today :) AMAZING!!!
> 
> Any chance of someone writing a tutorial and link all the files to do wireless head tracking? Or even make a video about it with files linked? I would like to try it, but I need a hint on how to. All I could do so far is flash the master branch of ELRS and the backpack (goggles and TX) in hopes that the function is merged. Do I need a special goggle Firmware for it as well? I am on the latest.

If you've flashed the master branch of ELRS and the backpacks to both TX and VRX, and you are using the latest version of the goggle firmware then you have everything good to go.

**Comment by HazzaHFPV** [comment]
@pkendall64 thank you for the reply :)

So, I can't figure it out unfortunately. I can activate HT in the LUA-Script of my Namimno Flash TX-Module. I can set the starting AUX-Channel for the head tracker. Module is set to 100Hz-FULL and switch mode to 8CH. I activated the tracking in the HDZero goggles. But what now?
Backpack works as far as changing channels on the Goggles goes, but what do I need to set to get the HT-Signal to the ELRS-TX-Module? I am not getting any movement of the head-tracking channels, but I can't get behind what is missing.

**Comment by pkendall64** [comment]
> EDIT: I found the solution. Switching HT to "on" in the LUA-Script actually does not activate the function as you would expect. The Module will just send "1500" on the head-tracking channels, but not work otherwise. Only if you chose an AUX-Channel for switching the HT-function on/off it will actually work and send the data from the goggles. Took me way to long to figure that out as I expected it to work when switched to "on".

Really, then I have a bug and I must fix it!

**Comment by xuhao1** [comment]
@pkendall64 would this become bi-directional?
May I use a button/switch on radio transmitter to reset the orientation of the head tracker?

**Comment by xuhao1** [comment]
@pkendall64 would this become bi-directional?
May I use a button/switch on radio transmitter to reset the orientation of the head tracker?

**Comment by pkendall64** [comment]
> @pkendall64 would this become bi-directional? 

Not sure what you mean by this.

> May I use a button/switch on radio transmitter to reset the orientation of the head tracker?

Yes, the intention is that when having head-tracking enabled via a switch and each time the head-tracking is enabled it resets the centre point to the current head position. Thats the way it's implemented in the HDZero goggles.

**Comment by xuhao1** [comment]
@pkendall64 that would be great!
I am thinking about to make it compatible with individual head tracker module like https://github.com/dlktdr/HeadTracker/issues/154

**Comment by zakkhoyt** [comment]
> > EDIT: I found the solution. Switching HT to "on" in the LUA-Script actually does not activate the function as you would expect. The Module will just send "1500" on the head-tracking channels, but not work otherwise. Only if you chose an AUX-Channel for switching the HT-function on/off it will actually work and send the data from the goggles. Took me way to long to figure that out as I expected it to work when switched to "on".
> 
> Really, then I have a bug and I must fix it!

Hey @pkendall64 I can confirm this bug is still a thing. 

@HazzaHFPV thank you for posting a workaround. I was convinced I was overlooking something but your workaround has been terrific.

**Comment by zakkhoyt** [comment]
For anyone having trouble getting this working. 

I was expecting to see the head tracker channels show up on my radio's Channel Output our Channel Mixer screens. It turns out this isn't how it works. I was able to see the channels moving around in iNav/BetaFlight's receiver tab though.

**Comment by driedger** [comment]
> For anyone having trouble getting this working.
> 
> I was expecting to see the head tracker channels show up on my radio's Channel Output our Channel Mixer screens. It turns out this isn't how it works. I was able to see the channels moving around in iNav/BetaFlight's receiver tab though.

Thanks @zakkhoyt 

I was having all sorts of trouble getting things to work, as I expected the head tracker channels to come through to the mixer, or through the trainer port, as a wired head tracker would. I reflashed my TX, backpack, and goggles thinking there was something wrong, but now I see the channels moving in the receiver tab of iNav.

This implementation bypasses EdgeTX and likely simplifies things considerably, but I am now finding this a limitation, as I was trying to have my pan/tilt on a 3 position switch, where: 
-100=off, 
0=wireless head tracking, +100=pot values from a mix on the radio. With this implementation I have to choose to use either wireless head tracking, or switches only as any outputs from the radio dont come through on the wireless head tracking channels. That, or I have to use 4 high res channels, which I dont have room for.

**Pull request merged**
