### PR TITLE
Upgrade ESP8266 framework to allow larger IRAM

### PR DESCRIPTION
**Pull request by pkendall64**
This allows changes to MMU_IRAM_SIZE from 32kb (0x8000) to 48kb (0xC000) but also reduces ICACHE from 32kb to 16kb.

### CODE REVIEW

**Review by JyeSmith — APPROVED** [review]

**Comment by JyeSmith** [comment]
Tested with crc13 PR https://github.com/ExpressLRS/ExpressLRS/pull/427 and full tlm enabled.

Working on 2.4 esp tx, esp rx, and CCG target.

**Comment by JBKingdon** [comment]
This is great, thanks!!

Is it worth opening an issue to remind us to put the framework back to a stable version once the required changes are released? I'm a bit nervous about us staying on master longer than needed.

**Comment by pkendall64** [comment]
What we can also do is add a commit hash to the end of the URL to fix us to a known working commit.

**Review by cruwaller — APPROVED** [review]
This is great!
Thanks a lot

**Pull request merged**
