### PR TITLE
Disable TX PA between packets

### PR DESCRIPTION
**Pull request by CapnBry**
This is an change to reduce transmitter power usage by disabling the PA in the idle time between packets.

### Details
When the TX module wants to transmit, it enables the output Power Amplifier (PA), duh. It stays enabled until the next telemetry interval, or until we go into wifi mode. However, we're only actively transmitting 82-92% of that time. This PR disables the TX PA during that idle time instead of leaving it active the entire time. ES24TX Pro on Q X7 at 500Hz 1:128 with 8.00V input:

RF Power | Total Power Before | Total Power with PR
|--|--|--|
| 25mW | 290mA | 260mA |
| 100mW | 340mA | 310mA |

Higher power levels are difficult to test with my bench power supply being all over the place but it does not seem to be a flat percentage across the board, just an offset. On the SIYI FM30 TX, there was virtually no difference in power (within margin of error) but the Namimno Voyager OLED showed similar power reduction to the ES24TX (~25mA).

A quarter of a watt seems like a lot of power being wasted by the PA when idle so it seems almost too good to be true, but maybe the front end in these ubiquitous units is just like that?

### Why was this "experimental"?
I initially declared this as experimental, but I have now used it on quite a bit of hardware and found no downside to the change. Jye mentioned one vague possible issue with one manufacturer but there have been no details so I'm discounting that report. The turnon time for the PA is 1/5th the amount of time it takes to send the packet to the RF, which then has its own delay to actually start transmitting. We have a ton of room to do this.

~~I'm not sure there's any performance degradation that comes from disabling the PA and enabling it just before TX~~. I did some testing on the unchanged code to see if the packet following telemetry was more frequently lost by the RX, which is a normal scenario where we'd have had the PA disabled. It does not appear to be lost any more frequently than packets for which the PA has been left on the whole time. Therefore I think this is safe to do since it does show some benefits. I've walked to the edge of range at 500Hz with both versions of code and the performance seems identical.

### Additional
I always try to sneak something else in with these eh?
* Changed RF HAL's `end()` method to use `TXRXdisable()` when going into wifi mode instead of just `RXenable()`. This function was not available at the time I added that and should also now disable any RX circuitry when going to wifi mode.

### CODE REVIEW

**Comment by CapnBry** [comment]
I did some testing and some measurement. With the "turn off the PA when idle" 250mW and standing down the street about 1km away, I turned on and off the feature (on a switch!) and saw no reduction LQ or RSSI, or at least no noticeable trend in the data.

The datasheets for all the sykworks frontend modules lists a PA turn on time of 800ns MAX, and the amount of time between us turning on the PA and sending the command to go to  SX1280_MODE_TX is around 38us (measured), and then it should also take the SX1280 27us (typical from datasheet) to actually start TX, so I believe there's about 50x the amount of delay needed for it to be ready.

**Comment by CapnBry** [comment]
More stats with another anonymous handset, power usage stock -> with this patch
```
10mW 2.62W -> 2.44W
25mW 2.72W -> 2.52W
50mW 2.80W -> 2.60W
100mW 2.96W -> 2.84W
250mW 3.44W -> 3.20W
```
Increased runtime from 123 minutes to 135 minutes. No noticeable change in link quality at 500Hz.

**Comment by CapnBry** [comment]
I still want this and once 2.1 drops I'm going to really start pushing hard for it! :-D

**Review by AlessandroAU — APPROVED** [review]

**Comment by JyeSmith** [comment]
This needs testing on all 1W transmitters.

The RF amp used requires Vref to be turned on and has different ramp up time between manufactures e.g. different capacitors used.

We need some comments on the below...

- Happymodel Pro modules
- Axis
- Namimno
- T Pro internal

**Comment by AlessandroAU** [comment]
@JyeSmith I had the same concerns, but I think it's alright, it happens before we do any SPI transactions in the TXnb() so we have a few dozen microseconds of headroom. Also the PA issue on those was that it didn't turn OFF fast enough, but the ON time was always pretty fast.

**Review by JyeSmith — APPROVED** [review]

**Pull request merged**
