### PR TITLE
Target E28 Internal

### PR DESCRIPTION
**Pull request by r1000ru**
Simple DIY target based on ESP32 and E28-2G4M27S transceiver with support EdgeTX passthrough
t-lite_internal

### CODE REVIEW

**Comment by deadbytefpv** [comment]
Why not _just_ use the DupleTX target?

Pinout is the same, power levels the same, power values the same..

**Comment by CapnBry** [comment]
The difference being the DupleTX target has the SKY85321 with PDET, and a backpack, and this doesn't. I think we're going to need a better solution for this instead of exploding with targets as everyone makes an "Internal TX" version of everything (including ESP-based RXes which now can be TXes too).

**Comment by deadbytefpv** [comment]
> The difference being the DupleTX target has the SKY85321 with PDET, and a backpack, and this doesn't. I think we're going to need a better solution for this instead of exploding with targets as everyone makes an "Internal TX" version of everything (including ESP-based RXes which now can be TXes too).

Ah yes.. the PDET. 
I'm sorry for not considering those.
Target will need to be "generic" and will have to consider combinations (does it have backpack? does it have RGB? and all those any user think they need for a DIY internal module)

**Comment by JyeSmith** [comment]
Agree with @CapnBry on this.  The only difference from the e28 diy target is the uart.  We need a better way of users adding custom pin configs via the Configurator for small use cases, and not directly to the main repo.

**Comment by r1000ru** [comment]
This is a very radical suggestion, but maybe pass the values of all pins and functionality as CRSF values after flashing? By default, make it possible to listen to those pins on which the module is being flashed. And the ability to record these parameters via WiFi, if it is available on the chip. Similar to unified targets from betaflight

**Comment by pkendall64** [comment]
I think we can close this PR as it will be addressed the "Unified ESP targets" PR.

**Pull request closed without merging**
