### PR TITLE
Increase 2.4G 50Hz preamble length

### PR DESCRIPTION
**Pull request by JyeSmith**
Firstly, there is still some debug code in rx_main.cpp.  So look past that if you are doing a CR.

This PR https://github.com/ExpressLRS/ExpressLRS/pull/2271 fixed the issue for all modes, but created an issue for 50Hz mode.  The issue here is that the 50Hz OTA packet time is much less than the packet interval, about 11ms.  While the other modes have packets that take up ~80% of the packet interval.

Currently when the tx done IRQ is trigger and the next packet is TLM, the tx goes immediately into receiving mode.  But when the 
tx does a LBT check and a the rssi is higher than the threshold, it will not transmit.  So now there is no tx done IRQ and receiving mode is entered at Tock.

This is an image of 150Hz mode with an LBT event just be receiving TLM.  We can see both the tx and rx have tocks that are close, and the tx enters receiving mode at a similar time to the rx transmitting.  TLM is received successfully.
image

Here is an image of 50Hz with the same LBT event before TLM.  The rx sends TLM as it should on its Tock.  But the Tx does not enter receiving mode until its Tock and the TLM packet is missed.  The massive offset is due to the rx syncing its Tock 200us after processing a received packet.
image

Here is 50Hz again but with a 8700us offset in place of the 200us.  Now both Tocks are aligned and TLM is received after an LBT event.
image

A similar problem exists with F500Hz but its less of a concern.  This mode is more likely to be used during racing with TLM turned off.

A possible fix is to have RF mode specific PacketToTockSlack values which align Tocks. An alternative is to pad out the packet with preamble and make it longer.  But this feels like we are just creating extra RF noise.  

Our HW time also doesnt appear happy with large slack values.  A hybrid approach may be better where the 50Hz packet gets some more preamble, and RF mode specific slack values are used.  Note that Tocks do not need to be perfectly aligned due to half of the OTA packet already being preamble.  But in the case of 50Hz they need to be much closer to allow the tx receiver timeout used for TLM to be canceled.

### CODE REVIEW

**Comment by JyeSmith** [comment]
In the end I wasnt happy with the offset changes for all modes.  It just started to induce other issues with missed TLM packets with LBT on other modes.  For now increasing the preambles looks to be the best approach.  Its more rf noise but the duty cycle is similar to other rf modes.

This is still compatible with 3.x if a users only flashes either the rx or tx.

For the record below is the slack I measured for each mode.  This will be useful later for the LR1121 work.  L500 Diversity receivers may not be possible with the LR1121 due to its slow command processing times.

F1k, D250, D500 - 380us
L500 - 280us
L333 - 400us
L250- 410us
L150 - 450us
L100 - 2040us
L50 - 3700us

**Review by pkendall64 — APPROVED** [review]

**Comment by schugabe** [comment]
I did try it on a SuperD + Zorro tx in LBT mode and get constant tlm lost/recovered on 50Hz with this change.

**Comment by pkendall64** [comment]
I've retested this as I realised I used a receiver that was 10mW limited and so was not doing LBT!
With a 100mW I get the same outcome, telemetry lost/recovered continuously.

**Comment by JyeSmith** [comment]
Closing as this doesnt appear to be working for everyone.  It also only 'fixes' a super minor edge case with LBT.

**Pull request closed without merging**
