### PR TITLE
FRM301 support

### PR DESCRIPTION
**Pull request by gagarinlg**
This PR is based the work being done for PR #1064.

- [x]  module communication with EdgeTX on PL18
- [x] LUA script connection
- [x] binding receivers
- [x] telemetry
- [x] enabling the bootloader
- [ ] flashing form the radio
- [ ] make FRM301 available in ExpressLRS configurator
- [ ] apply remaining review remarks from the last PR

If possible, I would like to get some help on the configurator integration.

### CODE REVIEW

**Comment by rotorman** [comment]
I tested this PR with Paladin EV (with FRM301 RF-module) running EdgeTX v2.8.0-dev (see https://github.com/EdgeTX/edgetx/wiki/Flashing-EdgeTX-to-Flysky-PL18-or-Paladin-EV ) and DIY-PWM ELRS Rx flashed with ELRS v3.0.0-rc2. FRM301 flashed via SWD.
I could use ELRS v3 LUA and TBS Agent Lite v0.96 for configuration, had a successful link and could actuate the servos attached to the RX.

**Comment by porfiheli** [comment]
I have just tested the FRM301 firmware with the flysky FTr10 receiver and it is working as transmitter.
- Sport pin of JR Bay connected to the receiver SENS Pin (UART1 of the STM32F030) 
- SWD connector of FTr10 receiver has the same order as the FRM301 tx module

Issues found: sometimes the lua script takes a long time to load all the data. Also changes with the lua script are sometimes not saved. Bind function from the lua script worked.
Tested with Radiomaster TX16S with Edge-TX
image

**Comment by gagarinlg** [comment]
It is probably not to hard to create a receiver firmware based on that PR.

**Comment by gagarinlg** [comment]
@porfiheli did you ever continue working on the boot loader?

**Comment by porfiheli** [comment]
> @porfiheli did you ever continue working on the boot loader?

@gagarinlg i didnt work on the bootloader, i focused first on getting the firmware working.

**Comment by gagarinlg** [comment]
OK thx.
I think I will try to get a bootloader working next.

**Comment by porfiheli** [comment]
@gagarinlg here is the pin mapping of the FTr10 receiver.

2022-09-09 FTr10 Pin Mapping

**Comment by gagarinlg** [comment]
I am still on this, it just got pushed back by some other stuff.

**Comment by JyeSmith** [comment]
@gagarinlg would you like me to leave this open for now?  Doesnt look like there has been much action recently.

**Comment by gagarinlg** [comment]
Please leave it open for now, I plan to continue the work on it soon.

**Comment by richardclli** [comment]
@gagarinlg So is this branch still works or not?

**Comment by gagarinlg** [comment]
Currently not, I need to put some work I to it, it stopped working after the last rebase.

**Comment by BlueskyFR** [comment]
@gagarinlg is there any hope for development to continue on this PR? I am sooo interested by compatibility with the EL18! 😍

**Comment by richardclli** [comment]
> @gagarinlg is there any hope for development to continue on this PR? I am sooo interested by compatibility with the EL18! 😍

I have worked out 2 branches for v3.0.1 and v3.2.0 and make it compilable.  However, it is not working properly during testing.  Need some time to figure out what the problem is.

https://github.com/richardclli/ExpressLRS/commits/frm301-v3.0.1
https://github.com/richardclli/ExpressLRS/commits/frm301-v3.2.0

However, the RAM resources is already quite critical for FRM301 to runt he ELRS, so......... may need to change the MCU to support future versions.

**Comment by BlueskyFR** [comment]
> > @gagarinlg is there any hope for development to continue on this PR? I am sooo interested by compatibility with the EL18! heart_eyes
> 
> I have worked out 2 branches for v3.0.1 and v3.2.0 and make it compilable. However, it is not working properly during testing. Need some time to figure out what the problem is.
> 
> [richardclli/ExpressLRS@`frm301-v3.0.1` (commits)](https://github.com/richardclli/ExpressLRS/commits/frm301-v3.0.1) [richardclli/ExpressLRS@`frm301-v3.2.0` (commits)](https://github.com/richardclli/ExpressLRS/commits/frm301-v3.2.0)
> 
> However, the RAM resources is already quite critical for FRM301 to runt he ELRS, so......... may need to change the MCU to support future versions.

Thanks for the answer! I'll try this when I can. Is work going to continue then?

Also, does something need to be done to make it compatible with an actual receiver?

**Comment by gagarinlg** [comment]
due to the flash am RAM constrains on the FRM301 it is not feasible to do this. It would be better to just make an ELRS module that fits the PL18 module bay.

**Comment by BlueskyFR** [comment]
> due to the flash am RAM constrains on the FRM301 it is not feasible to do this. It would be better to just make an ELRS module that fits the PL18 module bay.

What would you recommend to make the controller work with elrs then?

**Comment by gagarinlg** [comment]
Either via the AUX uart or by making a module that fits into the slot of the PL18.
@richardclli would you share your stl files?

**Comment by rotorman** [comment]
See here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/tree/master/STM32%20PCB/Flysky%20PL18/Casing

**Pull request closed without merging**
