### PR TITLE
Removing hardware files from source repository.

### PR DESCRIPTION
**Pull request by brandonrc**

### CODE REVIEW

**Comment by CapnBry** [comment]
Geez 356 files eh?

After an hour of discussion on discord we came to the conclusion that the simplest thing to do that kept everything intact was to just delete the folders and that's it. This keeps the history for the files intact without having to git log --follow (filename), doesn't break the configurator by moving the source root, break any refs to old file locations, or require that all outstanding PRs be redone to point to new file locations or branch references.

It isn't ideal but I think not having the git root and the project files root (which are all in src/ still) is an OK compromise to keep all those things.

**Review by CapnBry — APPROVED** [review]

**Comment by brandonrc** [comment]
@CapnBry @AlessandroAU updated the wiki... 

Do we want to merge this now?

**Comment by AlessandroAU** [comment]
Lets do it

**Comment by AlessandroAU** [comment]
Ah, does this break the lua script download button on the configurator?

**Pull request merged**
