### PR TITLE
Add bayck board

### PR DESCRIPTION
**Pull request by BAYCKRC**

### CODE REVIEW

**Comment by JyeSmith** [comment]
I dont think this PR is required with unified targets.

**Comment by BAYCKRC** [comment]
Do you have any better suggestions? We need to reflect the brand logo in our products.

I see that most manufacturers have proprietary firmware names.

**Comment by BAYCKRC** [comment]
> 我认为这个 PR 不需要有统一的目标。

Do you have any better suggestions? We need to reflect the brand logo in our products.

I see that most manufacturers have proprietary firmware names.

**Comment by pkendall64** [comment]
We now just add a target to `targets.json` in the targets repository https://github.com/ExpressLRS/targets

**Pull request closed without merging**
