### PR TITLE
change CR 4/5 to LI 4/6

### PR DESCRIPTION
**Pull request by JyeSmith**
Changing CR to Long Interleaving 4/6 looks to be quicker OTA based on the semtech calculator.  It will provide better FEC and burst interference.

OTA to be updated by @AlessandroAU in a separate PR.

Testing required.  No rush to merge this one.

### CODE REVIEW

**Comment by JBKingdon** [comment]
@JyeSmith Can you add some info about why the change is being made to the description? Would make things easier if we ever have to look back through the commit history for some reason.

**Comment by JBKingdon** [comment]
Code change looks good, but I think there will be changes to the OTA that need to be updated in the ExpressLRS_AirRateRFperf arrays?

**Comment by cruwaller** [comment]
Change to CR_LI is good thing.
Are you sure that ~500us budget is enough? How long does it take to process packet + configure next reception on ESP or STM32L4xx? I think current config is a bit too optimistic if RX timing fluctuates a bit (as it does always).

**Review by cruwaller — APPROVED** [review]

**Comment by JyeSmith** [comment]
I put 16 packs through 500hz, LI 4/6 with no issues.  Plus some low rssi flying,

The other modes still need proper testing.

**Comment by AlessandroAU** [comment]
had some weird things happen on the PFD branch with LI_4_6, needs some investigation before merge

**Pull request merged**
