### PR TITLE
Binary release firmware here we come

### PR DESCRIPTION
**Pull request by pkendall64**
# Problem
Many users have problems building the firmware, either because of firewalls or slow internet access or problems with their computer.

# Solution
Binary firmware releases!

This is the beginnings of being able to distribute binary firmware where configurator just configures the binary image using the included python script.

All the defines we know and love are still available for users/devs that would rather build the firmware themselves. The user defines just provide the default values built into the firmware.

Regulatory domain is also configurable with the binary configurator so we have a the following binaries
- 900MHz
   - FCC (the regulatory domain is selectable via the binary configurator)
- 2.4GHz
   - FCC
   - LBT

We would need configurator to change so that on the release page for 3.0 (or whenever this makes it in, if it does) that it calls the configurator python script with the correct parameters.

A binary flashing script has also beed added which inspects the binary firmware being uploaded and detects the available upload methods, and the default wifi address to connect to.

# Configurator Tool Usage
```
usage: binary_configurator.py [-h] [--print] [--phrase PHRASE] [--device-name DEVICE_NAME] [--ssid SSID] [--password PASSWORD] [--auto-wifi AUTO_WIFI]
                              [--no-auto-wifi] [--rx-baud [RX_BAUD]] [--invert-tx] [--no-invert-tx] [--lock-on-first-connection]
                              [--no-lock-on-first-connection] [--tlm-report [TLM_REPORT]] [--sync-on-arm] [--no-sync-on-arm] [--uart-inverted]
                              [--no-uart-inverted] [--unlock-higher-power] [--no-unlock-higher-power]
                              [--buzzer-mode {quiet,one-beep,beep-tune,default-tune,custom-tune}] [--buzzer-melody BUZZER_MELODY]
                              [--domain {eu_433,au_433,in_866,eu_868,au_915,fcc_915}]
                              file

Configure Binary Firmware

positional arguments:
  file

optional arguments:
  -h, --help            show this help message and exit
  --print               Print the current configuration in the firmware
  --phrase PHRASE       Your personal binding phrase
  --device-name DEVICE_NAME
                        The device name to display in the LUA status bar
  --ssid SSID           Home network SSID
  --password PASSWORD   Home network password
  --auto-wifi AUTO_WIFI
                        Interval (in seconds) before WiFi auto starts, if no connection is made
  --no-auto-wifi        Disables WiFi auto start if no connection is made
  --rx-baud [RX_BAUD]   The receiver baudrate talking to the flight controller
  --invert-tx           Invert the TX pin on the receiver, if connecting to SBUS pad
  --no-invert-tx        TX pin is connected to a regular UART (i.e. not an SBUS inverted pin)
  --lock-on-first-connection
                        Lock RF mode on first connection
  --no-lock-on-first-connection
                        Do not lock RF mode on first connection
  --tlm-report [TLM_REPORT]
                        The interval (in milliseconds) between telemetry packets
  --sync-on-arm         Send sync packets to the RX when armed
  --no-sync-on-arm      Do not send sync packets to the RX when armed
  --uart-inverted       For most OpenTX based radios, this is the default
  --no-uart-inverted    If your radio is T8SG V2 or you use Deviation firmware set this flag.
  --unlock-higher-power
                        DANGER: Unlocks the higher power on modules that do not normally have sufficient cooling e.g. 1W on R9M
  --no-unlock-higher-power
                        Set the max power level at the safe maximum level
  --buzzer-mode {quiet,one-beep,beep-tune,default-tune,custom-tune}
                        Which buzzer mode to use, if there is a buzzer
  --buzzer-melody BUZZER_MELODY
                        If the mode is "custom", then this is the tune
  --domain {eu_433,au_433,in_866,eu_868,au_915,fcc_915}
                        For SX127X based devices, which regulatory domain is being used
```

# Flasher Tool Usage
```
usage: binary_flash.py [-h] [-p PORT] [-b BAUD] -m {wifi,uart,bf,etx,stlink} [-f] [-c] file

Upload Binary Firmware

positional arguments:
  file

optional arguments:
  -h, --help            show this help message and exit
  -p PORT, --port PORT  SerialPort or WiFi address to flash firmware to
  -b BAUD, --baud BAUD  Baud rate for serial communication
  -m {wifi,uart,bf,etx,stlink}, --method {wifi,uart,bf,etx,stlink}
                        Upload Method
  -f, --force           Force upload even if target does not match
  -c, --confirm         Confirm upload if a mismatched target was previously uploaded
```

### CODE REVIEW

**Comment by jurgelenas** [comment]
How we are going to flash it? Or do we intend to go with build manual flashing where person upload the .bin file?

**Comment by pkendall64** [comment]
> How we are going to flash it? Or do we intend to go with build manual flashing where person upload the .bin file?

Flashing will not be a problem, all the flashing code we have already an be re-used. It's just a matter of calling the right script with the right parameters.

On writing this I think I'll write a wrapper script to do it. something like `flash_binary.py -wifi/-bf/-uart firmware.bin` should be easy to hook up in configurator?

**Comment by jurgelenas** [comment]
> > How we are going to flash it? Or do we intend to go with build manual flashing where person upload the .bin file?
> 
> Flashing will not be a problem, all the flashing code we have already can be re-used. It's just a matter of calling the right script with the right parameters.
> 
> On writing this I think I'll write a wrapper script to do it. something like `flash_binary.py -wifi/-bf/-uart firmware.bin` should be easy to hook up in configurator?

Yeah script is perfect!

**Comment by schugabe** [comment]
Why did you add two options --opentx-sync-autotune and --no-opentx-sync-autotune for the same config value since we also have a default value. I think the default could be off and with the option it gets enabled.

How would that work with PIO?

If I read the code correct the script searches the config position with the help of the magic bytes. I guess it would be possible that we get a bin that has the magic bytes at a second place? So maybe we need a sanity check that the sequence is only found once to catch some potential errors if the (unlikely) case happens.

**Comment by pkendall64** [comment]
> Why did you add two options --opentx-sync-autotune and --no-opentx-sync-autotune for the same config value since we also have a default value. I think the default could be off and with the option it gets enabled.
> 

I have the `no-` options so you can turn the value off if it is already on in the built firmware.

> How would that work with PIO?

PIO still works as usual and doesn't need to use the binary configurator at all.

> 
> If I read the code correct the script searches the config position with the help of the magic bytes. I guess it would be possible that we get a bin that has the magic bytes at a second place? So maybe we need a sanity check that the sequence is only found once to catch some potential errors if the (unlikely) case happens.

We could add a check to make sure that there is only one "magic" found, but it's highly unlikely and we'd have to do something to rebuild the firmwares if it ever happened!

**Comment by pkendall64** [comment]
Closing becasue "Unified targets" subsumes a lot of this functionality

**Pull request closed without merging**
