### PR TITLE
Display WiFi running screen on OLED/TFT when WiFi auto starts

### PR DESCRIPTION
**Pull request by pkendall64**
As it says in the tin 😄 

Also, updates the screen when going from AP->STA and vice-versa.

### CODE REVIEW

**Comment by JyeSmith** [comment]
Sooo the tin label needs correcting 😄 

Testing on an Aion nano and it boot loops.  Below is a quick debug showing where it craps out.

image

**Comment by deadbytefpv** [comment]
With 5a1112e on the same module and a Namimno Flash, the boot loop happens.

Tested on a Jumper Aion Nano with 9c92c33.
The boot loop is no longer happening after a successful flash.

with the Jumper Aion Nano being powered via USB, with Auto WiFi set (default 60s), once that set interval has elapsed, wifi would activate, accompanied by changing of the screen indicating it is in wifi mode with instructions to which address to load in the browser to access the WiFi page. 
Can then confirm PR is working as intended.

**Comment by pkendall64** [comment]
> Add: Also tested on a Namimno OLED Flash. One thing I have noticed is that the wifi mode will activate and take over the screen even when you're fumbling and playing with the joystick. I have no strong objection to this though, as any setting you set will not be saved once power is removed. Though from a UX standpoint, wifi mode is intrusive. Could we perhaps delay wifi mode if joystick activity is detected?

You know, I was thinking of putting up an error screen if there was no connection to the handset or other problems. Then realised it would impact us as devs not being able to check the display code with just a USB connection. So 🤷‍♂️

**Comment by JyeSmith** [comment]
> You know, I was thinking of putting up an error screen if there was no connection to the handset or other problems. Then realised it would impact us as devs not being able to check the display code with just a USB connection. So 🤷‍♂️

Maybe not an error screen, but dont display the rate/tlm/power since the module is not actually transmitting?

**Comment by pkendall64** [comment]
> > You know, I was thinking of putting up an error screen if there was no connection to the handset or other problems. Then realised it would impact us as devs not being able to check the display code with just a USB connection. So 🤷‍♂️
> 
> Maybe not an error screen, but dont display the rate/tlm/power since the module is not actually transmitting?

Yes, good idea. But that would be a different PR to this, or do you think add that to this PR as well?

**Comment by JyeSmith** [comment]
I think another PR.

**Review by JyeSmith — APPROVED** [review]

**Pull request merged**
