### PR TITLE
STM32 platform upgrade

### PR DESCRIPTION
**Pull request by pkendall64**
Upgrade all the STM32 based platforms to a consistent STSTM32 version 15.1.0 and add the `-flto` flag so the devices which very little flash have a bit more space left for new features going forward.

I only have R9M and R9MM that I can test with so if others can test the following that would be awesome.

- CCG Nano or HM PP
- Ghost TX & Atto RX
- R9MX
- FM30
- FM30 Mini
- Namimno 900 & 2400

~The following targets will also need to update their bootloader firmware as the change to the base platform has moved the `Reset_Handler` function and HMI handler functions to past the initial 64K of flash!~

- ~Frsky_TX_R9M_LITE_PRO~
- ~Frsky_RX_R9MX~
- ~Frsky_RX_R9SLIMPLUS_OTA~
- ~Jumper_RX_R900MINI~
- ~HappyModel_RX_ES915RX~
- ~Frsky_RX_R9MM_R9MINI~
- ~Frsky_RX_R9SLIMPLUS~

Edit: The bootloader's don't need updating with PR #507

### CODE REVIEW

**Comment by brandonrc** [comment]
I can test the Ghost TX, Atto RX, and HM pp tomorrow.

**Comment by pkendall64** [comment]
I'm having real problems with this platform version on the R9MM. It uploads and basically completes then reboots and the app crashes all the time so I see the LED quickly blink off then back on. If I go back to version 13, and rename the variant header file it works.

**Comment by deadbytefpv** [comment]
I can test with a Namimno Flash gen1.

Will report soon.

**Comment by CapnBry** [comment]
I can test with FM30 and FM30 Mini, will report back in a day.

**Comment by maybenikhil** [comment]
Will test Namimno Flash, Voyager and Ghost TX and maybe a PP if i can find it.

**Comment by maybenikhil** [comment]
Tests:
- NamimnoRC Flash TX - works, binds, shows up in LUA
- NamimnoRC Voyager TX - works, shows up in LUA (didn't have RX to check easily)
- IMRC Ghost TX - works, binds, shows up in LUA
The PP is on loan to someone

**Comment by CapnBry** [comment]
Works with FM30 TX and FM30 Mini as RX and as TX. Lua works and OTA connectivity works as expected.

Not sure about the ResetHandler stuff, I flashed via STLINK for the RX and via DFU for the TX as my RX isn't set up to be in an FC.

**Comment by Dropsleutel** [comment]
"The following targets will also need to update their bootloader firmware" 
Can the new bootloader be flashed via the old bootloader ? Or is it new packed flashed with the new firmware ?

**Comment by pkendall64** [comment]
> "The following targets will also need to update their bootloader firmware" Can the new bootloader be flashed via the old bootloader ? Or is it new packed flashed with the new firmware ?

With the changes made in PR #507 we don't actually need to reflash the bootloader.

**Comment by StonedDawg** [comment]
tested this with R9M and R9 SLIMPLUS OTA, changed configs, packet rate, switch mode, telemetry rate, and all works fine

**Review by brandonrc — APPROVED** [review]

**Review by JyeSmith — APPROVED** [review]
Tested NamimnoRC Flash via st link upload, to HM PP via BF passthrough (existing BL).  All good.

**Pull request merged**
