### PR TITLE
SPRacingRXN1 - Initial support

### PR DESCRIPTION
**Pull request by hydra**
See https://github.com/ExpressLRS/targets/pull/57

### CODE REVIEW

**Comment by JyeSmith** [comment]
Any reason this PR is required and its not using the Unified target?

**Comment by pkendall64** [comment]
This is not how we do things now. This can be closed.

**Comment by hydra** [comment]
> Any reason this PR is required and its not using the Unified target?

Nope, just a lack of understanding on my part I think.  I wasn't sure if this was needed or not and/or if there was anything else that needed doing instead.  I'm guessing the other PR is sufficient by itself and that I'm exepected to use the 'Unified_ESP32_2400_RX_via_UART' and pick the option that appears for the target when prompted by the build system.

It was nice to be able to hit build, do something else and have it built and uploaded instead of having to answer the 'choose configuration' question and then let it upload every time I want to test code changes though.  Any way around that?

**Comment by pkendall64** [comment]
Not currently but I'd like to add an environment variable with the target id to flash automatically. Should be fairly easy to do.
If you are thinking about for flashing multiple devices quickly, we have something for that.

**Pull request closed without merging**
