### PR TITLE
Implement event types and add event handlers to serial devices

### PR DESCRIPTION
**Pull request by LupusTheCanine**
Adds event type identifiers
Adds event handler support to serial device handlers.
pulled from #2964 as requested.

### CODE REVIEW

**Comment by pkendall64** [comment]
@LupusTheCanine I actually have a different implementation of this where the devices can actually subscribe to the events that they are interested in and will only be called if that event type is fired, which means that the `event` function for a device will only be called if the event that has been triggered is subscribed to by the device.

**Comment by LupusTheCanine** [comment]
> @LupusTheCanine I actually have a different implementation of this where the devices can actually subscribe to the events that they are interested in and will only be called if that event type is fired, which means that the `event` function for a device will only be called if the event that has been triggered is subscribed to by the device.

Will it support adding event handlers to devSerialIO? I need that so I can update MavlinkSerial SysIDs on the fly. When is it expected?

**Comment by pkendall64** [comment]
Yes it will allow that. I'm just waiting in Phase 6 to be approved and merged before I do a couple of event based PRs.

**Comment by LupusTheCanine** [comment]
Sorry I mixed up devSerialIO with SerialIO. I need to add event handler (to devSerialIO) from within serialIO so it only works when SerialMavlink is the active serial driver.

**Comment by pkendall64** [comment]
Closing this as we have an eventing framework in place now in the master branch.

**Pull request closed without merging**
