### PR TITLE
Start dynamic power low instead of high

### PR DESCRIPTION
**Pull request by CapnBry**
This PR starts the TX at MinPower instead of configured (max) power on startup or packet rate switch when dynamic power is enabled.

### Why change it?
I think most users expect that when they turn their handset on, the TX is going to be in low power mode instead of high power mode. For almost 100% of the cases, this is going to be the desired behavior and the receiver is almost always close to the transmitter on power up, making MinPower sufficient for connection.

### Why it was the way it was
The thinking with the existing code was that it was the safest thing to do. If the handset is powered while the receiver was far away and ELRS is in an "idle" state, there was no way for the power to increase which means we might not ever get a connection when it is needed most. This might be the case if
* The handset battery dies on a long range flight and needs to be swapped
* The handset crashes due to a Lua problem and needs a reboot or goes into Emergency Mode on its own
* Dropping the handset knocks the batteries and causes it to lose power

The way it works now guarantees full power on startup for the best chance of establishing a connection, however, this thinking was before we added the IsArmed check to the mix. The IsArmed check forces max configured power if armed and the TX is in a "disconnected" state. This provides the stimulus needed to go from low to high power in the above cases on power up. If any of those occur, it is always going to be with the craft armed already, so the existing logic will immediately boost the power due to being disconnected with the arm switch high.

### Drawbacks
Anyone with dynamic power enabled that does not have an arm switch OR dynamic power on a switch will be screwed if one of the above cases happens in flight. I don't think this is a common use case and if that's a concern then that use should have dynamic power on a switch for an emergency reconnect. Generally MinPower is going to be sufficient for a connection even with that scenario due to the 💪 range of ExpressLRS anyway.

### CODE REVIEW

**Comment by avsaase** [comment]
Yes! This is much more intuitive, and also great when doing bench work.

The only scenario where this change could bite you is when you have disarmed with your quad or plane sitting far away and you need to reboot your handset. In that case, it could be annoying or perhaps even dangerous that you have to arm for the link to recover. Say you crashed your quad into a tree, and your handset battery dies. You switch batteries and now you don't have telemetry to check the GPS coordinates because the link doesn't recover on 10mW. You then need to arm to boost the power, the link recovers, the quad arms and the motors spin up while the props are stuck. 

It's a pretty unlikely scenario and if this happens you could always set up a channel to boost the power to max. I am definitely in favor of this change. It's just something to be aware of.

**Comment by DM4DS** [comment]
The dynamic feature is a option and so I´m fine with low ---> high if changed, but then I´m sure will never  use it :)

For me is the "safe version" the better and thats high ---> low . You can change by hand to 25mW on benchwork.

Annoyed me more than one time that my VTX switched to PIT Mode and I lost link, so I disabled it too.

**Comment by CapnBry** [comment]
> For me is the "safe version" the better and thats high ---> low . You can change by hand to 25mW on benchwork.

For bench work, even 1mW of ELRS output is tons more power than is needed to connect from even a room away though. It isn't like VTX pit mode where the power is so low you need to be close to get a signal, so I feel like the case  of "need max power to connect on the bench" isn't valid.

@avsaase you're right, that's the one scenario where this change would be detrimental. I think that's mitigated by the fact that if you're stuck in a tree for so long that you need to swap the battery, you can just go into the Lua and turn off dynamic power completely, right?

**Comment by avsaase** [comment]
> @avsaase you're right, that's the one scenario where this change would be detrimental. I think that's mitigated by the fact that if you're stuck in a tree for so long that you need to swap the battery, you can just go into the Lua and turn off dynamic power completely, right?

Okay, so then even this edge case is covered and there is really no way not to do this. In the meantime, I flashed this branch and I'm already super happy with it because I always forget to decrease the power on the bench and the module gets pretty warm at 250mW.

**Review by JyeSmith — APPROVED** [review]

**Comment by SunjunKim** [comment]
I was thinking the same thing, but additionally having a checkbox option on Lua to set like "Start on high power".
This will allow some special users (aka long-range users) to use the option, while the rest of the users start on low power by default.

**Comment by CapnBry** [comment]
Yeah no new options if I can avoid it because every option takes precious flash space (many targets can already not be built with debug logging already) and slows down the loading of the Lua menu. I also don't think there's any reason to have another option because like you said, there's already an option to disable the dynamic power on a switch, so there's that way to get full power for those rare usage scenarios.

The only scenario not covered by the existing code without even setting up dynamic power on a switch is if the user wants to start their radio at high power without the arm switch on. Why would a user need to start their radio at max power and disarmed? Their model is 20km away **and** they want it to fall out of the sky? I really can't think of an actual reason for starting high now that we have the "max power if armed and disconnected" logic.

And this is coming from the person (me) who fought to keep "start with power high" the whole time. It just isn't necessary now with the updated code.

**Review by FOG-Yamato — APPROVED** [review]

**Pull request merged**
