### PR TITLE
GemX Lua RF Mode Labels

### PR DESCRIPTION
**Pull request by JyeSmith**
Currently there is no obvious way to identify the Sub GHz band from the 2.4GHz RF modes in Lua.  This PR replaces the sensitivity values with an identifier.  It not great to remove this info, but it is also easily found at https://www.expresslrs.org/info/signal-health/?h=sensitivity#rf-mode-indexes-rfmd

The GemX modes are identifiable with the 'X' prefix and the sensitivity values have been left.  Being new modes users will be interested to see the sensitivity values.

Im not set on these labels and open to discussion on alternatives.  Just keep in mind we need to keep them shortish,

### CODE REVIEW

**Comment by radio-mistress** [comment]
` "H50(-115dBm);H100 Full(-112dBm);H150(-112dBm);H250(-108dBm);H333 Full(-105dBm);H500(-105dBm);" // 2.4G
  "L50(-120dBm);L100(-117dBm);L100 Full(-112dBm);L200(-112dBm);L200 Full(-111dBm);L250(-111dBm);" // 900M
  "X100 Full(-112dBm);X150(-112dBm)" // Xband`  I vote for something like this as the rate unit is commonly understood to be HZ and it kinda matches the High Low designator with X.

**Comment by JyeSmith** [comment]
@radio-mistress Theissue with using L is that we already informally use it for Lora when distinguishing been Lora and FLRC modes.

The other thought was S for sub GHz.

**Review by CapnBry — APPROVED** [review]
Alright man, I've spend 4 days now thinking I was going to come up with better labels but I can not, so good work! I thought something with "SubG" would be more compact but everything is just too long.

I'm not sure if it is intentional but `200Hz Full Low Band` gets cut to `200Hz Full L` on B&W screens and you just can't get a better "giving you all the info you need in a too-small space" than that.

Also agree on the `L` already being known as "the LoRa modes"

**Comment by JyeSmith** [comment]
The nice thing is that this is just a label that can be changed in a bug fix.  Once users (JB) start to complain we will get some good suggestions.

**Review by wvarty — APPROVED** [review]

**Comment by wvarty** [comment]
I'm not really a fan of what we currently have (too long IMO), but I'll approve it for now, because it's an improvement over having nothing at all, which is horribly unclear for me.

**Pull request merged**
