### PR TITLE
Phase 5: STM32 Obliteration: RX device cleanup

### PR DESCRIPTION
**Pull request by pkendall64**
This one just cleans up a lot of the defines that were there to disable certain features that were not available to STM32 based receivers.

### CODE REVIEW

**Review by JyeSmith — APPROVED** [review]
Test with Nomad to BAYCK rx and mavlink... didnt break!

**Review by mha1 — APPROVED** [review]

**Comment by pkendall64** [comment]
> Will external i2c baro still work with ESP8285 devices? 

No, ESP8285 does not support the Baro sensors.

**Comment by pkendall64** [comment]
> > No, ESP8285 does not support the Baro sensors.
> 
> So you are going to remove support in 4.0?
> 
> Quote from #2480
> 
> > ESP8266 unified targets also can use barometers now as well

Well then it should still work. I'll have to check when I'm back with my gear.

**Comment by pkendall64** [comment]
> And will USE_MSP_WIFI change to PLATFORM_ESP32 break TCP Betaflight configurator from all ESP8285 receivers? #1274

No, because that will just change to TARGET_RX

**Review by wvarty — APPROVED** [review]

**Pull request merged**
