### PR TITLE
LUA field set from module

### PR DESCRIPTION
**Pull request by StonedDawg**
to prevent user to keep updating their LUA script, this will make LUA script fetch all the parameter field setups and values from the tx module side. 

we can use the crsf default LUA script but will not be able to pop up any warning info that we want to pass to the user, therefore there is also device.lua in this branch to provide a similar-like-popup-screen to show info to users.

for HM 915TX and R9M, I added a debug_suppress to not compile all the serial.println since flash size is becoming critical.

### CODE REVIEW

**Comment by CapnBry** [comment]
This is looking good! Happy to see it working as it was a pretty giant task.

I'd like to see all the giant case code removed though and switched to a data-driven approach. Like instead of every parameter having to build its packet and set buffers and stuff, It would be an array of config parameter structs like
```
struct tagConfigurableItem {
    uint8_t id;
    uint8_t type;
    uint8_t min;
    uint8_t max;
    uint8_t default;
    const char *label; // probably a pointer to a flash string
    const char *options; // pointer to select options
    getfunc getter; // pointer to getter function
    setfunc setter; // pointer to setter function
};

union tagGetFunc {
    std::function<uint8_t()>getU8;
    std::function<uint16_t()>getU16;
...
} getfunc;

union tagGetFunc {
    std::function<void(uint8_t)>setU8;
    std::function<void(uint16_t)>setU16;
...
} setfunc;
```
Then tagConfigurableItem could also be in flashmem for stuff that supports it and sending the parameters is as easy as iterating the list with gets, then setting an item is just find the tagConfigurableItem, call the setter. I don't think the above structs and unions have everything that you need, but that's the gist of what I think it should be. 

Also style tip you don't have to declare your strings with explicit lengths like
```
char textSelection[31]={"10;25;50;100;250;500;1000;2000"};
memcpy(fieldsetup2,textSelection,31);
// redone
const char textSelection[] = "10;25;50;100;250;500;1000;2000";
memcpy(fieldsetup2,textSelection,sizeof(textSelection))
```

Finally you can put DEBUG_SUPPRESS in your super_defines.txt if you want to use it rather than the environment build_flags you've included. I'd like to see this option reversed (to add like a DEBUG define that is the opposite) in 1.1 too, but that's not your problem :)

**Comment by StonedDawg** [comment]
@CapnBry thanks! yeah actually the struct is already there, i will do more fiddling to use the struct. i will optimize this and confirm when it is ready.
oh yeah I see this super_defines now. Ok will put it in there as well!

**Comment by CapnBry** [comment]
> @CapnBry ah ok, i thought i put it there just in case someone wants to try with r9m or the happymodel 915tx since these 2 targets having flash space issue... i will revert back

I would suggest putting a line at the top of tx_main to make it just like rx_main instead of messing with the build system. Really the entire "just write to `Serial` wherever you damn well feel like it regardless of what that is attached to" needs to go, so I feel your pain in trying to force some sanity into this.

**Comment by StonedDawg** [comment]
@CapnBry ah ok, I didn't feel to good about tinkering the debug print as it is outside of this PR.

**Comment by CapnBry** [comment]
Yeah for sure it is outside the scope of this PR, it is a bit of a mess currently and needs a real logging implementation instead of DEBUG_SUPRESS and Serial.print mixed in everywhere. Hope it isn't giving you too much of a problem though.

**Comment by howels** [comment]
Tested https://github.com/ExpressLRS/ExpressLRS/pull/620/commits/343f911e940949252b88834e0c9382506f8fcf70 on a deviationTX radio (T8SGv2) and it's working great.

**Review by maybenikhil — COMMENTED** [review]
Works well for me

**Comment by StonedDawg** [comment]
Thanks to belrik, @howels , @maybenikhil ,Tokyo_Dom, cprcpr, @JyeSmith 
PR has been tested on deviationtx  (t8sg), tx18s, tx16s, x9d, qx7 with  es24tx, r9m, ghost TX.

**Pull request merged**
