### PR TITLE
Package the python directory into a flasher package with shiv

### PR DESCRIPTION
**Pull request by pkendall64**
Packages the flashing code into a shiv package which is included in the firmware.zip built on github.
This allow the flashing of pre-built binaries with a vanilla python install directly using the following example command (in the unzipped firmware directory)...
```sh
python flasher.pyz --flash uart --target generic.rx_2400.plain --phrase xyz
```
You can also pass `-h` to get help about any of the available arguments to the flasher.
Also, if `--target` is not specified, a list of targets is presented from which a user can choose.

EDIT 1:
Added a `dir` flash mode which you also specify an `--out <dir>` parameter for which will copy the configured binary files to that directory, for copying to HDZero googles, or for uploading manually to the Web-UI page on devices.
 
EDIT 2:
As part of this PR I also generate an index json which is published to the artifact repository and create a workflow job that will cleanup old/stale artifacts from the repository.

The format of the json is
```json
{
  "branches": {
    "master": "d2dbbdb8bf5fd7273909001c0c73432c7843c959",
    "packaged-flasher": "7d65cc6652f02a022910dd4a084774d1a25791e7"
  },
  "tags": {
    "3.0.0": "8aa1b03e804ee896e974a05c3d9aadfb93d17069",
    "3.0.1": "2470fce853f0f9d389aada1e249c4fa1c775b9f9",
    "3.1.0": "a60040e8049e9fc2faedea3ffbbe2dc98690195c",
    "3.1.1": "2909ba2db2909b5c38a299eed575082f2894baf1",
    "3.1.2": "4da3aa7a6efc2f175b052647aa151e6c337e7b07",
    "3.2.0": "8d3388ef3369a2d8a64f92a80e42acb29f8e513e",
    "3.2.1": "8dbbdbe442660713ba1de07828ceb20cdaa5e26a"
  }
}
```

### CODE REVIEW

**Comment by SunjunKim** [comment]
WiFi upload fails, with the following error message:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                        
         Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 35  364k    0     0   35  128k      0  58399  0:00:06  0:00:02  0:00:04 58462

 35  364k    0     0   35  128k      0  40318  0:00:09  0:00:03  0:00:06 40342

 35  364k    0     0   35  128k      0  30823  0:00:12  0:00:04  0:00:08 30840

 35  364k    0     0   35  128k      0  24884  0:00:15  0:00:05  0:00:10 24894

 35  364k    0     0   35  128k      0  20896  0:00:17  0:00:06  0:00:11 23472

 35  364k    0     0   35  128k      0  18004  0:00:20  0:00:07  0:00:13     0

 35  364k    0     0   35  128k      0  15810  0:00:23  0:00:08  0:00:15     0

 35  364k    0     0   35  128k      0  14097  0:00:26  0:00:09  0:00:17     0

 35  364k    0     0   35  128k      0  12719  0:00:29  0:00:10  0:00:19     0

 35  364k    0     0   35  128k      0  11585  0:00:32  0:00:11  0:00:21     0

 35  364k    0     0   35  128k      0  10638  0:00:35  0:00:12  0:00:23     0

 35  364k    0     0   35  128k      0   9837  0:00:37  0:00:13  0:00:24     0

 35  364k    0     0   35  128k      0   9145  0:00:40  0:00:14  0:00:26     0

 35  364k    0     0   35  128k      0   8542  0:00:43  0:00:15  0:00:28     0

 35  364k    0     0   35  128k      0   8017  0:00:46  0:00:16  0:00:30     0

 35  364k    0     0   35  128k      0   7552  0:00:49  0:00:17  0:00:32     0

 35  364k    0     0   35  128k      0   7137  0:00:52  0:00:18  0:00:34     0

 35  364k    0     0   35  128k      0   6767  0:00:55  0:00:19  0:00:36     0

 35  364k    0     0   35  128k      0   6495  0:00:57  0:00:20  0:00:37     0
curl: (56) Recv failure: Connection was reset

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   
Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (6) Could not resolve host: elrs_rx.local
Warning: Problem : timeout. Will retry in 1 seconds. 2 retries left.


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     
0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (6) Could not resolve host: elrs_rx.local
Warning: Problem : timeout. Will retry in 1 seconds. 1 retries left.


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-
-     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (6) Could not resolve host: elrs_rx.local

 ** UPLOADING TO: http://elrs_rx/update
 ** UPLOADING TO: http://elrs_rx.local/update
WIFI upload FAILED!
```

**Comment by SunjunKim** [comment]
Also, "Build" button on WiFi flashing method should give gzipped firmware I believe, which is currently yielding uncompressed one.

**Comment by SunjunKim** [comment]
With build&flash button, I confirmed WiFi upload works fine on ESP8285 RX. 

However, the binary from "build" button with the WiFi flash option still gives an uncompressed one, which prevents a manual WiFi firmware update through WebUI)

(Configurator v1.5.6 gives a compressed one, just double checked)

**Comment by pkendall64** [comment]
> With build&flash button, I confirmed passthrough, uart, and WiFi upload works fine on ESP8285 RX (tested on nightly v20230420.76994.0)
> 
> However, the binary from "build" button with the WiFi flash option still gives an uncompressed one, which prevents a manual WiFi firmware update through WebUI)
> 
> (Configurator v1.5.6 gives a compressed one, just double checked)

I've fixed this by putting both .bin.gz and .bin in the output directory. The problem is that when doing a build, there is no `--flash` so theres no way to detect that we should be gzipping over the top of the .bin file.

I have not retrofitted this into the artifacts yet as I'm waiting on some changes in the configurator.

**Review by jurgelenas — APPROVED** [review]

**Review by wvarty — APPROVED** [review]

**Pull request merged**
