### PR TITLE
Targets: adds target NamimnoRC FLASH TX and RX

### PR DESCRIPTION
**Pull request by cruwaller**
NamimnoRC FLASH is 2.4GHz SX1280 based system. 
TX supports up to 1W transmit power.

### CODE REVIEW

**Comment by StonedDawg** [comment]
handset is qx7 and R9M, after flashing this, i did get the success tone but not the 2 tones that means connected.

**Comment by cruwaller** [comment]
ok, need to check R9M again. Thanks for reporting it!

**Comment by cruwaller** [comment]
I just tested this branch with R9M and seems to work without issues.
```
...
2021-04-05T00:17:34.553Z Hal Init
2021-04-05T00:17:34.556Z Use TX pin: 26
2021-04-05T00:17:34.560Z Use RX pin: 6
2021-04-05T00:17:34.562Z 2
2021-04-05T00:17:35.947Z  found! (match by REG_VERSION == 0x12)
2021-04-05T00:17:35.951Z Setting ExpressLRS LoRa reg defaults
2021-04-05T00:17:35.954Z 1000
2021-04-05T00:17:35.957Z set rate
2021-04-05T00:17:35.959Z Setting ExpressLRS LoRa reg defaults
2021-04-05T00:17:35.962Z 650
2021-04-05T00:17:35.964Z About to start CRSF task...
2021-04-05T00:17:35.966Z Start STM32 R9M TX CRSF UART
2021-04-05T00:17:35.968Z STM32 CRSF UART LISTEN TASK STARTED
2021-04-05T00:17:35.971Z CRSF UART Connected
2021-04-05T00:17:36.537Z UART STATS Bad:Good = 0:232
2021-04-05T00:17:37.537Z UART STATS Bad:Good = 0:200
2021-04-05T00:17:38.537Z UART STATS Bad:Good = 0:200
2021-04-05T00:17:40.537Z UART STATS Bad:Good = 0:200
2021-04-05T00:17:41.547Z UART STATS Bad:Good = 0:200
2021-04-05T00:17:42.537Z UART STATS Bad:Good = 0:200
```

Link is also good.

**Comment by cruwaller** [comment]
Merge conflict fixed and `targets/namimnorc_2400.ini` to extra_configs list

**Comment by StonedDawg** [comment]
hmmm ok, i'll try to rebuild and reflash again

**Comment by StonedDawg** [comment]
hey @cruwaller, I just re built and flashed again, its working! must've been a bad i did before...

**Comment by cruwaller** [comment]
Great! Thanks 👍

**Comment by jurgelenas** [comment]
@cruwaller I think you should also add your new target to [https://github.com/ExpressLRS/ExpressLRS/blob/47ec7b4347b02feda72ffe49f3be8cbad2ab5ffd/.github/workflows/build.yml](.github/workflows/build.yml).

**Comment by cruwaller** [comment]
> @cruwaller I think you should also add your new target to [https://github.com/ExpressLRS/ExpressLRS/blob/47ec7b4347b02feda72ffe49f3be8cbad2ab5ffd/.github/workflows/build.yml](.github/workflows/build.yml).

There is tasks ongoing with automatic builds so not included here...

**Pull request merged**
