### PR TITLE
Fix ER6GV target

### PR DESCRIPTION
**Pull request by pkendall64**
The cowboys reviewing the last PR 😅 

The ER6-GV is actually an ESP32 device!

### CODE REVIEW

**Review by JyeSmith — APPROVED** [review]

**Comment by CapnBry** [comment]
In the original sample I received, the power wouldn't go up to 100mW and Radiomaster said to just make it 50mW. I figured I would change this when the target was added, but someone else LEAKS'ed this hardware by adding the target prematurely. 😆

1. Do the latest samples support 100mW, or should that MaxPower change be added to this PR as well?
2. I also preferred the old "RadioMstr XXX" target names instead of "RM XXX". Any chance of going back to that and naming this the ER6GV instead of ER6-GV to make them all fit again? If this is what RM (lols I did it too) prefers that's fine.

**Comment by pkendall64** [comment]
> In the original sample I received, the power wouldn't go up to 100mW and Radiomaster said to just make it 50mW. I figured I would change this when the target was added, but someone else LEAKS'ed this hardware by adding the target prematurely. 😆
> 
> 1. Do the latest samples support 100mW, or should that MaxPower change be added to this PR as well?

We should limit it to 50mW as the new ones (V1.5) only go that high too.

> 2. I also preferred the old "RadioMstr XXX" target names instead of "RM XXX". Any chance of going back to that and naming this the ER6GV instead of ER6-GV to make them all fit again? If this is what RM (lols I did it too) prefers that's fine.

I think they were all changed to RM because of the Ranger Micro/Nano etc, and to keep them all consistent

**Comment by CapnBry** [comment]
Ah of course the Rangers triplets, forgot about those. The RM change makes sense then.

Do you want to do the 50mW change as well in this?

**Comment by pkendall64** [comment]
> Ah of course the Rangers triplets, forgot about those. The RM change makes sense then.
> 
> Do you want to do the 50mW change as well in this?

Done

**Review by CapnBry — APPROVED** [review]

**Pull request merged**
