### PR TITLE
Update BLE Joystick

### LINKED ISSUE #1563: BLE Joystick doesn't work under Android
## Current Behavior

I've tried using the BLE joystick on an Android device.  I find that I can connect it to my Android tablet, but I can't get it to appear as a joystick when testing with a sim.  I've noticed in the Dsicord group that a few people attempted to use it on Android, and also couldn't seems to get it to work using different sims and a bunch of gamepad testers.  In these cases of it failing on Android, it seems absolutely fine on Windows/Mac with the same radio.

## Steps to Reproduce

Put your radio/module into BLE joystick mode, pair it with your Android device - attempt to use a SIm - the Sim doesn't see any joystick connected.  I was using (and a few of my users) my own CurryKitten FPV Simulator, I saw another using Freerider.  Both these sims use Unity as their Game engine.  unity doesn't have any special support for bluetooth devices, it simply lists the available joysticks on the system.  If a bluetooth device has been paired as a joystick, then it should appear as a joystick in the sim.  

1.

2.

3.

4.

## Possible Solution (Not obligatory)

I don't know enough about the BlueTooth stack to suggest anything here, but given that the code appears to work fine on Windows/Mac - I assume there's something quite specific about Android that perhaps needs a more specific definition

## Your Environment

- TX hardware: RadioMaster Zorro
- RX hardware: N/A
- Handset model: RadioMaster Zorro
- OpenTX version (including nightly number) Edge TX 2.6.0
- ExpressLRS version (TX & RX MUST MATCH): 2.3
- Packet Rate: N/A
- Telemetry Ratio: N/A
- user_defines: N/A

### PR DESCRIPTION
**Pull request by Pmant**
This PR aims to fix #1563 and does further improvements to the BLE Joystick.

Android does not understand simulation controls like rudder or throttle.
To achieve a higher compatibility a **generic gamepad with 8 axis and 16 buttons** is used instead of simulation controls. 

**CRSF Channel mapping**:
- first 8 CRSF channels are mapped to axis 1-8 in this order: x, y, rx, ry, z, rz, slider1, slider2
- remaining 8 channels are mapped to buttons 1-8
- the user can modify the model's outputs to remap channels
- 3 way switches can be mapped to an axis to receive a meaningful output

The PR also removes the 100Hz update rate limit and instead uses the **Packet Rate** set by the user. 
I have tested this on a Windows PC with Packet Rate F1000 and did not drop packages. However it's up to the user to change the Packet Rate if it does not run well with less powerful receivers.

### CODE REVIEW

**Comment by nightflasher** [comment]
tested on my oneplus 7t with android 11 in currykitten sim and freerider recharged - working fine.
also tested on my ideapad 330 (ubuntu 22.04.1) with freerider (recharged) and also working fine.
good work!

**Comment by nightflasher** [comment]
While in Bluetooth joystick mode, the Lua script crashes. Maybe somebody could create a little joystick bitmap for the OLED screen?!
And change the Lua script to give hint, that this mode is running and the sx12xx chip is in deep sleep - joystick mode.

**Comment by pkendall64** [comment]
Tested on Mac with Tryp, Liftoff and FPV.SkyDive

**Review by pkendall64 — APPROVED** [review]

**Comment by nightflasher** [comment]
Which ExpressLRS version is this, when running now? Is it 3.2.0 or way earlier?

**Comment by pkendall64** [comment]
> Which ExpressLRS version is this, when running this branch now? Is it 3.2.0 or way earlier?

This PR is based off the current master branch, which has all the features of 3.2.0.

**Comment by nightflasher** [comment]
> Tested on Mac with Tryp, Liftoff and FPV.SkyDive. Lua script does not crash for me.

so i've to add my hardware: jumper t-lite (v1) will test with v2 later

**Comment by Pmant** [comment]
> so i've to add my hardware: jumper t-lite (v1) will test with v2 later

Personally I've tested it on the v2 without problems for ~30 minutes on all packet rates. Which packet rate were you using?

**Comment by mvaldesshc** [comment]
I tried using it in my Poco X3 Pro with Miui 13.0.3, and it didn't work in FPV.SkyDive and in freerider demo.

**Comment by nightflasher** [comment]
I tried sky.dive on iPhone - didn't work, but didn't work with any Bluetooth controller on any simulator on iPhone. On Android, fpv freerider (inkl recharged) and CurryKitten Simulator works fine.
Sky.dive didn't work, only with cable - I don't like it anyway.

**Comment by arthurson** [comment]
tx16s mk2 elrs, tried this and fails, no reaction on android and even pc, my elrs version become head ism2g4 a08732

**Comment by mvaldesshc** [comment]
> I tried sky.dive on iPhone - didn't work, but didn't work with any Bluetooth controller on any simulator on iPhone. On Android, fpv freerider (inkl recharged) and CurryKitten Simulator works fine.
> Sky.dive didn't work, only with cable - I don't like it anyway.
> 
> Tested again:
> sky.dive did work on my oneplus 7t (Android 11) —still don't like it anyway. 

Did you do anything on you phone for it to work?

**Comment by pkendall64** [comment]
> Did you do anything on you phone for it to work?

iPhone only allows accredited bluetooth HID devices to attach to them. So it will never work on an iPhone.

**Comment by nightflasher** [comment]
> Did you do anything on you phone for it to work?

No, just connected via Bluetooth and it works. Works on all modules and t-lite v2 with Ubuntu 22.04 (fpv freerider inkl recharged and steam), as well as all the sims on my android.
Sky.dive was a bit odd (arming via touchscreen) - but that's why I don't like it.

**Comment by Pmant** [comment]
At this point it is hard to tell whether the reported issues are caused by this implementation or the inability of the receiving device and software to work with any BLE gaming device. Can anyone confirm it not working whilst working with another BLE controller?

**Comment by arthurson** [comment]
for d113a5, tx16s mk2 elrs can now finally work on android 12, tried skydive and rds , no problem, and really thanks all of you.

**Review by JyeSmith — APPROVED** [review]

**Comment by FunkyKwak** [comment]
Hi,
I am very interested in this update, mainly for the Android support (#1563), thank you !
Do you know if this will be included in the next release ? And when ?

**Comment by Pmant** [comment]
> Hi, I am very interested in this update, mainly for the Android support (#1563), thank you ! Do you know if this will be included in the next release ? And when ?

This PR is merged already and will be released with version 3.3. You can test it now if you select the master branch as the firmware version in ExpressLRS Configurator.
grafik

**Comment by FunkyKwak** [comment]
> > Hi, I am very interested in this update, mainly for the Android support (#1563), thank you ! Do you know if this will be included in the next release ? And when ?
> 
> This PR is merged already and will be released with version 3.3. You can test it now if you select the master branch as the firmware version in ExpressLRS Configurator. !

Thank you for your answer, I will definitely give a try !

**Comment by Trevorlahey87** [comment]
My tx16s mk2 worked fine with ble joystick on velocidrone.  I updated to 3.3.0 now my windows 10 laptop recognizes and connects to the tx Bluetooth but in the sim nothing. Any known fixes for this?

**Pull request merged**
