### PR TITLE
Mavlink - disable tlm and switch options in Lua

### PR DESCRIPTION
**Pull request by JyeSmith**
Ideally it would be nice to display a lock icon🔒 next to these option in Lua.  Something indicating that the options are not available to the user while in Mavlink mode.

### CODE REVIEW

**Comment by JyeSmith** [comment]
Ive added OVR (override) to the labels which in inline with how ETX does this.  Im not sold if its any better than without OVR.

**Comment by wvarty** [comment]
I'm not loving this, mostly because `OVR` takes up 3 chars at the start, and isn't super clear to users what it means, without knowing what it means... the lock icon would be cool.

I'll flash is up and see how much I hate it,,,

**Comment by JyeSmith** [comment]
Based on the FB poll Ive reverted the OVR commit.

I think this PR is good to go while we figure out the best generic way to do  greyed out, or inverted text, for menu items with only a single entry.

https://www.facebook.com/share/p/jroHXKskBh9ann5o/

image

**Review by CapnBry — APPROVED** [review]
Changed elrsv3.lua to grey out any selection type item which only has a single item in the list (colorlcd only) and prevent going into edit mode / reloading the field if selected. Adds 30 bytes of code but I can't do any better :(

@Jye can you throw the lua on a handset and give it a try? I tried it on TX16S and a Boxer but just give it a quick sanity check that it greys and ungreys and nothing else goes wrong.

**Comment by JyeSmith** [comment]
All G.  LGTM!

**Review by pkendall64 — APPROVED** [review]

**Pull request merged**
