### PR TITLE
Semi-connected ModelMatch

### PR DESCRIPTION
**Pull request by CapnBry**
This changes the behavior of the TX-RX connection such that only 18 bits of the UID are used to establish a connection, but a full 24 bits must match to communicate with a Flight Controller. The purpose is to allow receivers/transmitters with different ModelMatch settings to still communicate to be able to change these settings.

## Details
The current ModelMatch system can only connect if the RX and TX have the exact same settings. That's pretty much the whole point of model match, right? The problem is that the ModelMatch config is stored on the receiver, and if the transmitter can't connect, how can it tell the receiver to change its config? The only way to disable an RX's modelmatch setting is to set the TX to modelmatch=ON and also have the Receiver ID set properly. If the user does not know the Receiver ID the used to enable the modelmatch, that means they'll have to try all 64 options until they stumble across the right one, then disable modelmatch on the TX.

To get around this, this PR will establish a connection using just the common part of the UID without the modelid added in. When a connection is established in this way, the receiver will not send any information to the flight controller. Not channels data, not MSP data, not connected link statistics (although the rate cycling is still passed). If the last 6 bits of the UID matches the expected modelmatch configuration, only then will the FC start receiving this data. To the flight controller this just looks like we're in failsafe the whole time.

The implementation follows this set of rules for handling half connections / full connections
| TX ModelMatch | TX Receiver ID | RX Model ID | Result |
|---|---|---|---|
| Off | Any | Off | Connects / Communicates as usual |
| Off | Any | A | Connects but does not communicate to FC |
| On | Any | Off | Connects but does not communicate to FC |
| On | A | A | Connects / Communicates as usual |
| On | B | A | Connects but does not communicate to FC |

I've also removed the reboot cycle the RX used to go through when changing the modelid. Now it simply forces a disconnect and goes back to listening for the new connection.

## Usage Steps
To enable modelmatch, connect a receiver and change the Model Match option in the Lua config to On. This sets the ModelId in the target RX to the "Receiver" id listed on the OpenTX Model Setup page. Multiple RXes can share the same ModelId. Alternatively, RXes with webui can set the ModelId from the web page. Note that the TX still needs to have modelmatch On to complete a full connection.

To disable modelmatch, establish at least a half-connection to the RX (the modelid / modelmatch setting does not need to match, which is the whole point of this PR). Set the Model Match option in the Lua config to Off. This clears the ModelId from the RX. Note that even with no ModelId in the RX, the TX must still have modelmatch Off to complete a full connection.

## Needed Improvements
It is very difficult to tell the difference when the modelmatch is not matching, because the transmitter gets linkstats telemetry, The connection LED on the RX goes solid, opentx shows a connection, but you can't arm, there's no advanced telemetry, and betaflight is showing a disconnected set of RF params. To try to alleviate some of the confusion, I'm planning to implement a new LED blink pattern to indicate a "model mismatch" situation. I want to make an asynchronous LED blinker class that will handle this as well as all the other LED blinking for disconnected / webupdate / bind / startup error, but this will come in a separate PR.

## Extra Fixes
* We'd do a syncspam even when the modelid isn't changing on startup (along with stopping TX on STM32 platforms). This changes it so we only do that if the modelid actually changes.
* Moved all the packet handlers out of `ProcessRfPacket()`. It was getting kinda busy in there.
* Moves GetRFLinkInfo() to after we send channels data to the FC. The function takes about 4us on STM32F103 and 3.8us on ESP8266, so not a lot of savings, but is an easy way to shave 4us off our latency for free.

### CODE REVIEW

**Comment by pkendall64** [comment]
Since this makes things a lot simpler for people to recover receivers where they have forgotten their model id, I think the part of the web UI for getting/changing the model id is virtually obsolete and I think we should either remove it or just change it be a read-only field. Also, the python script `set-model.py` is pretty much useless and should be removed.

**Comment by CapnBry** [comment]
> I think the part of the web UI for getting/changing the model id is virtually obsolete and I think we should either remove it or just change it be a read-only field. Also, the python script `set_model.py` is pretty much useless and should be removed.

I dunno, I can see that someone might want a way to unset the model id if they're having a problem with it, or don't want to toggle it on and off once to reset it. I don't think there's any problem with hanging onto it for a while unless it falls out of maintenance at some point and stops working. If you think it will get in the way more than it helps though, I have no problem removing it. Just seems a shame since you wrote it and it works still!

**Comment by pkendall64** [comment]
> I dunno, I can see that someone might want a way to unset the model id if they're having a problem with it, or don't want to toggle it on and off once to reset it. I don't think there's any problem with hanging onto it for a while unless it falls out of maintenance at some point and stops working. If you think it will get in the way more than it helps though, I have no problem removing it. Just seems a shame since you wrote it and it works still!

So what about the define to set the model id when building the RX firmware? Do you still think thats useful?

**Comment by CapnBry** [comment]
> So what about the define to set the model id when building the RX firmware? Do you still think thats useful?

😆 Iiiii did not even know that was possible. Now that bit of code makes sense! I thought it might have been left over from a previous implementation. I think we can probably remove that since I definitely broke that by removing it from the source code, but not the user_defines or options code. I think the number of people who would compile and flash an RX set to a single modelid and can only turn it on and off is pretty low and would create an inconsistent experience. What do you think?

**Comment by pkendall64** [comment]
Agreed, lets just remove that!

**Comment by CapnBry** [comment]
> Agreed, lets just remove that!

Done! Thanks for bringing your experience to this, I clearly did not look at anything apart from the little bit of source that is changed and didn't realize how much I had missed in all the external stuff.

**Review by pkendall64 — APPROVED** [review]

**Review by maybenikhil — APPROVED** [review]

**Pull request merged**
