### PR TITLE
Rotate the sync slot through all the FHSS slots

### PR DESCRIPTION
**Pull request by CapnBry**
This changes the sync packet behavior so that it can fall on any slot in the FHSS sync channel, not just on slot 1 or 2

### Details
Our current sync implementation will only send a sync packet on slot 1 or 2 of the FHSS and not on 0 or 3 at all. In practice the sync almost exclusively falls on slot 1 (being the first available slot after the timeout). The combination of the two means that if the receiver Nonce is off, it can miss the sync packet every time it is sent and never get back in sync.

In an ideal case this PR will send sync on slot 0, 0, 1, 1, 2, 2, 3, 3, repeat if connected. If the sync interval is short enough to fit two packets in the same cycle (such as Team2.4 disconnected interval), it will go 0, 2, 1, 3, repeat. If telemetry happens on the slot where the sync was supposed to occur, the sync will take place on the slot following the telemetry.

Note that due to telemetry falling on slot 0 most frequently, slot 0 sync is still underrepresented. There is no way to equally distribute the sync through all 4 slots without adjusting the telemetry math to move the telemetry to odd slots, but I think this is unnecessary and would add a lot of complexity that could actually create issues where the RX and TX have their telemetry parity flopped and create issues this PR is designed to reduce.

### Sync Spam
Sync spam, the sync packets sent on non-sync FHSS channels when changing rates or ratios, is unaffected by this PR-- they stay forced in slot 1 and 2. This is done to avoid any complexity of switching rates while also FHSS hopping and preserves the stability we've established using that mechanism. I did reduce the sync spam after rate change from 1500ms to 500ms as there is no chance the remote side would take anywhere near that long to switch rates and it frees up bandwidth for real data more quickly.

### A world without SYNC
~~This PR also uses some of what Jye discussed in #816, where we do not send sync packets at all if the connection is "healthy". Healthy is defined as:~~
* ~~Telemetry is on and being received. I'm using the connected state instead of "telemetry within the last 5s" since we will drop to disconnected before 5s using the dynamic disconnect threshold so this will react more quickly.~~
* ~~The current telemetry ratio matches the configured ratio. This is to allow the ratio to return to normal after MSP, where the ratio has been temporarily boosted.~~
* ~~The RX reported LQ is >75. The RX has to be in sync to get an LQ over 75 (receiving data on all 4 slots). This really should be dynamic based on FHSS slot count, but we need to save some bytes so 75 works for 4 or fewer packets per hop.
Note that I did not remove NO_SYNC_ON_ARM since I believe users still desire forced NO_SYNC, but this will eliminate sync packets for users with telemetry enabled with an high LQ.~~
Removed due to possible bad interaction with the telemetry boost. We'll revisit this later.

### Make room!
The net flash usage for this PR is around -30 bytes (it frees up about 30 bytes). To achieve this, I've made some tangentially related changes.
* Removed the LPF on the TX's LQ. I don't think anyone gives a hoot that the `TQly` telemetry item in OpenTX is damped. The value reported was also sometimes 101%. Now it just shows the actual downlink LQ (telemetry packets received LQ). If we want a smoother value, we can just up the samples on the LQ itself, which only takes more RAM, no code. Currently we use 10 samples, but even 100 samples is only 11 more bytes of RAM. I'd recommend 32 as a starting point if we're going to increase this, which is only 2 more bytes of RAM compared to 10.
* connectionState_e 's enum has had the unused members removed and is reordered so "connected" is 0 which generates less code. That happens because it is the value we check the most and 0 means there's no immediate needed for the comparison.
* I spent about 5 hours trying different code to generate the sync slot sequence along with a few different methods and the code that's here is as tight a I can get it. Don't think this code was just the first try!

### CODE REVIEW

**Comment by CapnBry** [comment]
I've fixed the issue with getting stuck with boosted telemetry at high LQ (which was skipping the sync). The simple solution was just that we can't skip sync if our telemetry ratio isn't right! One comparison added and looks to be working on my bench. Ready for further testing!

**Comment by JyeSmith** [comment]
How many times is sync sent with the correct tlm ratio after after switching back?  From what I see its only once?  and if that is missed then it will still be stuck on 1:2.  Should syncSpamCounter be used after switching back?

**Comment by CapnBry** [comment]
> How many times is sync sent with the correct tlm ratio after after switching back? From what I see its only once? and if that is missed then it will still be stuck on 1:2. Should syncSpamCounter be used after switching back?

You raise a very valid point. With setting it **to** 1:2 we only send 1 packet but it is OK if it is missed because MSP will kick it back on again if there's no reply, or an ongoing conversation. With switching **from** 1:2 we'd only get one shot at it and if the telem doesn't change on the RX it still will have high LQ. The problem with setting the syncSpam counter is what to trigger that. The TX end doesn't know when the MSP response has finished being received so it has to rely on some timeout. I really don't want to add a handful of code that sets a timer when it sees an MSP transfer then sets a syncspam to occur X seconds later.
```
static bool mspActiveLast;
static uint32_t mspTlmBoostStart;
if (mspActiveLast == false && MspSender.IsActive())
{
  mspActiveLast = true;
  mspTlmBoostStart = millis();
  syncSpamCounter = 1;
}
else if (mspActiveLast == true && !MsgPsender.IsActive() && (millis() - mspTlmBoostStart  > BOOST_DURATION))
{
  mspActiveLast = false;
  syncSpamCounter = syncSpamAmount;
}
```

I think it might just be better to remove the skip sync for LQ>75 altogether instead of bending over backward to try to insure link consistency to save one packet out of every 5 seconds. That means a sync packet every 5 seconds which will eventually switch the RX back to the right interval regardless. The problem with even all that code above, is that it still is almost a one time attempt to switch the RX to the right interval and if it doesn't get it for some reason, it will be stuck at 1:2 forever and there's no way for the user to know they're experiencing degraded performance.

**Comment by JBKingdon** [comment]
"I think it might just be better to remove the skip sync for LQ>75 altogether instead of bending over backward to try to insure link consistency to save one packet out of every 5 seconds. That means a sync packet every 5 seconds which will eventually switch the RX back to the right interval regardless."

This sounds like a good compromise to me. A very occasional sync packet seems like a small price to pay for the simplicity and robustness it provides.

**Comment by JyeSmith** [comment]
Yep, lets remove it for now.

**Comment by CapnBry** [comment]
Removed skipSync for now. We can revisit Syncless World at a later date.

**Review by JyeSmith — APPROVED** [review]

**Pull request merged**
