### PR TITLE
Use sans-serif fonts for OLED

### PR DESCRIPTION
**Pull request by pkendall64**
- Easier to read fonts (serif fonts on OLED are really hard to read)
- Fix cut off wifi image
- Adjust placement of test on status screen

### CODE REVIEW

**Comment by SunjunKim** [comment]
FYI comparison between serif vs. sans-serif:
serif_vs_san_serif

I vote for the san-serif font.

**Comment by NiklasVoigt** [comment]
can you try myriad pro?
look at the styleguide: https://github.com/ExpressLRS/ExpressLRS-Hardware/blob/master/img/logo/ExpressLRS-Styleguide.pdf

**Comment by jurgelenas** [comment]
> can you try myriad pro?
> look at the styleguide: https://github.com/ExpressLRS/ExpressLRS-Hardware/blob/master/img/logo/ExpressLRS-Styleguide.pdf

Not compatible due to the licensing issues with Adobe.

**Comment by jurgelenas** [comment]
> FYI comparison between serif vs. sans-serif: serif_vs_san_serif
> 
> I vote for the san-serif font.

Is it intentional or “HZ” both letters should not be in uppercase?

In real life “ExpressLRS” top part is cut off as well or this is just a camera angle?

**Comment by SunjunKim** [comment]
> Is it intentional or “HZ” both letters should not be in uppercase?
It should be Hz. must be a typo.

> In real life “ExpressLRS” top part is cut off as well or this is just a camera angle?
It's the camera angle. It's showing clearly without a cut.

**Comment by SunjunKim** [comment]
Found an issue on this commit:
-> TX power is not updated correctly.
Other values (tlm ratio, link speed) are fine.

**Comment by SunjunKim** [comment]
> Found an issue on this commit:
> -> TX power is not updated correctly.
> Other values (tlm ratio, link speed) are fine.

It turns out to be it's a bug in the current master. Not related to this PR.

**Comment by SunjunKim** [comment]
> It turns out to be it's a bug in the current master. Not related to this PR.

This bug is now fixed on PR #1222

**Review by brandonrc — APPROVED** [review]
I like the new font!

Wish I had my ghost tx lite working.. I need to order another one so I can try and fix the 128x32 screen stuff.. no way to test that :( 

Think for now we can approve this and have it merged and I will open up a new PR for the small OLED once I order a new ghost tx lite :( ... the things I do for ELRS users :)

**Comment by brandonrc** [comment]
@jurgelenas you are a UI guy. Do you like the new fonts? Do you have a module with OLED to test this and get your feed back.

**Comment by jurgelenas** [comment]
> @jurgelenas you are a UI guy. Do you like the new fonts? Do you have a module with OLED to test this and get your feed back.

I have no TX module with an OLED screen, but I like this change :) Sans-serif fonts on low resolution screens looks much better

**Review by jurgelenas — APPROVED** [review]

**Pull request merged**
