### PR TITLE
WiFi Web Server refactor/consolidation

### PR DESCRIPTION
**Pull request by pkendall64**
Refactor the wifi/web code to a single common source file for both RX and TX using "ESP Async WebServer".

- Moves all the code related to figuring out when to start wifi mode into the wifi code.
  Simplifies the RX/TX main code flow to only needing to call a single function to handle wifi/web update.
- As part of this the RX LED code was also moved into a single function, similar to the TX
- Library dependencies have been locked to known-good versions, so we don't get unexpected breakage
- As we were close to the edge (in terms of flash space) the ESP8266 is now linked against `eagle.flash.1m.ld` which removes the unused SPIFFS partition (which was 256KB). Similarly, for the ESP32, specify `min_spiffs.csv` which shrinks SPIFFS from 1MB to 192KB giving us more room for the application.

### CODE REVIEW

**Comment by pkendall64** [comment]
> This is all good stuff and I am looking at it, I've kinda squandered my time though so I haven't had a chance to fully review yet. I will this week for sure.

No problems

**Comment by CapnBry** [comment]
Ok! Sorry again about the delay on this, I just have some minor stuff and some of it isn't even stuff you've changed:

* SSID not consistent across type: `ExpressLRS TX Module` vs `ExpressLRS RX`. I think just drop module from TX
* wifiOff() is there no ESP32 code to turn wifi off? Do we not want to force that off in the same manner as the RX does?
*  EnterBindingMode (RX) should not have a `hwTimer.resume();` in it. The timer is only started on reception of packet. ...but do we even need to handle going to EnterBindingMode from wifi mode? How would the user get into this state from wifi mode? I think this should just be removed and we won't support binding while in RX mode just to reduce the complexity and the fact that this code would then need to be kept in sync and working with how setup() sets things up.
* `extern` on functions in WebUpdate.h. All functions have external linkage by default and our convention is to not explicitly decorate them with extern, just drop it.
* `changeTime+30000` and `changeTime+500` in WebUpdate.cpp. Can we get these flipped around to `now - changetime` to prevent overflow and follow convention?
* Compile fails if `AUTO_WIFI_ON_INTERVAL` not defined so that needs to be wrapped in ifdef. I'm fairly certain we can also drop the 60000 case too since I don't know if anyone can give you a good reason why that is still in there. If someone wants to get to wifi mode just leave binding mode, right?!
* The webui shows `undefined` for the Model Match ID. The JSON handler is just missing the bit that adds it for RXes `+= "\",\"modelid\":" + String(config.GetModelId());`. Also can the ssid be made common instead of being in both AP and STA's json?
* DBGLN("Setting model match id %d", (uint8_t)modelid); signedness mismatch
* `WebUpdateModelId` has `if (modelid < 0 || modelid > 63) modelid = 0;`, should be 255. This was my bad for missing this.
* `Fix wifi starting causing save to happen in main loop` causes a config.commit() every time wifi is started. I think there's got to be a better solution for this than committing it every time?

Last one just question, why the esphome version of ESPAsyncWeb? Is it more modular and doesn't contain RegEx by default or something? Just curious why this fork was chosen.

**Comment by pkendall64** [comment]
> * Compile fails if `AUTO_WIFI_ON_INTERVAL` not defined so that needs to be wrapped in ifdef. I'm fairly certain we can also drop the 60000 case too since I don't know if anyone can give you a good reason why that is still in there. If someone wants to get to wifi mode just leave binding mode, right?!

I think that this is for the case where someone is using traditional binding and hasn't bound, but want to update via wifi.
I assume this was for the case where some manufacturers would send out with firmware in this mode.

> * `Fix wifi starting causing save to happen in main loop` causes a config.commit() every time wifi is started. I think there's got to be a better solution for this than committing it every time?

No, this is only setting the SSID/Password to the compile-time defaults if the flash has not been previously configured and there is a compile-time default value set.

> Last one just question, why the esphome version of ESPAsyncWeb? Is it more modular and doesn't contain RegEx by default or something? Just curious why this fork was chosen.

Yes, this is the version that has updates and has regex off by default.

All other issues have been fixed. Nice review, thanks.

**Review by CapnBry — APPROVED** [review]
Looks flippin' great man, sorry again about the slow review.

And 100% you are right about the config commit /facepalm, I totally misread the `if` statement and thought it was only looking at the compiled-in ssid/password, not the config'd ssid.

**Review by JyeSmith — APPROVED** [review]

**Pull request merged**
