### PR TITLE
Current Leaderboard

### PR DESCRIPTION
**Pull request by ariefadha**
| 11Km | 900M | 50HZ | 100mW | No | Taufik |https://youtu.be/ySBvXENS33s

### CODE REVIEW

**Comment by CapnBry** [comment]
We have 40km on 900MHz / 50Hz at 10mW, so I don't know if 1/4 the distance on 10x the power is noteworthy.

**Comment by jurgelenas** [comment]
> We have 40km on 900MHz / 50Hz at 10mW, so I don't know if 1/4 the distance on 10x the power is noteworthy.
> 
> Also, we're removing the Range Competition from the README I believe.

@maybenikhil range competition will go to the website right?

**Comment by maybenikhil** [comment]
Range competition wil indeed go onto the website now:
See https://www.expresslrs.org/2.0/info/long-range/

Although I don't disagree with capn bry's comment I also think it's fine as long this beats the previous record at that power le

**Comment by maybenikhil** [comment]
https://github.com/ExpressLRS/Docs/commit/929ea1dba4362ba3a4e1cb37bd9d79e88a0ff4a7 done

**Pull request closed without merging**
