### PR TITLE
Merge 3.x.x-maintenance to master 

### PR DESCRIPTION
**Pull request by JyeSmith**
**DO NOT SQUASH MERGE**

Please check I didn't stuff this up!  

There was only a minor conflict with CTRL pins in hardware.html, otherwise everything looked good.

### CODE REVIEW

**Review by pkendall64 — APPROVED** [review]
Compare exactly the same as the one I was doing 👍

**Comment by CapnBry** [comment]
Stupid CTRL pins, shoulda maybe brought that over to 3.0. It looks OK to me, but I dunno how to verify that it has it all.

**Review by CapnBry — APPROVED** [review]

**Comment by pkendall64** [comment]
> Stupid CTRL pins, shoulda maybe brought that over to 3.0. It looks OK to me, but I dunno how to verify that it has it all.

The changes were over on 3.0, they changes merged them to master 😆

**Comment by CapnBry** [comment]
😂 Well we've did it, everyone. We successfully created a time loop.

**Pull request merged**
