### PR TITLE
Super defines

### PR DESCRIPTION
**Pull request by CapnBry**
This is a different take on #491 and instead of selecting one file, it always processes user_defines.txt and then processes super_defines.txt which can modify the build flags by adding or removing them.

I believe the ability to remove defines was present but I don't think it worked when processing *_defines.txt since the lines would be removed by parse_flags. The method for removing a define is to start it with a bang, `!-D=FAST_SYNC` will remove FAST_SYNC from the build flags. It just has to match everything after the bang.

Merging this would most likely create a conflict in #483 and vice versa, but I'm smart enough to be able to fix the conflict in whichever PR is merged second. EDIT: 483 was merged so I have fixed the conflict!

### CODE REVIEW

**Comment by pkendall64** [comment]
I added the ! processing in the PR for doing the target builds in gitlab. The expectation at the time was that they would be passed in the PLATFORMIO_BUILD_FLAGS which actually made it through to build_flags in the python script.

**Review by cruwaller — APPROVED** [review]
I think it would still be better to just override defined values when same define is found from `super_defines.txt`.
Very easy too miss removal...

**Comment by CapnBry** [comment]
> I added the ! processing in the PR for doing the target builds in gitlab. The expectation at the time was that they would be passed in the PLATFORMIO_BUILD_FLAGS which actually made it through to build_flags in the python script.

Yup, my bad. I was wondering why it seemed to try to be splitting one line into multiple defines. I will fix this in just a few minutes

**Comment by pkendall64** [comment]
> > I added the ! processing in the PR for doing the target builds in gitlab. The expectation at the time was that they would be passed in the PLATFORMIO_BUILD_FLAGS which actually made it through to build_flags in the python script.
> 
> Yup, my bad. I was wondering why it seemed to try to be splitting one line into multiple defines. I will fix this in just a few minutes

Yeah platformio is a bit silly. When you pass the PLATFORMIO_BUILD_FLAGS environment variable it sends that as a single argument to build_flags in the script. That's why I have to parse it out. I'd consider that a pio bug, I suppose. But we have to work around it.

**Review by SpencerGraffunder — APPROVED** [review]

**Pull request merged**
