### PR TITLE
graphical stuff

### PR DESCRIPTION
**Pull request by NiklasVoigt**

### CODE REVIEW

**Comment by JyeSmith** [comment]
@NiklasVoigt make sure PRs are against develop 👍

**Comment by AlessandroAU** [comment]
Is it just me or does the resolution of the sens/pkt rate graph look alittle low? https://raw.githubusercontent.com/AlessandroAU/ExpressLRS/7c84fe6741f3a09eef7a285d699a93e33cbc0e62/img/pktrate_vs_sens.png

**Comment by NiklasVoigt** [comment]
@AlessandroAU  I've used the low quality pic from the Readme... maybe you can send me a high resolution picture or the google docs file in the discord

**Comment by NiklasVoigt** [comment]
@AlessandroAU This PR is ready! Are you sure you want it to end up in the develop branch?

**Comment by AlessandroAU** [comment]
We will merge to dev, and then into all into master for 1.0RC1 looks good and thank you.

**Pull request merged**
