### PR TITLE
adds MEGA bauds

### PR DESCRIPTION
**Pull request by JyeSmith**
Adds higher baud rates and reduces the cycle time.

Goes with https://github.com/EdgeTX/edgetx/pull/640

### CODE REVIEW

**Comment by CapnBry** [comment]
Excellent! Let's. Get. Megabaud.

* I'd remove the `TxToHandsetBauds` from crsf_protocol.h and put it in CRSF.cpp since that doesn't need to be added to every module that includes crsf_protocol.h, it is internal to the CRSF class implementation. 
* CRSF::UARTcurrentBaud isn't needed and should be moved to be local to the UartWdt function. Outside there it can just use CRSF::TxToHandsetBauds[0], **or** it might be better to remove all the redundant code and just have init/ESP32uartTask call UartWdt to have it do the Port.begin() even for the first time?
* CRSF::UARTcurrentBaudCounter -> CRSF::UARTcurrentBaudIdx, it is the index into the bauds array. Update it with `UARTcurrentBaudIdx = (UARTcurrentBaudIdx + 1) % ARRAY_SIZE(TxToHandsetBauds)`, otherwise anything that wants to know the baud will have do do the mod and it just makes sense to keep UARTcurrentBaudIdx in bounds at all times.
* Instead of the weird thing of adjusting the UARTwdtLastChecked to in effect shorten the timer, would it be better to have faster cycling all the time? 200ms cycling is probably enough even for 25Hz to be able to tell if we're at the right baud and would get us to MegaBaud rates faster.

**Comment by maybenikhil** [comment]
3.75M is not working on my platform - RMTX16s (pkendall's branch) and Namimno Flash TX

**Comment by JyeSmith** [comment]
@CapnBry  I'll make those changes. Except UARTwdtLastChecked as keeping it at 1s is for the bad:good ratio display.

@maybenikhil NamimnoRC and the F103 only goes to 1.87M.

**Comment by JyeSmith** [comment]
@CapnBry changes pushed.

Ill leave init/ESP32uartTask calling UartWdt to you if you really want it.

**Review by StonedDawg — APPROVED** [review]
tested and work perfect beside 921k baud

**Pull request merged**
