### PR TITLE
LED Indication for other modes

### PR DESCRIPTION
**Pull request by pkendall64**
With the nice LED framework in place. This PR adds indication for...
| Mode | Indication |
| --- | --- |
| Web Update | Green heartbeat |
| BLE Joystick | Blue heartbeat |
| Radio Failed | Red flashing 100ms on/off |
| No Handset Connection | One Red flash every second | 

This is in addition to the usual startup color-wheel crossfade and Rate/Connected color pulsing modes.

As part of this I have removed the boolean variables for BLE Mode and WiFi mode and merged them into the connection status enum. Ultimately I'd like to move the IsBinding into the connection status enum as well.

### CODE REVIEW

**Comment by CapnBry** [comment]
Aww yeah, I can finally tell when I'm in one of these modes! The code to move everything to connection state looks good. I think this is a lot nicer than having individual variables and is consistent across the RX and TX.

What do you think about moving `disableWebServer` (RX) and `CRSF::hasEverConnected` (TX) into XXX_WebUpdate? Both of these fields are used for the same thing, to prevent the webserver from starting if something has connected, so it would be cleaner if both used the same variable to do the same purpose.

### Visibility
I can't really tell the difference between a connection (red, green, or blue) and the subtle hue shift of red to slightly less red, green to slightly less green, and blue to slightly less blue (although this last one I can sort of see better than the others). It might be because the ES900TX LED is small and the only way you can see it is reflecting through the case, although mine doesn't even have the cover on it and it is difficult to distinguish.

The monochrome LED patterns we put out are **very** distinctive and this is very subtle. Lightness changes are used by the "breathing" and power output so I think those are out. Playing with a color picker I have a hard time finding 3 distinct hues to cycle between to represent the mode. At +/-20 hue for the cycling I can easily see the BLE mode but not the Wifi mode.

Can we just do like a short blink [COLOR] (200ms) + delay (800ms) or something along those lines? Or maybe blink one color then another color with a delay between? Or COLOR from 0 to 255 intensity and wrap instead of reverse? I'd like the LED to convey information about being in these modes and not just provide ambience.

**Comment by pkendall64** [comment]
Yeah, I was thinking the same thing last night, that it was quite hard to tell the difference. So I will adjust the way the indication works for the status indication.

The disable flags I'll also move, I completely forgot about them. Sorry.

**Comment by JyeSmith** [comment]
Another vote for blink codes that can be associated with any failures/errors.  Say a string of 5 dots/dashes and we can add their meaning to the website.

Another error state that can be immediately added is for sport connection not detected.  Even another for bad:good ratio issues?

**Comment by CapnBry** [comment]
> Another vote for blink codes that can be associated with any failures/errors. Say a string of 5 dots/dashes and we can add their meaning to the website.

I've got a PR coming for a async LED sequencer for standard LEDs but I haven't had time to finish it with all the other stuff going on. It takes an array of durations to cycle through where each 2 elements are on time / off time (in 10s of milliseconds). Like
```
constexpr uint8_t LEDSEQ_WEBUPDATE[] = {  3, 3 }; // 30ms on, 30ms off (turbo blink)
constexpr uint8_t LEDSEQ_ERROR[] = {  10, 10 }; // 100ms on, 100ms off (fast blink)
constexpr uint8_t LEDSEQ_MODELMATCH[] = {  10, 10, 10, 80 }; // 100ms on, 100ms off, 100ms on, 800ms off (two short blinks and a pause)
g_LedRed.startSequence(LEDSEQ_WEBUPDATE, sizeof(LEDSEQ_WEBUPDATE));
```
Perhaps the same LEDSEQ arrays can be used to be consistent across color/regular LEDs?

**Comment by pkendall64** [comment]
> > Another vote for blink codes that can be associated with any failures/errors. Say a string of 5 dots/dashes and we can add their meaning to the website.
> 
> I've got a PR coming for a async LED sequencer for standard LEDs but I haven't had time to finish it with all the other stuff going on. It takes an array of durations to cycle through where each 2 elements are on time / off time (in 10s of milliseconds). Like
> 
> ```
> constexpr uint8_t LEDSEQ_WEBUPDATE[] = {  3, 3 }; // 30ms on, 30ms off (turbo blink)
> constexpr uint8_t LEDSEQ_ERROR[] = {  10, 10 }; // 100ms on, 100ms off (fast blink)
> constexpr uint8_t LEDSEQ_MODELMATCH[] = {  10, 10, 10, 80 }; // 100ms on, 100ms off, 100ms on, 800ms off (two short blinks and a pause)
> g_LedRed.startSequence(LEDSEQ_WEBUPDATE, sizeof(LEDSEQ_WEBUPDATE));
> ```
> 
> Perhaps the same LEDSEQ arrays can be used to be consistent across color/regular LEDs?

While I agree with this for the error cases, I don't think high speed flashing for WiFi mode looks very nice on the TX! I just tried it and it's very jarring, although wifi mode isn't used that often so it probably doesn't matter that much. On the other hand, BLE mode will be used a lot and having a flashing LED might be a bit off-putting.

**Comment by pkendall64** [comment]
I've removed `CRSF::hasEverConnected` but added a flag into the TX code for that. I don't think we should have a flag in the web server for this because we can manually start it from the LUA. So not automatically starting it is really a concern of the TX code.

**Comment by CapnBry** [comment]
That makes sense about the strobing led being too much. I still think we need something more district for the wifi and blue modes though, so I guess we'll have to figure something else out

**Comment by pkendall64** [comment]
> That makes sense about the strobing led being too much. I still think we need something more district for the wifi and blue modes though, so I guess we'll have to figure something else out

I've made them a little bit better with a heartbeat style to show they are doing something different. Hopefully that helps disambiguate things.

**Comment by CapnBry** [comment]
Oh yeah these new flash modes are great. I can definitely tell the difference now between the new modes and regular RF connection mode. Excellent!

The removal of hasEverConnected and just moving it to tx_main doesn't make any sense to me though. If there is going to be a variable that remembers if something has ever connected, it should be in the CRSF class, not a global variable. However, I was suggesting consolidating it with `disableWebServer` though, both of which are for preventing **autostart** of the web server. The variable can be named like `webserverPreventAutoStart` or something like that and not just disableWebServer (which as you say implies it would block any web startup). The WebUpdate_XXX code doesn't need to check it, I just want variables to live with the code they're associated with, and have both the RX and TX code reference same variable name instead of two things that do the same thing with different names living in "main".

On my ES900TX, the module stays in noCrossfire mode all the time though. There is nothing that sets it to a state `< MODE_STATES` so updateconnectdisconnect is never called until after the first connection. Are you missing a `connectionState = disconnected` in `UARTconnected`?

Lastly, this comparison needs to be `>=` so in the future if there are any LEDSEQ which have more than another, the counter will reset if was in a higher state that the new LEDSEQ supports (e.g. the previous LEDSEQ had 4 states and counter was 3, and you pass it a LEDSEQ with only 2 states).
https://github.com/ExpressLRS/ExpressLRS/pull/906/files#diff-0bc91b9837c44d634a19e0e74896f107b6dd5ee5fc80824ca87d261bfbaa9e6fR202

**Review by CapnBry — APPROVED** [review]

**Comment by CapnBry** [comment]
Love it. Love all of it!

**Review by AlessandroAU — APPROVED** [review]

**Pull request merged**
