### PR TITLE
Rename fullres 9ch/13ch switch modes

### PR DESCRIPTION
**Pull request by CapnBry**
Changes the display of fullres switch modes to accurately reflect how many channels there are:
* 8ch => 8ch + arm = `8+1ch`
* 12ch => 12ch + arm = `12+1`

Some confusion has been expressed to me about how many channels there are in each mode and how CH5 is "wasted" in 8/12ch modes, leaving you with one fewer channel. In actuality, there are 8/12 full resolution channels + 1 arm channel so labeling them properly may help to dispel the misconception that the channel is lost?

### CODE REVIEW

**Comment by pkendall64** [comment]
I'm ok with this, but if people are "confused" by the current naming I'm sure they will also be with the new names!
Perhaps "8+1ch" and "12+1 Mixed" might be better. Just an idea.

**Comment by CapnBry** [comment]
> I'm ok with this, but if people are "confused" by the current naming I'm sure they will also be with the new names! Perhaps "8+1ch" and "12+1 Mixed" might be better. Just an idea.

That's the naming I considered when I added it for 3.0, but the problem then was that "12+1ch Mixed" didn't fit on the screen so I gave it all amiss. The idea never occurred to me to drop the `ch` since the first two options have the ch part. Deadbyte, prepare for the support question "What does the 12+1 mean on the option that follows 8+1ch and 16ch? 12 whats!" 🤣

**Review by pkendall64 — APPROVED** [review]

**Comment by JyeSmith** [comment]
Its confusing now, and this will be as equally confusion.

Leaving at unchanged at least means the current knowledge base exists, instead of every relearning WTH the +1 means.

**Comment by CapnBry** [comment]
> Its confusing now, and this will be as equally confusion.

It's not great, but what other options do we have? The issue this PR attempts to help with is _discovery_. People see it says "8ch" so they only set up their mixer to go to CH8, because why would they think that 8ch actually means 9ch? Those who actually **try** it will see that they got 9 channels, but doing that involves possibly getting into the RX to map the channel too, so there's a lot of up-front cost to experimenting that deter that.

If the option itself somehow indicated that there are 9 channels, then everyone knows they get 9 so there are fewer complaints about CH5. I've had 3 people in the past month or two complain that 8ch mode is only 7ch because they don't try it. Maybe `8+1` is confusing. Maybe `9ch` is confusing. `8ch` is just not correct though, so I am open to any other option that fits on the screen and still lets users know they have Xchannels + 1 arm.

**Comment by froqstar** [comment]
8.1? 
Weird surround sound setup but okay.

**Comment by NameOfTheDragon** [comment]
As a lowly end user, here is what I think, FWIW

Just state the total number of channels.

Everyone knows (or should know) that Ch 5 is for arming and is 1-bit. This has been documented to death in every set of release notes and it is very evident when setting things up. So I (as an end user) would be happy to just see the total number of channels and would mentally compensate for Ch.5

**Comment by CapnBry** [comment]
@JyeSmith do you think about `8ch+A` and `12+A Mixed`? I'm struggling to come up with clearer alternatives :/

**Comment by froqstar** [comment]
I guess there is not enough space for "12+Arm Mixed"?

**Comment by CapnBry** [comment]
> I guess there is not enough space for "12+Arm Mixed"?

Nope, It comes out `12+Arm Mix` which I think is even more confusing than `Mixed` (it being already confusing what that means but I feel it is important information as well). Folks will likely lock on to "Arm Mix" and not that the 12ch are of Mixed (Half and Full) update rate.

Maybe this?
```
8ch+Arm
16ch Rate/2 (cut off slightly)
12+A Mixed (just fits)
```

The problem with all of these using "Arm" as the extra info is that these are the same users who think "I'm fixed wing, I don't care about arm" and will ignore the word entirely. Eventually we'd like to remove the concept of Armed entirely, but CH5 will always be 2-position in 9ch/13ch modes either way. The whole situation is just a bit of a mess and I'm a little worried that labeling it something with Arm might trigger the wrong part of users' brains and lead to further confusion.

**Comment by robustini** [comment]
In fact now that I read I learnt that it is 8+1 and 12+1, I always thought it was only 8 or 12.
Better to specify it.

**Comment by robustini** [comment]
But on the wiki in the column of 12CH+1 I do not see CH13 usable, if they are 12+1 channel 13 should be, or am I wrong?

immagine

**Comment by CapnBry** [comment]
Closing on the basis that we have no consensus on which is less confusing.

**Comment by sensei-hacker** [comment]
Re the current existing knowledge -
ELRS experts like Jye and CapNBry have that knowledge, and it may seem "well known" of you're an active ELRS dev. If you're not one of the dozen people who are experts, not so much.

I just had a user confused about that.
I've spent a number of hours in the ELRS code and read all the docs, but I didn't remember it. I had read it, but no reason to remember it if you don't need that info at the moment.

I suspect the vast majority of people who will use ELRS don't already know that eight is actually nine.

**Pull request closed without merging**
