### PR TITLE
Add guard around DEVICE_NAME for common headers

### PR DESCRIPTION
**Pull request by pkendall64**
Add `DEVICE_NAME` to mDNS options string so configurator can use this to match alias for a target.
Also, adds other missing options to mDNS options string.

### CODE REVIEW

**Review by CapnBry — APPROVED** [review]

**Review by schugabe — APPROVED** [review]

**Comment by justinlampley** [comment]
I am encountering an error when trying to build DIY_2400_TX_ESP32_SX1280_E28 with the user define  -DDEVICE_NAME="Test_Name"

image

DEVICE_NAME on the mDNS record has 2 sets of double quotes surrounding it

image


What do you think about device name being its own TXT entry on the mDNS record, like version and target?

**Comment by CapnBry** [comment]
I added guards for the BetaFPV RX/TX because those are used by JHEMCU / HiYounger according to #1139.

However, these RXes cloned the BetaFPV layout and didn't include all the parts, so they're missing (among other things) the inductor for the DCDC converter on the SX1280. I believe they should still work, at least they do when I tried it with an EP2 that doesn't have the inductor, but I am not sure how safe it is to enable the DCDC if it isn't connected. Does this make my desire for target aliases a pipe dream?

**Comment by pkendall64** [comment]
I added guards around the rest of the targets DEVICE_NAME defines.
Extracted the exposed the DEVICE_NAME as a seperate mDNS attribute so @justinlampley will not have to try to parse it out of the options attribute.

**Review by schugabe — APPROVED** [review]

**Review by CapnBry — APPROVED** [review]
Now everyone can even make their own device names for any device! I'mma name all mine SIXTEEN characters long. I like that you moved device_name to the options like the other strings. Typical, pkendall64-grade excellent work.

**Pull request merged**
