### PR TITLE
Fix typo in RX web ui ("connection" vs "conenction")

### PR DESCRIPTION
**Pull request by gchedzhemov**
A very small and humble PR to fix a typo ("connection" vs "conenction") in RX web ui and lua comments

### CODE REVIEW

**Comment by SunjunKim** [comment]
Some of the typo is already fixed in pr #1786, but the typo in `src/lib/LUA/rx_devLUA.cpp` is new! 

We're now applying all the changes into `3.x.x-maintenance`, so.. Could you change the base branch to `3.x.x-maintenance`?

**Comment by gchedzhemov** [comment]
Changed base branch to `3.x.x-maintenance`, as requested. Thanks, Sunjun

**Comment by pkendall64** [comment]
You can't just change the base branch. You will have to rebase your changes on the 3.x branch, force push your branch then it would be ok, by just changing it in github it's trying to merge a lot of extra changes from master, which we will not be doing.

**Comment by gchedzhemov** [comment]
Gotcha, PK. Sorry I messed this up. I'll give it another go.

**Comment by pkendall64** [comment]
> Gotcha, PK. Sorry I messed this up. I'll give it another go.

No worries.

**Comment by gchedzhemov** [comment]
Closing, since I simply cannot figure out how to rebase and force push without doing a brand new PR

**Pull request closed without merging**
