### PR TITLE
Diversityfunction

### PR DESCRIPTION
**Pull request by StonedDawg**
Based on master commit 149b8aaffef5d27d3b42c3500df01846328dc691
This code added function was based on JamesK first method on the diversity function, so far it does not cause any problem, but need more testing more to see how much advantage we can get.
still need more work on other method and more result.

to help this branch please enable DEBUG_CRSF_LINK for blackbox when trying this.

### CODE REVIEW

**Comment by StonedDawg** [comment]
sorry for the mess, code has been updated based on the master - RC1, and PR has been re targeted to develop

**Comment by JyeSmith** [comment]
@StonedDawg I'm hoping to have a good look at this when my rf switches arrive and now that binding is mostly done.

Do you mind post BB logs here so that dont get lost on discord.

**Comment by StonedDawg** [comment]
@JyeSmith Sure
BB log showing latest diversity code running on r9 Slim+ OTA, 10mw power, TX was on 1st floor, RX get in an elevator and goes up to 5th floor: 
https://drive.google.com/file/d/1LYZkLqxnGzE-UWDoczHg9PXkFcZAjd80/view?usp=sharing

BB log showing latest diversity code running on r9 Slim+, 10mw power, TX was on 1st floor, RX get in an elevator and goes up to 5th floor and failsafe on 6th (elevator motor room)  : 
https://drive.google.com/file/d/1lqFGM8jWdJrb5GcBa-fpIf7tma3WTe94/view?usp=sharing

**Comment by StonedDawg** [comment]
further testing to see if diversity would make the LQ worse or not, it seems stable and doesn't affect the LQ.
here is the log, RF mode will show which antenna is activated, log was recorded in 2khz, when flight mode was changed to angle mode is when failsafe stage 1 occurred.

https://drive.google.com/file/d/1X809b7cBEd7EZhFcTJ4R90IdT6F2B3pt/view?usp=sharing

**Comment by StonedDawg** [comment]
latest code BBL, done in the same test condition as before : 
https://drive.google.com/file/d/1qbunaU1QnHRcyAMIX4Z-gwSGLdOmn4Gb/view?usp=sharing

**Comment by StonedDawg** [comment]
BBL based on 8e50d49, done in real flight.
https://drive.google.com/file/d/1SRoIozWMnDkx9TCfr94ts3Cd5KjR34Yz/view?usp=sharing

**Comment by ClickNciak** [comment]
Hy🙌🏽
May I merge this feature? 
Is stable for slim+ plus and work by twoAntenna?

**Comment by StonedDawg** [comment]
@ClickNciak for now this is stable and working but it is not compared yet with the other methods

**Comment by ClickNciak** [comment]
Thanks you 🙌🏽

**Comment by JyeSmith** [comment]
@StonedDawg @JBKingdon is there a version of diversity you would like to commit?  This PR?  Even if it is basic dumb switching on a missed packet.  Pretty much anything so that we have basic functionality.  Then we can continue to play with fancier methods.

**Comment by StonedDawg** [comment]
@JyeSmith @JBKingdon there is no addition to this method.. but @JBKingdon also has the preamble method ready too?

**Comment by JyeSmith** [comment]
Do you mind rebasing it on latest dev and we can look at getting in merged 👍

**Comment by StonedDawg** [comment]
@JyeSmith ok, it is now has been rebased with the latest develop

**Comment by StonedDawg** [comment]
really sorry for the complete mess before, I messed up my git cache or something, I just fix it and force pushed...really sorry..

**Comment by JyeSmith** [comment]
@StonedDawg been there and done that... And will do it again in the future 😄

**Comment by sfersystem** [comment]
Diversity tested with Betaflight at 10mw - 500mw and 1000mw
R9M and R9 Slim +

[Here the BB files and DVR](https://wetransfer.com/downloads/25a097ae7b6e6e260ff107ef871c379e20210325133947/23695efb410e1574de7d88bfbf4fc86920210325134032/b0f84c)

**Comment by StonedDawg** [comment]
> Diversity tested with Betaflight at 10mw - 500mw and 1000mw
> R9M and R9 Slim +
> 
> [Here the BB files and DVR](https://wetransfer.com/downloads/25a097ae7b6e6e260ff107ef871c379e20210325133947/23695efb410e1574de7d88bfbf4fc86920210325134032/b0f84c)

hey @sfersystem , were you flying with diversity flashed already? bf debug mode is certainly crsf_uplink but in the log it seems like diversity is not active because it stays on 1 antenna all the time...

**Comment by sfersystem** [comment]
Oh, i'm sorry i'm a bit noob with that, but yes, i flashed the ext R9M and the slim + this morning
with the configurator

**Comment by StonedDawg** [comment]
> Oh, i'm sorry i'm a bit noob with that, but yes, i flashed the ext R9M and the slim + this morning
> with the configurator
> 
> https://drive.google.com/file/d/1Y5u6sIVH4A6z-OtoCfNoT2oZhRW_BUGo/view?usp=sharing
> https://drive.google.com/file/d/1oSlkOMSMn7sPDGLCQQJloqWyYRt9O_RU/view?usp=sharing

have you uncomment the -DUSE_DIVERSITY in the user_defines.txt?

**Comment by sfersystem** [comment]
> have you uncomment the -DUSE_DIVERSITY in the user_defines.txt?

No !

**Comment by sfersystem** [comment]
> 
> 
> > > have you uncomment the -DUSE_DIVERSITY in the user_defines.txt?
> > 
> > 
> > No !
> > Where is this file ?
> 
> I just had a look in the screenshot you sent. you used another diversity branch (not this PR) which its main code has not been updated for a long time...can you find the diversityfunction (instead of diversity-experiment)?

No, i haven't this choice in the list.

**Comment by sfersystem** [comment]
Someone can help me to install the right firmware ?

**Comment by StonedDawg** [comment]
> Someone can help me to install the right firmware ?

hey sorry I'm still trying to get the branch work on configurator. anyway you can try with vscode and platformio first if you want

**Comment by sfersystem** [comment]
Ok, i understand, but i have never used it before, i just see the video from UAVTECH, but how can i find this firmware ?

**Comment by StonedDawg** [comment]
> Ok, i understand, but i have never used it before, i just see the video from UAVTECH, but how can i find this firmware ?
> 
> Should i clone this link ?
> https://github.com/StonedDawg/ExpressLRS.git

yes, and then on the bottom left corner, where there is "master", you can click it and change it to the deversityfunction

anyway now the configurator has been updated to 0.46, and you can use the "git commit" to select the diversityfunction, copy this PR hash ( `89a098f42163a8388da108e0b4b504c3260a1c20` ), and also copy the `user_defines.txt` ([LINK](url)https://github.com/ExpressLRS/ExpressLRS/blob/89a098f42163a8388da108e0b4b504c3260a1c20/src/user_defines.txt(url)) from this PR and pick manual mode from the "device option", and paste it there and edit according to your settings.

**Comment by sfersystem** [comment]
> yes, and then on the bottom left corner, where there is "master", you can click it and change it to the deversityfunction
> 
> anyway now the configurator has been updated to 0.46, and you can use the "git commit" to select the diversityfunction, copy this PR hash ( `89a098f42163a8388da108e0b4b504c3260a1c20` ), and also copy the `user_defines.txt` ([LINK](https://github.com/ExpressLRS/ExpressLRS/blob/89a098f42163a8388da108e0b4b504c3260a1c20/src/user_defines.txt)) from this PR and pick manual mode from the "device option", and paste it there and edit according to your settings.

Great, thank you.
Flashed done 
New sunny day, new test today.
Come back in few hours (sorry for my English)

**Comment by sfersystem** [comment]
I just checked all my stuff before flying and just notice that i have a '"?" in ELRS lua power line. 
Before i can switch the power from 10mw to 2000mw 
Something wrong with my "user_defines.txt" ?
[User defines.txt](https://github.com/ExpressLRS/ExpressLRS/files/6210679/User.defines.txt)

**Comment by StonedDawg** [comment]
@sfersystem no, its just that you need to update the elrs.lua in your handset, get it here [LINK](https://github.com/StonedDawg/ExpressLRS/blob/diversityfunction/src/lua/ELRS.lua)

**Comment by sfersystem** [comment]
All is ok now .. Thank you.

Just a question please.
Can you tell me what does every settings mean in lua 
If i understand Rate is the latency, higher rate less latency but less range
TLM Ratio ??? (don't know at all)

**Comment by sfersystem** [comment]
Successfully tested. 
here the files
[BB Diversity 26.03.zip](https://github.com/ExpressLRS/ExpressLRS/files/6211969/BB.Diversity.26.03.zip)

**Pull request merged**
