### PR TITLE
Adds Rx fan support

### PR DESCRIPTION
**Pull request by thesacredmoocow**
adds emax aeris 900 nano as an RX target, with some patches to the RX code to make the fan work. apologies in advance for the garbage code lol, will clean up if there is any intention to actually merge this.

### CODE REVIEW

**Comment by JyeSmith** [comment]
Is this still good to go?

While the Aerial waynt designed to also be a RX, the Bandit Nano is and has been added has a RX target.

Let's get the title changed to singing like "Adds Rx fan support".

**Comment by thesacredmoocow** [comment]
> Is this still good to go?
> 
> While the Aerial waynt designed to also be a RX, the Bandit Nano is and has been added has a RX target.
> 
> Let's get the title changed to singing like "Adds Rx fan support".

I haven't updated my elrs systems in a while but I've used my build of it since I wrote the PR initially and it's been working fine. If there's any desire to merge the PR I can check to make sure the latest master hasn't broken anything with it?

**Comment by JyeSmith** [comment]
> If there's any desire to merge the PR I can check to make sure the latest master hasn't broken anything with it?

That would be great.

**Comment by wvarty** [comment]
The builds look to be failing on a few targets.
This will need to be fixed up before we can get it into v3.5

**Review by pkendall64 — APPROVED** [review]

**Review by wvarty — APPROVED** [review]

**Pull request merged**
