### PR TITLE
Fix the font overflowing on TFT screens

### PR DESCRIPTION
**Pull request by pkendall64**
During the updates to the TFT screen driver, the chosen font for "normal" size was slightly too large and would over flow.
See #1588

### CODE REVIEW

**Comment by CapnBry** [comment]
Aha! I thought the font looked bigger (and a little more jagged if I am being honest). I'll give this a try. It might be a good idea to check the "333MHz Full" to see if it fits too. In the fullres PR, I also removed the left border from the white box, since all the text is centered so the border just makes everything pushed slightly off to the right (although I haven't looked since I merged master).

The font might need to be even smaller is what I am saying.

**Comment by pkendall64** [comment]
> Aha! I thought the font looked bigger (and a little more jagged if I am being honest). I'll give this a try. It might be a good idea to check the "333Hz Full" to see if it fits too. In the fullres PR, I also removed the left border from the white box, since all the text is centered so the border just makes everything pushed slightly off to the right (although I haven't looked since I merged master).
> 
> The font might need to be even smaller is what I am saying.

Or we can change to a slightly condensed font rather then smaller 😄

**Comment by pkendall64** [comment]
@CapnBry I did some tests and after removing the GAP from the text (as you say it's centered), and the slightly smaller font, your "333Hz Full" will fit 🥳

**Comment by CapnBry** [comment]
> @CapnBry I did some tests and after removing the GAP from the text (as you say it's centered), and the slightly smaller font, your "333Hz Full" will fit 🥳

On you're just **trying** to give me a merge conflict in the massive fullres PR. I see how it is! 😅 Thanks for checking that.

**Review by schugabe — APPROVED** [review]

**Review by JyeSmith — APPROVED** [review]

**Pull request merged**
