### PR TITLE
Dynamic tx power feature

### LINKED ISSUE #305: (native) Dynamic Power
Would reduce power consumption as well as reduce contribution to RF noise floor.

("requested" by Fernandez#5615)

( #124 is not really related to this)

### PR DESCRIPTION
**Pull request by SunjunKim**
This resolves #305.

This Dynamic Power features less power consumption, reducing the risk of potential overheating of a TX module, and less congested RF environment. 
The feature relies heavily on telemetry data, so it needs telemetry to be turned on (and ideally more frequently) to work smoothly.

A configured power on the Lua script will work as "MaxPower" set on the TBS Crossfire/Tracer system -- the output power will not exceed the configured power and only be reduced from it.

The power adjustment works in two ways:
1. RSSI-based slow speed power change: from an RX sensitivity limit (hard-coded from a configured packet rate), -15 dB to increase power / -30 dB to decrease power = There are 15dB margin from the link budget, and 15dB gap for handling potential hysteresis.
2. LQ-based power boost: when experiencing a rapid LQ drop (-20 in a short time), or less than 50 LQ, the power immediately boosts up to the configured power.

For general use, a user sets the configured power to be the maximum power allowed in a certain flying field or set to the TX module's maximum for a long-range flight. This feature will adjust the power levels down automatically, in general stays <50 mW in near-range flights.

### CODE REVIEW

**Comment by CapnBry** [comment]
I've reviewed this code over the course of the discussion of the best way to make this work simply and still cover the two big power-change scenarios (slow declines and sudden drops). I've also test flown a bunch of packs and did the house walkaround on the edges of power transitions and it works nicely. I like being able to just set the max power in the Lua config and it drops to 10mW while I am working at the desk versus setting a minimum power and letting it power climb to max if needed.

It will be nice to save people some power, especially for anyone who keeps their power level high "just in case". The TX will run a bit cooler too which means it might put out more power when it is actually needed. It also means the fan is dynamic too, turning on when the power bumps up and then turning off if not needed.

I'm game to approve this PR for 1.1 unless someone can come up with a simpler and more effective algorithm. I'm going to hold my approval though until #725 goes through because knowing the active antenna will simplify the RSSI averaging code in this PR to just this for both diversity and non-diversity configurations.
```
rssi = (active_antenna == 0) ? rssi1 : rssi2;
```

**Comment by CapnBry** [comment]
I'm not for allocating a channel to this feature, I think the new commit should be reverted. I think this PR should be limited to strictly the dynamic power feature and not affect the interpretation of channels.

Also, for the record, `ChannelDataIn[]` is not in us units so the code is also wrong.  It should compare against `CRSF_CHANNEL_VALUE_MID`, and also shouldn't anything around 1500 also be considered a disable, so 3-pos switches won't be possibly on the edge of toggling the power output if the handset is doing an analog reading of the input channel.

But mostly, I am against dedicating a channel as part of this PR.

**Comment by SunjunKim** [comment]
I think I reverted to the previous version.... somehow.

**Comment by SunjunKim** [comment]
> But mostly, I am against dedicating a channel as part of this PR.

I agree with this regarding this PR.
However, I believe similar feature requests like this would be come up someday in the future.

**Comment by JyeSmith** [comment]
@SunjunKim https://github.com/ExpressLRS/ExpressLRS/pull/725 has been merged.  Do you want to update and we can get this merged.

**Comment by ZupinM** [comment]
Me and some friends have been using my version of dynamic power  for half a year now.  (fork on my account if you want to look  at) It is only simple  switch based on LQ that uses 2 stages of how fast it switches ( LQ<100->slowly countdown to switch, LQ<95->switch to higher power almost imediately).  Works ok and never had any problems.  I also added short buzzer pulses to indicate the switch of power, which i would say is useful, so you know at what power you are.
I will try this version and see how it compares.

**Comment by JyeSmith** [comment]
The rx output power is much less than the tx and TLM packets will potentially be lost before the tx output is anywhere near max power e.g. a wing LR flight, or even an obstruction when flying a bando.

Should an extra condition be use alongside `dynamic_power_updated` based on TLM timeout?  Maybe every 3s interval after the last TLM packet received the power should be increase by 1 level up to max?

**Comment by SunjunKim** [comment]
> The rx output power is much less than the tx and TLM packets will potentially be lost before the tx output is anywhere near max power e.g. a wing LR flight, or even an obstruction when flying a bando.
> 
> Should an extra condition be use alongside `dynamic_power_updated` based on TLM timeout? Maybe every 3s interval after the last TLM packet received the power should be increase by 1 level up to max?

Could you point a variable or function that can check a TLM timeout?
I'd suggest that when TLM timeout happens just instantly pull the power up to the max, which makes a logic simpler.

**Comment by SunjunKim** [comment]
> @SunjunKim #725 has been merged. Do you want to update and we can get this merged.

I'd like to merge after update the diversity antenna selection feature #725 to be co-work with this.

**Comment by SunjunKim** [comment]
> Me and some friends have been using my version of dynamic power for half a year now. (fork on my account if you want to look at) It is only simple switch based on LQ that uses 2 stages of how fast it switches ( LQ<100->slowly countdown to switch, LQ<95->switch to higher power almost imediately). Works ok and never had any problems. I also added short buzzer pulses to indicate the switch of power, which i would say is useful, so you know at what power you are.
> I will try this version and see how it compares.

Thanks I'll take a look!

**Comment by JyeSmith** [comment]
@SunjunKim  you could use `LastTLMpacketRecvMillis`.

But I agree there needs to be a condition around it so the tx doesnt go to max when you unplug a battery at the end of a flight.

**Comment by CapnBry** [comment]
For sure it can't just be based solely on the last telemetry packet timing as well. It has to account for both packet rate and telemetry ratio to not just jump to full after a fixed interval.

Range is also **highly** asymmetric with the TX getting so so so much more range than the RX sending telemetry back (with the majority of RX not having any PA hardware) so it might be better to slowly ramp up power. Say only once every 5 telemetry periods like the current code does, if no telemetry packets were received in the time it should have taken to get enough data to make the RSSI-based calculation. I'd love to hear better ideas apart from "missing a telemetry packet = MAX POWER" if possible since we miss a lot of telemetry packets. I really want to avoid having so many exceptions to the dynamic power ramp that we're always just at max power.

Also, as Jye said, we need to make sure unplugging doesn't spike the power, but I'm not sure how to accomplish that. Maybe TQly of >90 means take the power up slowly?

**Comment by SunjunKim** [comment]
I want to merge the current version as it's working stable so far.
Diversity code simplification regarding #725 is done now.

Let's think about the telemetry lost situation in a future PR.

**Review by CapnBry — APPROVED** [review]

**Comment by SunjunKim** [comment]
> Range is also **highly** asymmetric with the TX getting so so so much more range than the RX sending telemetry back (with the majority of RX not having any PA hardware) so it might be better to slowly ramp up power. Say only once every 5 telemetry periods like the current code does, if no telemetry packets were received in the time it should have taken to get enough data to make the RSSI-based calculation. I'd love to hear better ideas apart from "missing a telemetry packet = MAX POWER" if possible since we miss a lot of telemetry packets. I really want to avoid having so many exceptions to the dynamic power ramp that we're always just at max power.

To make the overall logic simple, I’d like to give users an option to choose by themselves, saying, the-one-button-to-max-the-power. When a user feel like to raise the power, they can do by just flicking a switch.
https://youtu.be/wdPWw2xu8Ig

**Comment by JyeSmith** [comment]
@SunjunKim is it worth writing a wiki doc we can point users to which describes how dyn power works.  You can also link your demo flights.

**Comment by SunjunKim** [comment]
> @SunjunKim is it worth writing a wiki doc we can point users to which describes how dyn power works. You can also link your demo flights.

Will do soon!

**Comment by jurgelenas** [comment]
> > @SunjunKim is it worth writing a wiki doc we can point users to which describes how dyn power works. You can also link your demo flights.
> 
> Will do soon!

I have created an issue for that in our docs repository: https://github.com/ExpressLRS/Docs/issues/13

**Comment by CapnBry** [comment]
I've written a doc in the wiki to describe the feature. If it looks good and I've stopped editing it for a few days, I'll get it over to the website.
https://github.com/ExpressLRS/ExpressLRS/wiki/Dynamic-Transmit-Power

**Comment by SunjunKim** [comment]
> I've written a doc in the wiki to describe the feature. If it looks good and I've stopped editing it for a few days, I'll get it over to the website.
> https://github.com/ExpressLRS/ExpressLRS/wiki/Dynamic-Transmit-Power

Great document! I added some more details on top of it.

**Pull request merged**
