### PR TITLE
Add an ELRS theme to color screen and mockup

### PR DESCRIPTION
**Pull request by CapnBry**
This intends to fix the color Lua script to not bomb out on OpenTX due to EdgeTX constantly changing their colors, and provides an OKish ELRS-colored theme to the color display. The fields are rendered using the handset's native display colors to prevent them from just becoming completely f'ed up. TX16S and T16 respectively:
elrs-clr-renders2

Also adds one vertical space under the title bar on B&W screens per @AlessandroAU.
image

## Bug Fixes
There's two variations on the bug on color displays
* Straight up crashing OpenTX and rebooting it into Emergency Mode on script launch due to them mishandling color definitions they do not understand
* `Attempt to perform arithmetic on nil value M...` on some versions of EdgeTX
* Fix CPU Limit killing script if scroll wheel is used before any fields load
* Fix Index nil error when exiting if no fields loaded

## Additional
* Adds a mockup lua helper script that allows for seeing how the Lua will display on any type of screen using the OpenTX Companion Simulator. I didn't mock up all the fields though, just enough to do the main screen and TX Power. More fields can be added to be able to test folders / BACK if desired.

## Broke as Heck
The color support in OpenTX is reeaaaaaaallly weird. Changing colors does not seem to be something it wants to do. If you change the TEXT_COLOR it breaks how text with no attributes renders _in the script_. Blue text becomes black text. The only way to get the color you want is to use BOLD. I think there's a font cache rendered in the actual theme color so trying to change things breaks its expectations. I've attempted to work around how changing to some colors makes the background draw in the theme color, and used CUSTOM_COLOR and setColor with BOLD to trick it somehow but this is likely fragile and could break easily leaving the script unreadable on some setups.

I think we should just go back to rendering in default colors.

## Testing
Needs testing on EdgeTX 2.4 and 2.5 nightly. I have tested this in OpenTX Companion Simulator for X9D, QX7, TX16S, and Jumper T16. Also tested on TX16S and Jumper T16 by Discord user mgtschida, many thanks!

### CODE REVIEW

**Comment by CapnBry** [comment]
I'd recommend that we remove all the color theming and go back to rendering in default colors. The color system is just so weird this is likely to not work on all radio colors (yes the theme color seems to be important) and is fragile enough that we could end up being unreadable on some screens or future handset updates.

**Comment by StonedDawg** [comment]
@CapnBry If OpenTX LUA or some other firmware lua is acting weird or cannot run our lua properly, yeah I agree we should keep the default color. this lua supposed to be the most basic lua for elrs setup for any user, with any handset firmware.

**Comment by CapnBry** [comment]
Just a sampling of how differently the same settings render on different models:

elrs-clr-renders

Note the text color on TX16S changes how the background renders, and it isn't in either color requested regardless of if CUSTOM_COLOR is used. Meanwhile the bold text is often in the right color. The INVERT attribute shows a similar set of issues, which is why I had to make it bold to show up properly. Non-bold will use the correct background color to clear the area the text is going, then write on it in the handset's theme color leaving 1px of the correct color on each side of the inverted text but the text itself is in the handset's color.

**Comment by CapnBry** [comment]
I'm done with this! Sure it doesn't look great on color screens but it is consistent with the handset's theme? About as good as I am willing to do after spending like 10 hours on this.

Please review now.

**Review by StonedDawg — APPROVED** [review]
there is so much to give away to take the route around evading all these FW conflicts and still this LUA looks pretty good!

**Review by pkendall64 — APPROVED** [review]

**Comment by pfeerick** [comment]
Indeed... some elements of Lua scripting are an absolute disgrace, which is why some Lua scripts have had to do some really shady stuff to work as well as they do... and it's even harder with out of date information. We're trying to fix both over at ETX, but it'll take a while, and at least we have Lua script devs giving input and/or contributing some of the changes to make things actually work properly ;)

**Comment by CapnBry** [comment]
> Indeed... some elements of Lua scripting are an absolute disgrace, which is why some Lua scripts have had to do some really shady stuff to work as well as they do... and it's even harder with out of date information. We're trying to fix both over at ETX, but it'll take a while, and at least we have Lua script devs giving input and/or contributing some of the changes to make things actually work properly ;)

Yup agreed. I was nice to see EdgeTX start refactoring it to make sense. I think it just sort of grew generically as vendors did their own thing and it just became inconsistent. Unfortunately, not only does the code have to make it to release, but it will be years probably before users upgrade enough that workarounds won't have to exist in Lua too (sad slumped emoji)

**Pull request merged**
