### PR TITLE
Add BLE Telemetry device

### PR DESCRIPTION
**Pull request by sixtyfive**
Hi all! Not sure where to comment on this ... the author of this commit (@dz0ny) seems to have written code for using BLE as a telemetry device. Can somebody take a look at the code and see if they can figure out whether (a) it is intended to send telemetry between ELRS TX and ELRS RX or (b) to _forward_ telemetry from ELRS RX via ELRS TX to a groundstation connected via BLE?

### CODE REVIEW

**Comment by sixtyfive** [comment]
Thank you for the prompt answer, dz0ny! So I'm understanding correctly that it's not inteded for connecting a laptop-based groundstation with the craft using something like Mavlink?

**Comment by pkendall64** [comment]
Hey @dz0ny since you are the author of this code/branch, do you want this PR open? If so the code will need to be updated and building on all platforms. If not then just let me know and I'll close this PR and you can open a new one when you are ready.

**Comment by dz0ny** [comment]
@sixtyfive this is not close to Mavlink, it would only expose telemetry data as BLE service that the apps then can use to show the data. 

@pkendall64 Please close, there was discussion on Discord and this approach is not the correct way.

**Comment by pkendall64** [comment]
> @pkendall64 Please close, there was discussion on Discord and this approach is not the correct way.

Thanks for getting back to me

**Pull request closed without merging**
