### PR TITLE
[WIP] ExpressLRS Radar

### PR DESCRIPTION
**Pull request by CapnBry**
Sometimes it is nice to know where other pilots are, a lot of people think it is a good idea. This PR adds radar functionality to existing ExpressLRS Team900 and Team2.4 hardware which is capable of broadcasting and receiving pilot / model location and identification information **while still using the hardware for the control link**. ESP and ESP32 hardware only, sorry PP / R9 receivers, you're not capable.

Currently supported:
* A Basic ID message containing a device serial number (ANSI/CTA-2063-A), i.e. a device ID
* A Basic ID message contain a Civil Aviation Authority (CAA) issued registration number, i.e. a pilot ID
* One of the two Basic ID messages can be replaced with an UTM assigned ID if operating with a UTM system
* An Operator ID message, if not present in a Basic ID message
* A location message containing current UAS position: latitude, longitude, altitude, speed, heading
* Pilot (control station) takeoff location: latitude, longitude, altitude
* Transmission interval for completing send of all messages 500ms (2 updates per second) currently
* WiFi 2.4GHz Beacon mode operation (up to 20dBm EIRP possible)
* Operates from takeoff to shutdown
* Transmission is non-proprietary using radio frequency compatible with personal wireless devices in accordance with part 15 of title 47, Code of Federal Regulations where operations may occur without FCC individual license

image

Missing requirements to be completed:
* MISSING: A method for indicating the status of the broadcast system (LED or buzzer) which indicates it is operational
* MISSING: A method for the pilot to indicate they are operating in a GNSS Canyon or Indoor operation to disable any Location requirement
* MISSING: A time mark identifying applicability of a position output in UTC

### Features
* The inability to turn it off! I have not yet done any of the configuration side so this PR has it always enabled, using IDs compiled into the code. This will be user configurable when it is complete.
* On-UAS reception of other ExpressLRS Radar users, which is published to the flight controller via MSP2_COMMON_SET_RADAR_POS message (0x100B). iNav has an OSD element for displaying these other users in a radar-fashion. Betaflight and Ardupilot can also support this, and the [FormationFlight project](https://formationflight.org/getting-started/#ardupilot) has test fork builds with the functionality added. Note: this PR currently does not send the data to the flight controller yet as ExpressLRS needs more infrastructure to build the dang packet. (Image courtesy of [Mr.D RC](https://www.mrd-rc.com/tutorials-tools-and-testing/flight-controller-therapy/esp32-radar-finding-your-friends-in-the-sky/))

ESP32-Radar-View-OSD-elements

* Reception possible from cellphone with no additional equipment using the OpenDroneID application ([Android](https://play.google.com/store/apps/details?id=org.opendroneid.android_osm)) or Drone Scanner ([Android](https://play.google.com/store/apps/details?id=cz.dronetag.dronescanner) [iPhone](https://apps.apple.com/gb/app/drone-scanner/id1644548782))

Screenshot_20230622-124936_OpenDroneID-(2)Screenshot_20230702-094434

### Is this RemoteID?
No of course not. A RemoteID device must go through a certification process to be considered compliant, and this has not so therefore this is not at all RemoteID. In my limited testing, no current ExpressLRS hardware appears capable of meeting the radiated power requirement (EIRP) for RemoteID due to their size-constrained wifi antennas.

### Details
This adds a new ExpressLRS device class "devRadar" which utilizes the MCU's wifi/bluetooth radios to broadcast [OpenDroneID](https://github.com/opendroneid/opendroneid-core-c) packets. Promiscuous mode is used to sniff and decode other radar broadcasts. GPS information comes from a connected Flight Controller via the CRSF GPS telemetry packet, although PWM RXes can also get Radar if they use an external GPS module + CRSF converter (we could natively support GPS some day too).

The current transmission rate is 2Hz and I see no noticeable degradation in ELRS Link Quality despite having a 2.4GHz transmitter literally adjacent to the SX1280. I'm pretty sure it does have an impact, but further testing will determine if this is safe for long term use.

The range of the transmission is ... not spectacular. This is not a limitation of the radio hardware, but more how the "wifi range" of our tiny receivers is sort of an afterthought in design. This can be improved if necessary using actual wifi antennas, or perhaps a small 2.4GHz PA. Even with the suboptimal hardware, line of sight reception ~90m is currently possible.

### External Needs
* An accurate time source is needed. There is no CRSF message to get GPS time, but maybe the MSP_RTC command can get it? I know there is an MSP time set command, there better be a get! If not, we could use Lua to set it from the handset.
* Geometric Altitude I believe is needed? The altitude in the CRSF GPS packet tends to be a sensor fusion AGL from the baro and GPS. We need an absolute altitude from the GPS source (or a fusion that returns absolute altitude)
* Vertical speed. Both Horizontal and Vertical speed are required. I can calculate this myself using the altitude delta between packets but it would be better to get it directly. Some FC software support the CRSF VSPD sensor.
* A convenience feature would be to be able to set the UAS ID / PilotID from Betaflight, iNav, or Ardupilot configurators. Ardupilot already has these fields in their RemoteID implementation but I believe they are Mavlink commands :/

### TODO
- [x] ESP-based receiver broadcast 2.4GHz beacon signal
- [x] ESP-based receiver reception of beacon signal packets / decoding pilot and location information
- [x] External debugging Radar receiver ([ESP32 implementation](https://github.com/CapnBry/RidRadarReceiver))
- [ ] ESP32-based receiver implementation (easy!)
- [ ] Send Radar updates to flight controller
- [ ] Configuration webui
- [ ] Bluetooth Legacy-based broadcast option (ESP32 receivers only)
- [ ] Get RTC time
- [ ] Vertical speed information
- [ ] Need "geometric altitude" (MSL)?
- [ ] Range testing! Devs allegedly love range testing
- [ ] Control link interference / coexistence stress testing and characterization
- [ ] Lots and lots of documentation
- [ ] Uploading flight logs to your government every time you use the Configurator (this = joke)

### CODE REVIEW

**Comment by YI-BOYANG** [comment]
A nice feature!

**Comment by CapnBry** [comment]
-- Reserving this post for RemoteID information --

If it isn't entirely obvious to everyone, the goal of this PR is both to add a technically RemoteID-compliant mechanism. The format of the messages meets F3411-22 and is sent in a manner meeting the transport requirements for Broadcast UAS. The current transport is via 2.4GHz wifi management frame as described in section 5.4.8.2.

### Becoming a RemoteID Certified Device
Sending the requisite data in the prescribed format isn't enough to satisfy the requirements of the Federal Aviation Administration (FAA) 14 CFR Part 89 (Part 89) rule. The device must also have an approved declaration of compliance. This declaration covers not only the effective operation of the device but requires a few other major things:
* Maintaining a device serial number database
* Securing the RID device in a "tamper resistant" method
* Filing for a certificate of compliance for the devices they produce

I can maybe do one of these things, but I can provide the information and device software needed. Here I will present the COMPLIANCE MATRIX! (to be filled in as I have time and the software meets the requirement)

## TABLE 21 All Methods Compliance Matrix
- [ ] BPW0010
- [ ] BUR0010
- [ ] BUR0020
- [ ] BUR0030
- [ ] BUR0040
- [ ] BUR0050
- [ ] BUR0060
- [ ] BMG0010
- [ ] BMG0020
- [ ] BMG0030
- [ ] BMG0040
- [ ] BMG0050
- [ ] BMG0060
- [ ] BMG0065
- [ ] BMG0070
- [ ] BMG0080
- [ ] BMG0090
- [ ] BMG0100
- [ ] BMG0110
- [ ] BMG0120
- [ ] BMG0130
- [ ] BMG0140
- [ ] BMG0150
- [ ] BMG0160
- [ ] BMG0170
- [ ] BMG0180
- [ ] BMG0185
- [ ] BMG0190
- [ ] BMG0200
- [ ] BMG0210
- [ ] BMG0220
- [ ] BMG0230
- [ ] BMG0240
- [ ] BMG0250

## TABLE 22 Bluetooth 4.x Compliance Matrix
- [ ] BB40010
- [ ] BB40030

## TABLE 23 Bluetooth 5.x Compliance Matrix
No current ExpressLRS device is capable of Bluetooth 5 compliance due to hardware limitations. It is possible to achieve this with newer MCUs.

## TABLE 25 Wi-Fi Beacon Compliance Matrix
- [ ] BWFB0010
- [ ] BWFB0020
- [ ] BWFB0030
- [ ] BWFB0040
- [ ] BWFB0050
- [ ] BWFB0060

**Comment by mmosca** [comment]
Radar integration sounds great. :)

Any chance it can support the same OTA protocol as FormationFlight as well?

**Comment by CapnBry** [comment]
> Any chance it can support the same OTA protocol as FormationFlight as well?

Does FormationFlight put out Remote ID complaint messages? If so, yes. But it does not, so no. :)

**Comment by DzikuVx** [comment]
@CapnBry In case of INAV there is MSP_RTC but it does not get date time only offset since power up.
On the other hand, I'm more that willing to add such frame and return UTC time is present (GPS is up) to INAV project!

**Pull request closed without merging**
