### PR TITLE
Let the firstly updated data to initialize the LPF

### PR DESCRIPTION
**Pull request by SunjunKim**
The current LPF implementation expects`init()` is called before`update()`.
However in some cases `update()` is called without `init()` (like as in `rx_main.cpp`), or it's just unable to initialize the filter before the first value comes.

When `update()` is called without an initalization, some unknown starting value will ruin the first few tens of (and possibly hundreds of, in case of a large `Beta` value) smoothed output. 

This PR allows LPF to work properly without a mandatory `init()` call. When `update()` is called without an initialization, it will be initialized by the first-come value.

Also, `reset()` function allows to throw out some outdated value quickly, for example when two LPFs are used in a diversity setup, LPF-ed RSSI of an unused antenna may be outdated for a long time, and hinder an immediate reading of a fresh value when the antenna is switched.

### CODE REVIEW

**Comment by SunjunKim** [comment]
Note: The # of datapoints to reach 80% of the new value from the previous:
Screen Shot 2021-09-30 at 4 57 50 PM

* The numbers are approximately doubled every increase of Beta 
Beta=0 => 1
Beta=1 => 4
Beta=2 => 7
Beta=3 => 13
Beta=4 => 26
Beta=5 => 51
Beta=6 => 103
Beta=7 => 207

The default Beta = 3, and LPF for the RSSI smoothing is using Beta=5.

**Comment by CapnBry** [comment]
I'm for adding this functionality, but please match the style of the code you're integrating into (`NeedsReset` for this unit). I know our style is all over the place, but I'd like it to be consistent at least in the same file.

Also, make this part of the changes you want to the diversity code, there's no need to make it a separate PR.

**Comment by SunjunKim** [comment]
> I'm for adding this functionality, but please match the style of the code you're integrating into (`NeedsReset` for this unit). I know our style is all over the place, but I'd like it to be consistent at least in the same file.
> 
> Also, make this part of the changes you want to the diversity code, there's no need to make it a separate PR.

I close this and make another PR with the complete diversity enhancement.

**Comment by CapnBry** [comment]
> I close this and make another PR with the complete diversity enhancement.

Sounds perfect!

**Pull request closed without merging**
