### PR TITLE
Wrong firmware version displayed on web update

### PR DESCRIPTION
**Pull request by SunjunKim**
1.0 -> 1.2

### CODE REVIEW

**Comment by CapnBry** [comment]
I think this should just be changed to 1.x if it is changed at all. It has been wrong for all the firmware versions and is dynamic in 2.0 so there's no reason to make more work out of this for the 1.x branch.

**Comment by CapnBry** [comment]
I'm not sure this is worth doing anything about, especially considering we're going to try to not have a 1.3, but we can consider it at that time.

**Comment by JyeSmith** [comment]
1.2.x-maintenance has a couple of minor commits.  Thoughts on merging this for a 1.2.1 release along side the v2 RC?

**Review by JyeSmith — APPROVED** [review]

**Comment by JyeSmith** [comment]
So merging as is for a 1.2.1 release? or incrementing?

**Comment by pkendall64** [comment]
If we're going to do it, make it have the right version number

**Comment by SunjunKim** [comment]
In the v1.2.1 release, it'd be nice to have the right version number all across the interfaces.

**Comment by JyeSmith** [comment]
> 
> 
> In the v1.2.1 release, it'd be nice to have the right version number all across the interfaces.

Please update and we'll get this merged.

**Comment by SunjunKim** [comment]
I accidentally deleted my forked repo for the patch -- so I close this and redo the PR.

**Comment by lazyzero** [comment]
Shouldn't the files ESP32_WebUpdate.h and ESP8266_WebUpdate.h be updated as well? I am a newbe to ExpressLRS and the 1.0 confused me like hell. I used the ExpressLRS-Configurator. And after finding the patch I used it with the 1.2.x-maintenance branch and with a local checkout of the branch and both showed up as 1.0 in the WebUI. Only after changing the two files mentioned, it showed the correct version number....

**Comment by pkendall64** [comment]
> Shouldn't the files ESP32_WebUpdate.h and ESP8266_WebUpdate.h be updated as well? I am a newbe to ExpressLRS and the 1.0 confused me like hell. I used the ExpressLRS-Configurator. And after finding the patch I used it with the 1.2.x-maintenance branch and with a local checkout of the branch and both showed up as 1.0 in the WebUI. Only after changing the two files mentioned, it showed the correct version number....

Oh, yes you are correct, they don't get automatically regenerated like in 2.0!

**Comment by shijianzhong** [comment]
I also meet ths error , can you tell me how to resolve it please.
image
image
image
image

**Pull request closed without merging**
