### PR TITLE
Increase SX1276 SyncPktIntervalDisconnected for 25Hz

### PR DESCRIPTION
**Pull request by JyeSmith**
Currently 25Hz mode (no tlm) can have back to back sync packet sends.  This appears as a 119ms gap in the serial data.

image

Increasing SyncPktIntervalDisconnected removed the double sends while maintaining the regular sends at ~1.5s.

image

### CODE REVIEW

**Comment by CapnBry** [comment]
I thought this was intentional as part of the PR that adjusted all the sync intervals. I can't remember the exact reasoning but it was because a disconnected RX would only limited chance at syncing if there was only one sync packet. This trades away that higher chance of being able to establish a connection at suboptimal LQ.

It sucks but so does 25Hz mode for being a good link, when you're disabling telemetry to try to make up throughput (?) and now the TX doesn't even know if the RX is even connected any more and has to make these sorts of compromises.

**Comment by CapnBry** [comment]
I should say that I am not opposed to changing this but if the stage 1 failsafe is being triggered on 25Hz by missing packets, adding 1 more packet doesn't practically fix that issue except for bench testing. Yes, you have slightly better packet throughput to the FC, but isn't the FC in peril of entering stage 1 failsafe _all the time_ when LQ <100? It can go like full failsafe at LQ 87%!

I feel like this is something that needs to be addressed on the FC side or the user having to do something to prepare the FC for the incredibly low packet rate. Just adding 1 more packet in one situation might give the user a false sense of stability in bench testing that completely failsafes at high LQ (90%) in practical use.

If I am attaching the wrong dev conversation to this PR then let me know that as well, as my responses are somewhat geared toward that as the reason this PR exists.

**Review by wvarty — APPROVED** [review]

**Comment by pkendall64** [comment]
The PR @CapnBry is referring to is #784

**Review by pkendall64 — APPROVED** [review]
I'll approve on the understanding that you know what @CapnBry is referring to 😃

**Pull request merged**
