### PR TITLE
Adds BusyDelay for FLRC

### PR DESCRIPTION
**Pull request by JyeSmith**
Busy is high for much MUCH longer when setting SX1280_RADIO_SET_PACKETPARAMS for FLRC in SetPacketParamsLoRa().  This PR corrects any issues with https://github.com/ExpressLRS/ExpressLRS/pull/1477

### CODE REVIEW

**Comment by CapnBry** [comment]
How long does SX1280_RADIO_SET_PACKETPARAMS actually hold the busy?

**Comment by JyeSmith** [comment]
Upper with the double tap is FLRC, and lower LoRa. The GPIO toggle is just before the WriteCommand SX1280_RADIO_SET_PACKETPARAMS is called.

Im not sure why Busy isnt clearing before the FLRC call.  But you can see busy is higher for longer than LoRa.

image

**Comment by CapnBry** [comment]
Is this capture with the BUSY pin not defined? You gotta capture it with it defined so you can measure the actual value. The value I see in your capture is 1437us, the value you propose is 120us, I measured 30us. I agree that FLRC packet params take longer but I'm asking how you arrived at 120us for this PR. I see the ~16us from NSS going low to busy going low for Lora and ~30us for FLRC.

The fact that you see busy going high without any action is also cause for further investigation, since if it goes busy all on its own we really can't do without that GPIO to tell us when it is safe to send commands. Is it going high when the NSS goes low? In your capture it seems to be going high all the time for no reason (or am I misinterpreting the top trace being the BUSY one?).

**Comment by JyeSmith** [comment]
Yep, the delay was wrong.  Delays were actually required for ConfigModParams and SetPacketParams, FLRC and LoRa.  I also saw a lot of NSS going low before Busy with the default delay of 12us, like in the image below.  Upping this to 15 results in a minimum 1us gap between Busy going low before NSS.

Current testing with multiple spamming TXs is looking good.

image

**Comment by JyeSmith** [comment]
The Saleae v2 firmware makes it easy to find NSS going low while Busy is still high as you can setup trigger for that condition.

BusyDelay(13) still has NSS going low before Busy.  14us looks clear, but 15 give a nice 1.5us clearance like we see when the Busy pin is enabled.

image

**Review by pkendall64 — APPROVED** [review]

**Comment by CapnBry** [comment]
Wouldn't it be better to have WriteCommand() have a parameter for the expected busy duration with a default instead of adding two busydelay calls to every command? I can make this change for you if you like.

I appreciate you measuring all these extra delays and finding the cases where my oscilloscope alone wasn't enough to find them. I'm not sure about adding a 5us delay at the start of the interrupt though. I know all these happen in the interrupt but it just feels wrong that it is telling us "hey I have something for you NOW" but also "hey I'm not ready for you to do anything".

**Comment by JyeSmith** [comment]
@CapnBry that change sounds sensible, go for it.

The callback delay is required because busy is still high after the interrupt.  The ax1280

**Comment by CapnBry** [comment]
Done (and fixed the merge conflicts)! Tested on Namimno OLED and SIYI FM30 (which previously could not do FLRC due to the bad timing)

> The callback delay is required because busy is still high after the interrupt.

(whines) I knowwwwwww but clearly it is not needed since my FM30 has been my primary TX for a year and has not experienced any issues with bad LQ, or dropping the connection unexpectedly, or getting wedged. I feel like removing this is 100% safe, even FLRC on the SIYI works without it.  I mean you're fully right about adding it, the Namimno spends 0-2us busywaiting every interrupt but why force a 5us wait on busyless devices when it clearly is not needed and busycapable devices only wait 0-2us? And that's the last I'll say about it.

**Review by CapnBry — APPROVED** [review]

**Comment by CapnBry** [comment]
> Fiiinnnnneeee.... remove it since you are the only FM30 user. Lets see what happens 😁

I appreciate your handful of rope with which I will certainly hang all our FM30 users. 😘 I just saved us 12 bytes, which delays the obsolescence of this hardware for exactly 19.761 more days at our development pace.

**Pull request merged**
