### PR TITLE
Allow RX to accept telemetry from a TX module

### PR DESCRIPTION
**Pull request by CapnBry**
The RX code only will recognize telemetry coming in that starts with 0xC8 (CRSF_SYNC_BYTE  / CRSF_ADDRESS_FLIGHT_CONTROLLER) or 0xEC (CRSF_ADDRESS_CRSF_RECEIVER), but TX modules put out 0xEA (CRSF_ADDRESS_RADIO_TRANSMITTER). This means users with a relay system set up can not receive telemetry from the model:
```
handset <-> TXmodule1 <-> OTA1 <-> RX1 <-> TXmodule2 <-> OTA2 <-> RX2 <-> model
```
This simple change prevents RX1 from discarding any telemetry received from TXmodule2 which then forwards it back to the handset. Note this does not forward LinkStats "telemetry" because it is not true telemetry and is generated internally. Making that work involves a lot of poking around to override RX1's LinkStats as well as implementing a CRSF LinkStats parser on the receiver.

Tested with 
TX16S EdgeTX 2.8.1 <-> RadioMaster Ranger Micro <-> BetaFPV Lite (Flat) <-> Fyujon DUPLETX ESP <-> Vantac RX <-> iNav 6.0.0

I tagged this as 3.3 since it is small and would be nice to get in, but I do understand if this needs to be pushed back to 3.4.

### CODE REVIEW

**Review by JyeSmith — APPROVED** [review]

**Comment by CapnBry** [comment]
Successful test by user, yay!
https://github.com/ExpressLRS/ExpressLRS/discussions/2279#discussioncomment-6377067

**Review by pkendall64 — APPROVED** [review]

**Comment by DangerD1024** [comment]
What should i wire from RX to TX?
TX pin from receiver to bottom pin of module?

**Comment by DangerD1024** [comment]
Anybody?

**Comment by pkendall64** [comment]
You need to wire the receiver to the transmitter module via a full UART.
So it's the usual RX to TX, TX to RX. If you have a external module bay style module then you will need to figure out where the RX and TX pins are on it.
I would suggest asking on discord as this is very similar to setting up airport on an external module.

**Comment by DangerD1024** [comment]
> You need to wire the receiver to the transmitter module via a full UART. So it's the usual RX to TX, TX to RX. If you have a external module bay style module then you will need to figure out where the RX and TX pins are on it. I would suggest asking on discord as this is very similar to setting up airport on an external module.

Should i change default speed of RX?

**Comment by CapnBry** [comment]
> Should i change default speed of RX? To 400000

You **must** change the baud rate of the RX. The TX supports any of these bauds: 400000, 115200, 5250000, 3750000, 1870000, 921600, 2250000. You may need more baud than 400k depending on what packet rate you're using (same as if it were a transmitter in a handset).  921600 supports all current ExpressLRS packet rates.

**Comment by DangerD1024** [comment]
image
This image was sent to me from manufacturer
image
I've connected is this way, but it doesn't work... Foxeer 2.4GHz receiver baudrate is set to 400000

Any ideas?

**Comment by CapnBry** [comment]
Github PRs are not a tech support forum. I will not reply to another message, but if you've got it connected like that you also need to go into the TX's hardware.html and tell it CRSF is on pins 1 (CRSF TX) and 3 (CRSF RX) and remove those pins from any other field on that page (backpack probably).

**Comment by DangerD1024** [comment]
> Github PRs are not a tech support forum. I will not reply to another message, but if you've got it connected like that you also need to go into the TX's hardware.html and tell it CRSF is on pins 1 (CRSF TX) and 3 (CRSF RX) and remove those pins from any other field on that page (backpack probably).

Dipswitch connects those pins to some device, currently they all are turned off, so no other device is connected...
P.S. on discord on this kind of question nobody would help. I've created topic 3 monthes ago in help-and-support and there's no any reply regarding that, so i'm bothering you)

**Pull request merged**
