### PR TITLE
Set Sync Address Control to zero bit errors permissible

### PR DESCRIPTION
**Pull request by JyeSmith**
The Sync Address Control register can be configured to allow between 0-15 bit errors in the sync word (default is 4).  At first this sounds ok to allow some errors in the sync word if it means a valid packet can still be received.  But it turns out the HW CRC includes the sync word.  So any errors in the sync word will mean the CRC fails.  So there isn't any point receiving a packet with sync word errors.

Changing to 0 error means the radio will stop listening if the sync word has errors (Im pretty sure this is what happens) and go back to waiting for a preamble.  If an interfering packet with a similar sync word is being received, the radio will now stop and return to listening and hopefully receive the correct packet.

Side note... the 24b CRC used now has a reduced HD from 8 to 6 due to the 4 extra bytes included.  HD6 is still inline with the CRC16 used with LoRa packets.

Bits 4-7 of the register are unknown and need to be preserved.

This is a minor improvement and needs some user testing.

image

image

### CODE REVIEW

**Comment by JyeSmith** [comment]
I put nearly 20 packs through this at an event today.  Looks solid.

**Comment by CapnBry** [comment]
The code seems correct, but just to clarify for my testing, I should see roughly the same LQ at F500/F1000 in a congested environment, but them being flagged as errors coming into `ProcessRFPacket()` instead of failing our software CRC check due to them being for another RX? Just trying to work up my testing methodology?

Also this is for 3.0 right? I'm assuming it is.

**Comment by JyeSmith** [comment]
Previously with the default of 4 bit errors allowed a packet with similar sync word would still be received, but the HW CRC fails.  In the scoreboard it is flagged as a crc error.

The same packet with this change should not even trigger the rx done irq.

Theoretically LQ might be higher because the radio stops listening to the packet with a similar sync word and goes back listening for the correct packet.
 
> Also this is for 3.0 right? I'm assuming it is.

Either way as its a non breaking change.

**Review by pkendall64 — APPROVED** [review]
Bench tested. All good.

**Pull request merged**
