### PR TITLE
Extracting/Normalising RX targets that have Power Amps

### PR DESCRIPTION
**Pull request by pkendall64**
Rename BETAFPV Nano target file to "Generic 2400 PA", which is used by BETAFPV Nano, Matek R24-S and Vantac targets (others later as well).

This adds a target file for receivers using the SE2431 PA/LNA with diversity. Which is used by Matek R24-D (and others later).

The target to flash is Unified and choose "Generic ESP8285 + Diversity PA 2.4Ghz RX" at the prompt before flashing.

# Reasoning

This is required because in 2.5, the Matek R24-S and R24-D share the same target and expect the user to define `USE_DIVERSITY`.

In 3.0 that option is gone as we allow the user to choose antenna A, B or diversity from the RX LUA.

~~Also, the Matek R24-D and R24-S have different PA chips! And so should have a seperate target file.~~ Actually the power values are very similar on the chips, so really it's just because of the previous reason.

# TODO

Someone with a decent RF meter needs to check the power values on a RX with an SE2431 (but they should be similar to the 2401 if the datasheets are to be believed).

### CODE REVIEW

**Comment by CapnBry** [comment]
I'm not sure I understand because I can't see any different in code, but why is a AT2401 different than a SE2431 such that they need different bases entirely? I thought just setting GPIO_PIN_ANTENNA_SELECT would enable the Diversity option, or does one of those two frontends have antenna select that needs to be toggled for even non-diversity?

**Comment by pkendall64** [comment]
You are right, there is no different code. But if we have a shared config file, that has ant_select defined, to pin 9, then the non-diversity RX will say in the LUA that they have diversity!
Also, the PA chips have different output power and different gains.

**Comment by pkendall64** [comment]
Perhaps what we need then is a Generic 8285 PA, and Generic 8285 Diversity instead?

**Comment by CapnBry** [comment]
> Perhaps what we need then is a Generic 8285 PA, and Generic 8285 Diversity instead?

I think you might be onto something there because that distinction seems be clearer. They both can have a TX enable and an RX enable, but only a diversity would have the antenna select, regardless of what chip is used, right? Other frontends that support switching antennas would use generic diversity, and not specifically SE2431. Then also makes it immediately clear to me without having to look at the data sheets what the difference is, so I think that would be better if you agree.

**Comment by pkendall64** [comment]
> > Perhaps what we need then is a Generic 8285 PA, and Generic 8285 Diversity instead?
> 
> I think you might be onto something there because that distinction seems be clearer. They both can have a TX enable and an RX enable, but only a diversity would have the antenna select, regardless of what chip is used, right? Other frontends that support switching antennas would use generic diversity, and not specifically SE2431. Then also makes it immediately clear to me without having to look at the data sheets what the difference is, so I think that would be better if you agree.

I pre-agreed with you 😆 and pushed that change.

**Review by CapnBry — APPROVED** [review]
Yeah now this makes perfect sense, thanks for explaining to get me there, and the rename.

**Review by AlessandroAU — APPROVED** [review]

**Pull request merged**
