### PR TITLE
DIY ESP32 E28 10ch PWM RX

### PR DESCRIPTION
**Pull request by mariusdp**
**DIY ESP32 E28 10ch PWM RX.**

Simple to build for anyone using E28 module. Hardware under ExpressLRS-Hardware/10ch_E28_RX. 

Thank you all for the amazing project :P

### CODE REVIEW

**Comment by JyeSmith** [comment]
At the moment we are just doing bug fixes for v3.0.

**Comment by CapnBry** [comment]
Any "DIY" build should also be able to use the same pin definitions as Frank 2400, instead of a completely new set of pin definitions. The VTX stuff isn't needed so those can be repurposed as the final 2 PWM outputs. The goal should be to have as few differences between targets as possible.

Ideally, Frank will be broken down into a base with overlays so a whole new target won't be necessary at all and the only way that works is if the same pinouts are used when possible, instead of every person who makes one receiver for themselves getting their own thing we have to maintain without having the hardware to reference.

Have you built and tested this hardware yet?

**Comment by mariusdp** [comment]
> Any "DIY" build should also be able to use the same pin definitions as Frank 2400, instead of a completely new set of pin definitions. The VTX stuff isn't needed so those can be repurposed as the final 2 PWM outputs. The goal should be to have as few differences between targets as possible.
> 
> Ideally, Frank will be broken down into a base with overlays so a whole new target won't be necessary at all and the only way that works is if the same pinouts are used when possible, instead of every person who makes one receiver for themselves getting their own thing we have to maintain without having the hardware to reference.
> 
> Have you built and tested this hardware yet?

Will change to use Frank". Thank you...

> Have you built and tested this hardware yet?
Yes - used on a ranger but used only 9 channels (flaps, cam pan/tilt, 2 ch for flight modes with a FY41AP)
      *everything worked ok on a 2km radius - did not try to go further but I am sure can do a lot more*
Also, wanted to see how telemetry  changes when using E28:
             - with 12.5 sx1280 had telemetry through a few rooms in an industrial building (work place - 3rd room lost telemetry)
             - with E28 went couple of massive buildings and still got good signal

**Comment by mariusdp** [comment]
@CapnBry I have a clip I made to show a friend the telem if you want to see it let me know

**Comment by Ncerzzk** [comment]
Maintaining all the DIY build is impossible. 
While there will still be something different from the template(like Frank.json) in different DIY situations.
May be every DIYer could maintain the PIN.json themselves in the hardware page like https://github.com/ExpressLRS/ExpressLRS-Hardware/tree/master/PCB/2400MHz/RX_20x20/v2.0

and add a entry in [Configurator](https://github.com/ExpressLRS/ExpressLRS-Configurator) to chose the pin.json when building.

**Comment by pkendall64** [comment]
> Maintaining all the DIY build is impossible. While there will still be something different from the template(like Frank.json) in different DIY situations. May be every DIYer could maintain the PIN.json themselves in the hardware page like https://github.com/ExpressLRS/ExpressLRS-Hardware/tree/master/PCB/2400MHz/RX_20x20/v2.0
> 
> and add a entry in [Configurator](https://github.com/ExpressLRS/ExpressLRS-Configurator) to chose the pin.json when building.

In the hardware.html page there is the option to upload a json file. There is also the ability to download the current running json file so I feel that this PR is not really necessary.
Also I think it would be a good idea to add the json file to each DIY project in the hardware repository so it's easy for users.

**Comment by JyeSmith** [comment]
Closing.  PKs suggestion to maintain new DIY opensource hardware in the hardware repo is a good one.

**Pull request closed without merging**
