### PR TITLE
add 100mW output power for RX

### PR DESCRIPTION
**Pull request by cvetaevvitaliy**
Hi!
I need the 100mW receiver output power (that SX1276 chip supports) for telemetry. 
After analyzing the code, I found an error, the value 0x87 is not written to the RegPaDac register

ScreenShot 2023-08-24 at 10 52 29

I also changed the output power settings (100mW) for the all receivers (If it needs to be make in another PR, let's discuss it)
I tested target BETAFPV RX 900 with telemetry TX power 100mW, the power increased to 100mW, there is no overheating of the receivers

P.S. I ported source code form Semtech repo
https://github.com/Lora-net/LoRaMac-node/blob/master/src/boards/SAMR34/sx1276-board.c#L234

### CODE REVIEW

**Comment by pkendall64** [comment]
You are running the chip outside specs with this PR. If you are enabling 20dBm output then the duty cycle MUST be <1%. ELRS is more like 80% duty cycle. See section "5.4.3 High Power +20 dBm Operation" of the datasheet.
Long term use WILL damage the chip.

**Comment by cvetaevvitaliy** [comment]
> You are running the chip outside specs with this PR. If you are enabling 20dBm output then the duty cycle MUST be <1%. ELRS is more like 80% duty cycle. See section "5.4.3 High Power +20 dBm Operation" of the datasheet.
> 
> Long term use WILL damage the chip.

this is documented in the datasheet: out power +20dbm see picture.

Duty cycle for telemetry or for RC command?

**Comment by cvetaevvitaliy** [comment]
Even if you use the output: 15dbm (31.62 mW), do you see mistake in the source code? When using the PA_BOOST pin, the register RegPaDac:Ox4d must be changed, for correctly set the output power

**Comment by pkendall64** [comment]
At an 80% duty cycle per packet we'd have to limit the telemetry ratio to 1:64 to be within specs for the chip.
You referenced the data sheet, but neglected the sentence at the bottom and the 2 tables it references!
Screenshot 2023-08-25 at 8 28 51 AM

> Even if you use the output: 15dbm (31.62 mW), do you see mistake in the source code? When using the PA_BOOST pin, the register RegPaDac:Ox4d must be changed, for correctly set the output power

We don't need too update this register as the default value is correct for PA_BOOST 17dBm MAX.

> if you are so afraid of overheating, you can fix the correct setting of the output power to 17dbm (~50mW) for PA_BOOST pin and for everything more than 50mW make build option and write message warn to user, that this is at his own fear and risk, do not leave the receiver on the ground for a long time.

It's not about overheating, it's that the datasheet says quite clearly what the absolute maximum ratings are and we need to stay within those limits. You are more than welcome to maintain your own fork with these changes for your own purposes.

**Comment by cvetaevvitaliy** [comment]
> At an 80% duty cycle per packet we'd have to limit the telemetry ratio to 1:64 to be within specs for the chip.
> 
> You referenced the data sheet, but neglected the sentence at the bottom and the 2 tables it references!
> 
> Screenshot 2023-08-25 at 8 28 51 AM
> 
> 
> 
> > Even if you use the output: 15dbm (31.62 mW), do you see mistake in the source code? When using the PA_BOOST pin, the register RegPaDac:Ox4d must be changed, for correctly set the output power
> 
> 
> 
> We don't need too update this register as the default value is correct for PA_BOOST 17dBm MAX.
> 
> 
> 
> > if you are so afraid of overheating, you can fix the correct setting of the output power to 17dbm (~50mW) for PA_BOOST pin and for everything more than 50mW make build option and write message warn to user, that this is at his own fear and risk, do not leave the receiver on the ground for a long time.
> 
> 
> 
> It's not about overheating, it's that the datasheet says quite clearly what the absolute maximum ratings are and we need to stay within those limits. You are more than welcome to maintain your own fork with these changes for your own purposes.


you have a strange attitude when discussing with other open source developers... maybe close the repository ?

**Comment by JyeSmith** [comment]
Can you please share a pic of the rx outputting 100mW.

I have attempted this a couple of times and only measured an increase from the current 50 to 56mW.

**Comment by howels** [comment]
RXs with PA already exist, why not just use an existing RX?

**Pull request closed without merging**
