### PR TITLE
Fixing unit tests

### PR DESCRIPTION
**Pull request by pkendall64**
fixes the unit tests after update to PIO have now caused them to fail because it can no longer find header files in different libraries!

### CODE REVIEW

**Review by FOG-Yamato — APPROVED** [review]

**Comment by CapnBry** [comment]
Oh platformio. Automatically upgrades, every developer is using a different version. Every ~minor version~ release changes how it works.

I think the CRSF directory should be renamed devCRSF, as that's what I've been making everything conform to-- that devCRSF.h was the main header and CRSF.h is a support header for that library. As you can see that's why you also have to add device.h when adding CRSF.h, because devCRSF.h already has these in it, so those won't be needed. I think crsf_protocol should go into devCRSF as well, nothing else uses it without using crsf_protocol as well.

CRSF2MSP should get some sort of main header that includes the right things, and I guess be renamed to something unique so the two other headers (crsf2msp msp2crsf) can stay what they are.

Weird that POWERMGNT doesn't work. That one should work?

I think for 3.x we should get rid of most of these libraries and build our source tree like a proper source tree. These are not libraries at all as they all reach directly into the inter workings of the other libraries. It would save us the headache of PIO changing their library scan methodology every couple of weeks, and make builds a million times faster when it doesn't sit there for a full minute trying to work out the library dependencies.

**Comment by pkendall64** [comment]
I 100% agree that most if not all of our libraries are not libraries. They should be in the main codebase under functional areas.
This would, of course, be a massive change to the codebase, so it should be done fairly early in the cycle, but to too early as to cause headaches for ourselves with merging from maintenance and backports.

**Comment by pkendall64** [comment]
> Weird that POWERMGNT doesn't work. That one should work?

Yes, this one is really bothersome, and I agree is should just work!

I have managed to simplify this PR right back to the basics. I don't know why I couldn't manage this before?! I had tried about 3 times and ended up where I had before.
Seems the root of most the problems was that `targets.h` needed to be included in `options.h`.

**Comment by CapnBry** [comment]
haha ... (sighs) I love PIO but also I hate PIO.

We should probably remove redundant `targets.h` from things that include `options.h` as well but I care less about that than how clean this solution is. Do you want me to approve this now or wait until after 3.0 release when we're doing 3.1 dev? I'm not sure how our process works 😄

**Comment by pkendall64** [comment]
Either way is fine.

**Review by CapnBry — APPROVED** [review]
Let's get er out of the way then!

**Pull request merged**
