### PR TITLE
Switch Jumper TPro GPIO_PIN_DEBUG pins... mod for TPro Backpack

### PR DESCRIPTION
**Pull request by JyeSmith**
This will allow users to now add a Backpack to the TPro.  Just add the Backpack define to the Configurator and solder a rx you dont want to use inside.  The receiver rx pad is solder to the modules SP pad.

image

image

### CODE REVIEW

**Comment by pkendall64** [comment]
Funny, I noticed that pad sitting idly there the other day too!

**Review by pkendall64 — APPROVED** [review]

**Review by Meldinov — APPROVED** [review]

**Review by deadbytefpv — APPROVED** [review]

**Comment by zhoumigo** [comment]
WOW nice!

**Comment by AVIC621** [comment]
This means that when I use ExpressLRS-Configurator with master branch, I must use Manual mode and ADD -DUSE-TX_BACKPACK?      In ExpressLRS-Configurator 1.4.1 There is no “-DUSE-TX_BACKPACK” Options.   If i need use nightly ExpressLRS-Configurator ?
image

**Comment by JyeSmith** [comment]
Correct, you must use master branch and add the define manually.

**Comment by AVIC621** [comment]
> 

Need some help! master branch can not for build
image

**Comment by AVIC621** [comment]
> 正确，您必须使用 master 分支并手动添加定义。

Hi,Jye.  I Need some help! master branch can not for build
image

**Comment by AVIC621** [comment]
can not to work

image

**Comment by pkendall64** [comment]
That is not an up to date master as that error was fixed a few weeks ago in both master and 2.5 branches.

**Pull request merged**
