### PR TITLE
Add BETAFPV literadio3 target

### PR DESCRIPTION
**Pull request by wvarty**
Testing completed:

- Test log: https://docs.google.com/document/d/1u4EL7C9RiPojMh4jc83nSAH4tadTj0Xr8L29n2OI_z4/edit?usp=sharing
- Testing limited to ELRS
- No issues found with the internal ELRS module, except when using 500mW RF output. Power has been limited to 250mW in the target as a result.

### CODE REVIEW

**Comment by AlessandroAU** [comment]
all working as expected

**Review by AlessandroAU — APPROVED** [review]

**Review by CapnBry — APPROVED** [review]
I don't have this device but it compiles so SHIP IT, I assume the testing has all been completed to satisfaction if Wez had the test report and Sandro agrees.

**Comment by howels** [comment]
Is there an issue here or is the PR waiting for more feedback? Not clear if the Literadio3Pro is blocked by an issue or if people are just busy.

**Comment by wvarty** [comment]
> Is there an issue here or is the PR waiting for more feedback? Not clear if the Literadio3Pro is blocked by an issue or if people are just busy.

It _was_ waiting for a second approval so that it passes the merge checks, which only happened 13 hours ago.
Needs a release to be cut after merge, which still might take a few days.

**Pull request merged**
