### PR TITLE
Added otx-2.3.11 builds [Needs testing]

### PR DESCRIPTION
**Pull request by nik012003**
I've built the binaries from https://github.com/raphaelcoeffic/opentx/tree/mixer-scheduler-squash-rebase using this docker image https://github.com/vitas/opentx-docker-build. 
The only confirmed working build is qx7. All of the others need testing.

### CODE REVIEW

**Comment by AlessandroAU** [comment]
Did this fix the unstable UART connection or saw or is that still an issue?

**Comment by nik012003** [comment]
> Did this fix the unstable UART connection or saw or is that still an issue?

No, it didn't. It's probably an hardware problem that we need to fix in the r9 access.

**Comment by 0crap** [comment]
> I've built the binaries from https://github.com/raphaelcoeffic/opentx/tree/mixer-scheduler-squash-rebase using this docker image https://github.com/vitas/opentx-docker-build.
> The only confirmed working build is qx7. All of the others need testing.

Can you please recompile with the option "no-heli" checked?
Has always been the case.
I tested the QX7S and all my models now have a unwanted HELI tab.
Thx!

**Comment by nik012003** [comment]
> > I've built the binaries from https://github.com/raphaelcoeffic/opentx/tree/mixer-scheduler-squash-rebase using this docker image https://github.com/vitas/opentx-docker-build.
> > The only confirmed working build is qx7. All of the others need testing.
> 
> Can you please recompile with the option "no-heli" checked?
> Has always been the case.
> I tested the QX7S and all my models now have a unwanted HELI tab.
> Thx!

Here you go. 

[opentx-x7-noheli.zip](https://github.com/AlessandroAU/ExpressLRS/files/5792848/opentx-x7-noheli.zip)

**Comment by 0crap** [comment]
> > > I've built the binaries from https://github.com/raphaelcoeffic/opentx/tree/mixer-scheduler-squash-rebase using this docker image https://github.com/vitas/opentx-docker-build.
> > > The only confirmed working build is qx7. All of the others need testing.
> > 
> > 
> > Can you please recompile with the option "no-heli" checked?
> > Has always been the case.
> > I tested the QX7S and all my models now have a unwanted HELI tab.
> > Thx!
> 
> Here you go.
> 
> [opentx-x7-noheli.zip](https://github.com/AlessandroAU/ExpressLRS/files/5792848/opentx-x7-noheli.zip)

Awesome! Thx a lot.
Is it the ACCST version, which I need? (I guess so because there is no ACCESS in the filename.)

I think you can do "noheli" for all the radios, it was like that before.
But I leave that up to you to decide.

**Comment by nik012003** [comment]
> > > > I've built the binaries from https://github.com/raphaelcoeffic/opentx/tree/mixer-scheduler-squash-rebase using this docker image https://github.com/vitas/opentx-docker-build.
> > > > The only confirmed working build is qx7. All of the others need testing.
> > > 
> > > 
> > > Can you please recompile with the option "no-heli" checked?
> > > Has always been the case.
> > > I tested the QX7S and all my models now have a unwanted HELI tab.
> > > Thx!
> > 
> > 
> > Here you go.
> > [opentx-x7-noheli.zip](https://github.com/AlessandroAU/ExpressLRS/files/5792848/opentx-x7-noheli.zip)
> 
> Awesome! Thx a lot.
> Is it the ACCST version, which I need? (I guess so because there is no ACCESS in the filename.)
> 
> I think you can do "noheli" for all the radios, it was like that before.
> But I leave that up to you to decide.

yes, it's for accst radios. I'll rebuild them once I have some time, maybe I'll make a script to automate all builds...

**Comment by JyeSmith** [comment]
@nik012003 any chance of sneaking the T-Lite into this? or when you are free doing a separate build and PR?

https://github.com/opentx/opentx/pull/8230

**Comment by nik012003** [comment]
> @nik012003 any chance of sneaking the T-Lite into this? or when you are free doing a separate build and PR?
> 
> [opentx/opentx#8230](https://github.com/opentx/opentx/pull/8230)

Unfortunaly there is a conflict

**Comment by nik012003** [comment]
> @nik012003 any chance of sneaking the T-Lite into this? or when you are free doing a separate build and PR?
> 
> [opentx/opentx#8230](https://github.com/opentx/opentx/pull/8230)

Ok did it.
```
Build completed in 46.8 seconds.

Firmware file: /opentx/opentx-tlite-2.3.12.bin

WARNING: Unable to validate firmware image size
Firmware size: 292.91796875KB

```
[opentx-tlite-2.3.12.bin.zip](https://github.com/AlessandroAU/ExpressLRS/files/5847556/opentx-tlite-2.3.12.bin.zip)

**Comment by JyeSmith** [comment]
@nik012003 you legend!

I dont have the T Lite yet, but hopefully its not far away.  Thanks again!

**Comment by bjin** [comment]
I tried to flash `opentx-t16-2.3.11.bin` to my Jumper T16 Pro, and could confirm it's compiled without internal multi-protocol module support.

**Comment by llinass** [comment]
Is it possible to include radiomaster tx12 build also?

**Comment by JyeSmith** [comment]
@nik012003 Im finally testing the TLite binary.  For any rf mode selected I get 0:100.  So something is up with the syncing.

**Comment by JyeSmith** [comment]
Closing since we now have OpenTX nightlys with mixer.

**Comment by sendorm** [comment]
Do you suggest that the OpenTX Nightlies enable 500Hz mode for the t-lite. I can't even seem to find the default baud rate of the T-Lite.

**Pull request closed without merging**
