### PR TITLE
Support running unit tests on Windows

### PR DESCRIPTION
**Pull request by pkendall64**
I have made some minor changes to the native unit testing framework to allow unit tests to run on windows natively.

I've created a wiki page [Unit Testing](https://github.com/ExpressLRS/ExpressLRS/wiki/Unit-Testing) with instructions on how to setup platformio on windows to run the unit tests. Other platforms are pretty well supported without too much problem.

### CODE REVIEW

**Comment by JyeSmith** [comment]
Woohoo!

Ive added it under the wiki sidebar Testing heading so it doesnt get lost.

**Comment by pkendall64** [comment]
> Woohoo!
> 
> Ive added it under the wiki sidebar Testing heading so it doesnt get lost.

saweeet

**Review by cruwaller — APPROVED** [review]
great!

**Comment by CapnBry** [comment]
image
Do I need to say anything else? I installed the 64 bit version because I am awesome and it worked as well. Thanks for the documentation and code fix to make it work

**Review by CapnBry — APPROVED** [review]

**Pull request merged**
