### PR TITLE
Emax

### PR DESCRIPTION
**Pull request by EmaxModel**

### CODE REVIEW

**Comment by JyeSmith** [comment]
Since emax targets are already released, this could target the 3.x.x-maintenance branch and be included in the next bug release.

**Review by pkendall64 — APPROVED** [review]

**Comment by pkendall64** [comment]
@JyeSmith I cherry-picked and retargeted this PR over to 3.x.x

**Review by JyeSmith — APPROVED** [review]
Approved, but we should wait for Emax to review before merging.

**Review by EmaxModel — COMMENTED** [review]
Yes, hank you.

**Pull request merged**
