### PR TITLE
CRSF class cleanup op

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
This is aimed at cleaning up "a bit" so we can increase the readability and maintainability.

Also, I'll use the following clang-format on my changes:
```yaml
---
Language:        Cpp
BasedOnStyle:  Google
BreakBeforeBraces: Linux
BreakConstructorInitializers: AfterColon
AccessModifierOffset: 0
...
```

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Tested on R9M and DIY 900 (ESP8285), and against RC2.

**Comment by sfjuocekr** [comment]
Instead of removing debug functionality, could we instead add a define to enable debug output?

**Comment by raphaelcoeffic** [comment]
> Instead of removing debug functionality, could we instead add a define to enable debug output?

Sure, what do you miss? Do you something in particular?

**Comment by sfjuocekr** [comment]
Well, it is not that I miss something but the removed debug lines could have been stripped with an ifdef(DEBUG) for example?

**Comment by raphaelcoeffic** [comment]
> Well, it is not that I miss something but the removed debug lines could have been stripped with an ifdef(DEBUG) for example?

I asked for something specific, as I don't have the feeling I removed any debug at all. If you think this is the case, please point me at what is missing compared to the current version against which this is supposed to be merged. Or maybe I missed your point?

**Comment by VladimirP1** [comment]
What's the status of this?

**Comment by pkendall64** [comment]
It's got a 1.1 milestone, so it's slated to be merged into 1.1 when that starts!

**Comment by raphaelcoeffic** [comment]
> It's got a 1.1 milestone, so it's slated to be merged into 1.1 when that starts!

And as I see the conflicts, it looks like it will need some more love ;-)

**Pull request closed without merging**
