### PR TITLE
Simplify dynamic power logic

### PR DESCRIPTION
**Pull request by avsaase**
## Changes

- Remove the redundant logic for LQ-based power changes. Using just simple LQ thresholds is much easier to understand and tweak the settings of. It also leaves room to disable LQ-based power changes, something that long-range pilots might want to do. We don't have any fundamental RSSI<->LQ relationship so it's best to leave the RSSI logic as it was originally.
- Use non-averaged LQ for power changes. LQ is already an average over the last 100 packets and averaging it over a longer time period puts a lot of weight on packets that were transmitted a while ago and very little on the most recent packets.
- Reset the RSSI average when the `connectionState` goes to `disconnected` to avoid using old data when the connection comes back.
- Small changes to the sampling and LQ threshold.

## Other things
I think dynamic power can be a bit sluggish because it only updates when telemetry packets are received. When you start dropping telem packets, but not enough to trigger the `disconnected` state, dynamic power gets updated less frequently and keeps holding on to old data. I would like to change this to update on every expected telem packet but I still need to work out the exact logic for that.

If you guys don't want to take this PR for 2.2 then I'll update it later. Otherwise, I'll create a new PR if I have any improvements to share.

### CODE REVIEW

**Comment by AndreaCCIE** [comment]
Tested today: I can’t say if it's more responsive than the previous iteration from a user perspective, but it work fine

**Comment by CapnBry** [comment]
I disagree with these changes. The code checks every 4th instantaneous LQ reading to determine an incremental power change? Isn't that confusing that the LQ was below the threshold but the power didn't increase because it didn't happen to be on update No.4? We also can't compare the LQ value every time because I think the power output will jump all over as each update could change the power. I think the way of sliding the sensitivity limit using the avg LQ provides a much smoother settling than comparing against two hardcoded values "suitable for a general flying".

I'm going to put the do not merge tag on it for now to indicate this is shouldn't be merged until a consensus is reached.

**Comment by avsaase** [comment]
If we assume a telemetry ratio of 1:64 or above, then every LQ value we receive via telemetry also covers uplink packets that the previous telemetry packet already reported on. So if LQ was low on telemetry update 3, then it will also be low on update 4. The higher the telemetry ratio the more overlap there is. If you take an average over the LQ values you put much more weight on the old packets than the new ones (with a 4-point average and 1:16 telemetry ratio the older packets get four times the weight of the most recent ones!). I don't think this is desirable in and of itself but it also creates a second problem: those old packets very likely factored into the previous dynamic power update. This could get you into a situation where you increase power because LQ is low, more packets get through but your average is very slow to update so power could be increased again on the next update. 

The current code attempts to solve this by resetting the LQ average after every power update but then still uses five overlapping and partially pre-determined LQs building up the new average. Updating the power level every 4th telemetry packet without averaging at least gives some time for the old packets to drop out of the sample. (Now that I think of it, the LQ-based power updates could be changed to only update power after every packet that is at least 100 uplink packets after the previous update to really avoid this problem. )

I don't see the logic in adjusting the RSSI thresholds based on LQ (yes I changed my mind on this). We cannot quantify the relationship between LQ and RSSI so putting them together like this seems arbitrary. Why do 3 LQ points equate to 1dB RSSI change? The complaint about dynamic power in 2.0 was that LQ was allowed to drop too much before the RSSI-based power changes kicked in. Using configurable (not hard-coded) LQ thresholds is a very simple way for users to configure dynamic power and get the behavior they want.

**Comment by CapnBry** [comment]
The problem with just using the one LQ value and not an average is that you're assuming that one LQ packet is representative of the entire series (you say "if LQ was low on telemetry update 3, then it will also be low on update 4"). If that's the assumption, then we can also assume that the LQ value never changes, right? 🙃

The incremental increase / decrease code is not there to work with sudden changes, and is the "I term" of the logic. The idea is so slowly shift the power one step at a time until the "output" (the RSSI reported and now the LQ) stays in the correct range. It does not react fast to be able to compensate for suddenly flying behind things so using the avg LQ is fine. This part of the code is for dealing with a long range craft flying away and very gradually getting a better or worse signal.

As far as the frequency of power changes, there's no reason to enforce restrictions on the number of packets that we have to send before making a change, because we know there's at least one packet sent, and the LQ we receive after that is valid for the current conditions. When we get more data, we can make better decisions faster. It is true that the longer between the updates, the less valid the average becomes. To get around this we could timestamp the values and decay their contribution based on their age and not simply weight them all equally. That's incredibly complex though and again, this part of the system is the slow drift part of the system.

I should make sure that you're aware of the parameters of the LINKSTATISTICS telemetry too, because it isn't entirely clear from just looking at the TX's side. The RX attempts to allocate at least 2x LINKSTATS every 1024ms, so the dynamic power system is targeted at 2Hz update rate. It shouldn't be any _lower_ than that, unless the user is running lower telemetry ratio than recommended, in which case they can suck it. It can be higher than that if the telemetry ratio is higher, or if there's no ADVANCED TELEMETRY (packets from Betaflight) to send. In practice this is rarely the case since there's almost always more data to send than we have bandwidth for, so assume the "slow drift" of power is happening at most once every 2.5 seconds.

My system of adjusting the RSSI targets based on LQ is a simple way to try to adjust to noisy environments or a persistent partial obstruction. I feel that sliding the window is a more elegant solution than setting hard limits like 85 LQ raises the power always but 86 LQ raises the power never. Adding (100-86)/3=+4 dBm to the thresholds is already a theoretical doubling of power, but only if that would push the RSSI out of the acceptable window, preventing a screaming match when the LQ is low due to congestion/collisions. With a hard LQ limit of 85, then theoretically any time you have ~12 pilots with their transmitters on, all of them will go to **FULL POWER** due to collisions, bleeding into adjacent FHSS channels and causing lower LQ overall.

**Comment by SunjunKim** [comment]
Firstly I'd like to thank @avsaase for your attention and efforts in this PR.

After some extensive testing and analysis, we've decided to get rid of RSSI in DP logic. The inconsistency of RSSI from RX LNA is the main source of error in the previous approach, which made the logic complicated.

In the future version, the DP logic will be completely rewritten from the scratch based on SNR for one-step inc/dec and LQ only for panic bump-up -- which will greatly simplify the logic. Unfortunately, this will invalidate the base code of this PR as well.

I'll close this PR for now, but thanks again for your interest in this project.
Please visit the revised DP logic later, and please share your opinion again.

**Comment by SunjunKim** [comment]
FYI: 
The new SNR-based logic is being tested here:
https://github.com/CapnBry/ExpressLRS/tree/dynpower-snr

**Comment by avsaase** [comment]
Cool, but what about SNR not being reliable when above zero?

**Pull request closed without merging**
