### PR TITLE
Move sync channel to middle of the band

### PR DESCRIPTION
**Pull request by cruwaller**
Sync channel is set currently to lowest edge of the bands (frequency index 0) which is not the most optimal location when compared to transmitter antenna tuning. Generally, antennas are tuned to middle of the band which means the best power output is on the middle.

Purpose of the PR is to move sync channel to middle of the band ( `num_of_frequencies / 2`) to maximize sync channel output power. This should help to recover link in case of link lost.

### CODE REVIEW

**Comment by cruwaller** [comment]
@JBKingdon ping. This effects to your handset as well. 

@phobos- this will also effect to https://github.com/betaflight/betaflight/pull/10788 . I can open a PR to your branch to align it accordingly.

**Comment by JBKingdon** [comment]
Wouldn't it be easier to keep index 0 for sync and just set FHSSfreqs[0] to whatever frequency you want?

**Comment by cruwaller** [comment]
Sure it would be easier. 
I think it is better to keep freqs in order. Then we can easily adjust sync channel e.g. based on UID to avoid overlapping with other users.
+ freq swap sounds like a hack 😄

**Comment by CapnBry** [comment]
> Wouldn't it be easier to keep index 0 for sync and just set FHSSfreqs[0] to whatever frequency you want?

That would involve reordering the list of frequencies, and ideally we would generate this list on the fly as needed with a START + SLOT * STEP instead of storing them in the data segment. 

I'd say there's no reason to store the sync channel in a variable though since it never changes. If you're doing the optimization of making it uint_fast8_t then optimize it by making it compiled in instead of a variable. Other than that, it looks good. I'll give it a test soon.

**Comment by cruwaller** [comment]
@CapnBry i was thinking to modify wync channel based on UID later. It is not part of this PR. 
That would help to avoid interference with other users.

**Comment by CapnBry** [comment]
> @CapnBry i was thinking to modify sync channel based on UID later. It is not part of this PR.
> That would help to avoid interference with other users.

Roger that. I'll test this out in the next day or so, but it looks good.

**Comment by AlessandroAU** [comment]
tested on both 900mhz and 2.4ghz

**Comment by hydra** [comment]
With regards to the everyone using the same sync channel, and potentially using the UID to modify the sync channel, does it make sense to avoid using the low and high frequencies, for antenna tuning reasons, rather than choosing a sync channel that could be any frequency from range.

i.e.

Lowest 33% of Range | Sync Range (Optimal Power) | Highest 33% of Range
------------ | ------------ | -------------
Not used for Sync | Sync frequency based on UID | Not used for Sync

**Comment by CapnBry** [comment]
I know this is already merged but I verified that my receivers allocate the middle channel to be sync channel and flew several packs this morning with this PR integrated. Does what it is supposed to, I approve!

**Comment by cruwaller** [comment]
@hydra yes, something like that. Need to find a good range for the sync freqs and most likely limits per domain.

@CapnBry thanks for testing this!

**Comment by cmanley** [comment]
@hydra 
Please excuse my humble attempt at writing C code, but would this semi-pseudocode achieve what you described above ?
In https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lib/FHSS/FHSS.cpp#L290 
replace ```sync_channel = FHSS_FREQ_CNT / 2;``` with...
```
if (FHSS_FREQ_CNT < 3) {
   sync_channel  = 0;
}
else {
   unsigned int trim_cnt =  FHSS_FREQ_CNT / 3;  // trim outer thirds of frequency range
   unsigned int candidate_cnt = FHSS_FREQ_CNT - (2 * trim_cnt);  // same as trim_cnt if divisor above is 3
   unsigned int candidate_offset = rand() % candidate_cnt; // assuming srand() already called
   sync_channel = trim_cnt + candidate_offset;
}
```
https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lib/FHSS/FHSS.cpp#L290

**Comment by hydra** [comment]
@cmanley yeah, something like that.  thanks for following up on this idea too.

**Comment by cmanley** [comment]
@hydra Perhaps even better is to perform a short listen on all candidate channels and choose 1 with the least noise. But how to do that is beyond my scope of knowledge of ELRS.

**Comment by hydra** [comment]
@cmanley not sure about that because they would probably still all pick the same sync channel on power up, makes collisions less likely I would thing.  i.e. power up rx 1, listen on X, X is quiet, X = sync.  power up rx 2, listen on X, X is quiet, X = sync too...  also the TX would need to tell the RX on what to listen anyway right?  Using the bind id/code as a seed gives both the TX and the RX a way to choose the same sync channel, which they both need to agree on.

I don't remember the bind process, but when an RX is unbound it must listen on a set frequency.  So in IIRC only /after/ bind the sync frequency can be different from the bind frequency.

**Comment by CapnBry** [comment]
There should be very little advantage to having the sync channel be different based on the UID. In theory, every channel has an equal chance of being coexisted-on (interrupted by another transmitter) so the sync chance for a _single_ new receiver coming online would be equal regardless of the channel. The only difference would be if there are multiple receivers coming online at the exact same time (so the sync is coming from each TX at the nearly exact same time). That's an insanely unlikely event, but an advantage if that were the case.

The disadvantage is that it only works for binding phrase users. A user can not just bind a new RX to their bind-phrase-using TX since there's no guarantee they will have the same sync channel. This means there needs to be a sync channel AND a binding sync channel. This is a small complexity, but due to the incredibly low benefit of having multiple sync channels, to me it makes more sense to just not have multiple sync channels. Even at the low complexity, the benefit to complexity ratio just isn't high enough to justify adding more code to support it.

We are also looking to use the bind channel as sort of a "version lockout". There's no protocol version in the OTA transfer, so the only way to block users from running a 3.0 TX against a 2.0 RX is to prevent them from syncing with each other. I mean there can be other ways to do it, but I thought just shifting the sync channel is the quickest way to make them incompatible. If we spread the sync around then something else will have to be done to prevent version mismatch.

**Comment by hydra** [comment]
@CapnBry Interesting thoughts, thanks for taking the time to think about it.  I conculde that your assessment is likely must more informed that my idea.

With regards to the protocol version in the OTA transfer, are you referring to just the sync packets?  Should that be addressed as a 2.0.x update and the issue tracked somewhere else other than here so that when 3.x is ready fewer people would be affected?

**Pull request merged**
