### PR TITLE
Guard RF mode changes while armed

### PR DESCRIPTION
**Pull request by JyeSmith**
RF mode changes can cause the link to drop, and Ive seen wing guys doing this mid flight :grimacing:

This PR ruins your fun and only allows changes while disarmed.

### CODE REVIEW

**Review by deadbytefpv — DISMISSED** [review]
Tested on a NamimnoRC Flash OLED
Works pretty well with a brief bench test.

Bye Packet Rate Roulette. "Ivan" will miss you.

**Comment by CapnBry** [comment]
I am against this concept for two reasons

1) If I need to change the packet rate, let me change the packet rate. Restricting me from performing a function is unnecessary and will instead lead to taking an even riskier path if directly restricted. Oh I can't change while armed and I'm flying? Well I'll just disarm in flight to make the change and rearm. That is exactly what is going to happen and you've not prevented the person from changing rates in flight, you just made it more of a gamble.

The switch mode is different, because the switch mode change does not inherently break the connection like changing rates does, so it must be done while disconnected entirely to prevent a mixed interpretation of the RC data. Packet rate changes do not have this problem.

2) IsArmed needs to die. It was in the code for the very specific purpose of NO_SYNC_ON_ARM, where it is still in use, but no other subsystem should be checking the armed state. No other RC link has this concept of armed vs disarmed, why should it, as the majority of RC models don't have an armed state! As we expand into fixed wing PWM and Ground RC, those things don't have arming so it becomes "I can't change rates with my flaps down" and "I don't have any switches on my ground RC controller?". Eliminating the IsArmed crutch should be a priority, not expanding it.

I keep trying to refute the argument that "ExpressLRS is just for quads" but denying that becomes implausible as more things become tied to this concept that only quad / fixed wing flight controllers have.

**Comment by pkendall64** [comment]
I think we should disallow changing the packet rate in flight, as it is not guaranteed to work and not supported by the devs.
If a we allow it to be done (like it currently is) then we continually get questions as to why it doesn't work as expected, so if we disallow it when armed and a user decides to disarm mid-flight to change it then they have actively decided thats what they want to do.
Personally I think it should not be allowed to change once it'c connected to the RX!

**Review by pkendall64 — DISMISSED** [review]

**Comment by CapnBry** [comment]
Yeah I find it to be really annoying to have to unplug to change a setting, and there's no consequence to changing it normally. It would also make testing a fucking nightmare. I'll say it again, it would fucking suck. Fucking suck to have to unplug and replug and wait for rate cycling every fucking time I want to try something else, as I already spend a ton of time testing things. Fuck that solution. Fuck it right in its fucking face. 🤣 Yes all those expletives are necessary.

We put a lot of effort into making it change somewhat seamlessly and the fact that it generally works is what has lulled everyone into thinking it just works all the time. It certainly would not if the LQ is not 100% though, so maybe we could teach people that? We could make it so that the TX stops transmitting for 3 seconds after every change, so people know it is actually disconnecting every time they change that setting. That kinda sucks though because you don't know if it actually changed or is still locked on the old rate, and you have to wait for 5 seconds or 10 seconds to know it didn't work.

**Comment by pkendall64** [comment]
> Yeah I find it to be really annoying to have to unplug to change a setting, and there's no consequence to changing it normally. It would also make testing a fucking nightmare. I'll say it again, it would fucking suck. Fucking suck to have to unplug and replug and wait for rate cycling every fucking time I want to try something else, as I already spend a ton of time testing things. Fuck that solution. Fuck it right in its fucking face. 🤣 Yes all those expletives are necessary.
> 

Wow, Mr Sweary-pants! 😆 

> We put a lot of effort into making it change somewhat seamlessly and the fact that it generally works is what has lulled everyone into thinking it just works all the time. It certainly would not if the LQ is not 100% though, so maybe we could teach people that? We could make it so that the TX stops transmitting for 3 seconds after every change, so people know it is actually disconnecting every time they change that setting. That kinda sucks though because you don't know if it actually changed or is still locked on the old rate, and you have to wait for 5 seconds or 10 seconds to know it didn't work.

So, are you saying just leave it how it is now? Or don't allow while armed? I know you hate the armed state on the TX/RX, but you know theres a shit-ton of stuff connected to that knowledge.

**Comment by CapnBry** [comment]
> So, are you saying just leave it how it is now? Or don't allow while armed? I know you hate the armed state on the TX/RX, but you know theres a shit-ton of stuff connected to that knowledge.

I would prefer it not be tied to the armed status, and left as it is would be the best solution for me 😁 Having so much stuff tied to the Arm status is not a reason to tie more stuff to the armed status. We have to stop somewhere and start going the other direction if we ever want to unwind it instead of just saying "It sucks, so let's just make it worse".

If that's not good enough, then I would think HARD breaking the connection when the rate changes, with a 3s TX dead time so it always says "Telemetry lost" on every switch might be a helpful indicator that teaches the user the connection always goes down when you change it might be a happy medium. I'm open to other ideas that don't require going back and forth between the model and the handset just to make a change or using Armed status though.

**Comment by JyeSmith** [comment]
Do we want to consider allowing rate changes but maintain a warning?

A 3s break will also suck during development.

**Comment by CapnBry** [comment]
Well I am for just leaving it the way it is. 😀 

Just doing a warning if connected (like "Enable WiFi" does) could be acceptable, but the warning message has to be like 15-20 characters at the most because that's all that fits on the B&W screens. I'm not sure how much warning you can get in that space. Even the cryptic "Disconnect to change?" won't fit.

**Pull request closed without merging**
