### PR TITLE
Adds Region to Web & Lua

### PR DESCRIPTION
**Pull request by maybenikhil**
Can be changed to more specific, but this will work with all screens. See #1136

### CODE REVIEW

**Comment by maybenikhil** [comment]
will require updates once #1161 is merged

**Comment by CapnBry** [comment]
> will require updates once #1161 is merged

Why not just make it support it now? The define name is already known to be `Regulatory_Domain_EU_CE_2400`.

**Comment by maybenikhil** [comment]
Will update it to work as such.

**Comment by CapnBry** [comment]
This works great apart from the fact that the branch name is longer than a version number so it flows over into the SHA on B&W. Tested with ISM2G4 and FCC915.

Here's the next problem, that the webui should also have this information :) That's in build_html.py, so now the challenge is that there's a lot of code to process the user_defines and super_defines and then use that to get the domain, so it isn't simple to just move `get_regulatory_domain` to elrs_helpers.py since more than just that function needs to go.

**Comment by maybenikhil** [comment]
For the first bit we could just display the region and not the freq (because the frequency should probably be known to the user) so: AU, FCC, EU... etc

For the second bit, could we just dump the regulatory domain to a temp file or is that too bad practices

**Comment by CapnBry** [comment]
ha HA! I said you were done but I came back at you again. Since the reg domain is now stored in the env, it probably should not have the leading space on it that was used when it was converted to ascii immediately. The only place this is apparent is in the firmware.bin download where it has two spaces in the filename (the webui has two spaces too but it is HTML so they are condensed to one). Either the space needs to be removed in build_html.py or added separately in build_flags.py, I went for making it not have the space in the env. I can push this change if you want or you can do it yourself, let me know.
```
diff --git a/src/python/build_flags.py b/src/python/build_flags.py
index 7c691d37..8db1fa33 100644
--- a/src/python/build_flags.py
+++ b/src/python/build_flags.py
@@ -90,15 +90,15 @@ def version_to_env():

 def regulatory_domain_to_env():
     regions = [("AU_915", "AU915"), ("EU_868", "EU868"), ("IN_866", "IN866"), ("AU_433", "AU433"), ("EU_433", "EU433"), ("FCC_915","FCC915"), ("ISM_2400", "ISM2G4"), ("EU_CE_2400", "CE2G4")]
-    retVal = " UNK"
+    retVal = "UNK"
     if ("_2400" in target_name or \
         '-DRADIO_2400=1' in build_flags) and \
         '-DRegulatory_Domain_EU_CE_2400' not in build_flags:
-        retVal = " ISM2G4"
+        retVal = "ISM2G4"
     else:
         for k, v in regions:
             if fnmatch.filter(build_flags, '*-DRegulatory_Domain_'+k):
-                retVal = " " + v
+                retVal = v
                 break
     env.Append(REG_DOMAIN = retVal)

@@ -109,7 +109,7 @@ def get_git_sha():
     return string_to_ascii(env.get('GIT_SHA'))

 def get_ver_and_reg():
-    return string_to_ascii(env.get('GIT_VERSION') + env.get('REG_DOMAIN'))
+    return string_to_ascii(env.get('GIT_VERSION') + " " + env.get('REG_DOMAIN'))
```

I tested all the existing domains and they all were indicated properly on the handset, webui, and firmware.bin apart from the extra space so we're good to go after getting that space out.

**Review by CapnBry — APPROVED** [review]

**Review by pkendall64 — APPROVED** [review]

**Pull request merged**
