### PR TITLE
Radio GPIO optimisation

### PR DESCRIPTION
**Pull request by pkendall64**
Whilst debugging a problem with tachometer readings from PWM controlled fans I found that I was getting "TX_DONE" Timeouts. i.e. the SX1280::TXnb() was being called before the previous TX had completed. This was causing problems where the radio would lock-up (i.e. telemetry lost and no re-connection to RX) and continue sending packets on just one frequency.

I have combed through the code and found that from 2.5 to 3.0 we have significant changes with dynamic pin assignments (Unified ESP targets) and Dual Radio support which have each contributed extra code and therefore more time to the setup of sending radio packets.

This PR performs some optimisation around the SPI calls in the `IsrCallback()` and also in the GPIO calls to enable RX or TX and which (if multiple) is sending. This has reduced the amount of time setting up, giving more time for the TX to happen and allowing it to complete before the timer executes and tries to start another TX cycle.

There are 2 commits in this PR, the first is optimisation that works for all platforms, the second (maybe more contentious) is specific to ESP32 where we can calculate the direct SET/CLR register settings at initialisation time and apply those "in one hit" at the time we need them.

### CODE REVIEW

**Comment by robustini** [comment]
@pkendall64 nice shot!
Do you think there may be a correlation with the problems in #1686?

**Comment by pkendall64** [comment]
> @pkendall64 nice shot! Do you think there may be a correlation with the problems in #1686?

I don't think so because the STM32 targets are built only with the code that is specific to the target vs the ESP based devices which have all the options on and only execute the ones specific to the target at runtime.

**Comment by pkendall64** [comment]
I have reverted the changes to IsrCallback as discussed with @JyeSmith and have also implemented specific direct register control for ESP8266/85 as well.

**Review by JyeSmith — APPROVED** [review]

**Comment by JyeSmith** [comment]
Here is master vs this PR.

On a diversity rx, DIO1 is high for about 90us on master and 59us with this PR.

image

image

**Comment by JyeSmith** [comment]
I just put a dozen packs through this PR without issue.  Looking good.

**Review by schugabe — APPROVED** [review]

**Pull request merged**
