### PR TITLE
Support 16 channel CRSF

### LINKED ISSUE #2363: crsf output on ch 15-16 dont work
## Current Behavior
on 16 ch, in sbus no problem, but in crsf output ch 15 and 16 are not working they are stable at 1811 

## Steps to Reproduce
set the protocol to 16ch and look at the output

https://www.youtube.com/watch?v=CAHO2vdnPrA

i got a kind of way to test it here the output debug from the receiver look at the 2 last bit they stay the same never change 
https://user-images.githubusercontent.com/378637/261110162-82850554-0d4b-4442-b783-720731683b37.png

im trying to bring elrs to plane guy's i made a pcb to get 16ch pwm from oxs platform like the sbus thing, i try to get elrs to the next level, all big compagnie sit on there ass for too long it is the best link that i want to make to the next level to everybody , big plane guy need this too ther servo at 333hz will be drive for the first time at the speed they are made for....
 if some one can take a look at why i cant get the ch 15 and 16 to work it will help a lot ,  from what i see its the rx that dont send the 15 and 16 on elrs but on sbus its perfect

### PR DESCRIPTION
**Pull request by pkendall64**
Fixes #2363 

Link stats packet for RSSIdBm and LQ have been around for some time. So we can just send the channel data out on the channels and remove this "hack" that was there for older versions of FC software.

Betaflight 4.3.0
iNav 2.6.0
Ardu 4.1.0

### CODE REVIEW

**Review by secretman28 — APPROVED** [review]
tested on an actual 16ch expander work as it should  and test on betaflight everything act as normal lq rssi

**Review by JyeSmith — APPROVED** [review]

**Comment by gjhaynes** [comment]
This is great news Paul. Thanks so much for providing this enhancement.

**Review by secretman28 — APPROVED** [review]

**Review by wvarty — APPROVED** [review]

**Comment by secretman28** [comment]
tanks to every one that help my project i really think it will help a lot to bring more plane pilot to use elrs
and a special tanks to pkendall64, i took some of his time to proof my point and show it was doable, and he help me complete my project again you deserve a big big tank's and really apreciate your help

**Comment by CapnBry** [comment]
For those like me who were like "_what?! we already support 16ch CRSF_" it was working in 3.0.0-3.2.1 but was broken by the refactor to support SBUS where the code that supported both LQ/RSSI in CH15/16 **and** CH16 mode was removed.

**Comment by gjhaynes** [comment]
Fascinating! Was it a user-configurable option back then? Clearly you can’t have both at the same time.

**Comment by pkendall64** [comment]
It was sort of configurable. When you selected 16channel mode it didn't do the RSSI/LQ overwrite.

**Comment by GTFreeFlyer** [comment]
Hi, just found this thread after not getting channels 15 and 16 to work.  I'm using the Ranger external module and RP1 receiver, both on the latest firmwares.  I'm still not getting Ch 15 and 16 to come through.  Is there a setting I missed?

Also, on another note, when I go into the ELRS lua tool to access my receiver settings, I see nothing for setting up the failsafe. Is it not something I can do with the RP1 rx?

Thanks.

**Comment by ot0tot** [comment]
> Hi, just found this thread after not getting channels 15 and 16 to work. I'm using the Ranger external module and RP1 receiver, both on the latest firmwares. I'm still not getting Ch 15 and 16 to come through. Is there a setting I missed?
> 
> Also, on another note, when I go into the ELRS lua tool to access my receiver settings, I see nothing for setting up the failsafe. Is it not something I can do with the RP1 rx?
> 
> Thanks.

Please use the ELRS Discord for support help: https://discord.gg/dS6ReFY

**Pull request merged**
