### PR TITLE
6/7-bit (64/128 pos) HYBRID_SWITCHES_8

### PR DESCRIPTION
**Pull request by CapnBry**
This PR expands the `HYBRID_SWITCHES_8` implementation to 1x 2-pos switch (AUX1, 1-bit) and 7x 6/7-bit (AUX2-7) switches. It does so by removing the switch index from the packet and relying on the Nonce to be synced with the transmitter. The resolution of the high res switches is determined by the Telemetry Ratio, where anything less frequent than 1:8 gets 7-bit and 1:2 and 1:4 ratios get 6-bit.

In addition it adds the `uplink_TX_power` field in some newly unused bits. This field is only used in iNav OSD currently.

No changes to OTA size, coding parameters, effective air rate, or any other performance compromise was made to achieve this. However, the "switch priority" (where if a switch changes, it is sent on the next packet) has been removed. This means there may be a delay of up to 7 packets before the new switch is sent, but, I mean, c'mon, 7 packets is 14-140ms. The AUX1 switch is still sent every packet so ARM status is not affected.

## OTA behavior changes
The low 2 bits of the Nonce is now added to the CRC by the transmitter on non-SYNC packets (the sync already has the whole nonce in it). This was added to provide a guarantee that the Nonce is correct since it is used to determine the switch index that's represented in the packet. This can create a **new Sudden Failsafe situation** if the RX and TX Nonces do not match where previously we'd instead go to a 75/50/25 LQ situation. This was plucked from @pkendall64's #716 (Nonce Recovery) PR, and @JyeSmith said we had 7 bits available in the CRC from our discussion of this feature back in May so this should not affect our CRC's performance [Discord Discussion](https://discord.com/channels/596350022191415318/744445841779064863/847234283143430244)

## Switch Encoding Changes
* Remove SwitchIndex from switch encoding, saves 3 bits
* Remove the Telemetry State bit from every packet, and only send it every 8 packets to save 1 bit. Normally, we send the "ACK" bit hundreds of times between each telem interval and really it is only needed once. At telemetry rations of 1:2 and 1:4, the telemetry bandwidth would be effectively crippled waiting for the ACK, so at these ratios the bit is sent every packet again.
* Use the 6/7 available bits to send the switch, or maybe we can almost call it channel, data

The extra slot that would be taken by AUX1 is used to transmit the telemetry ACK bit and `uplink_TX_power`. We don't need to send that so often, so if anyone has any values they want to uplink to the RX of 6 bits or less, there's more space available. We have roughly 16 "slots" of 6 bits and the TX power can take just one instead of all of them.

## Caveats
The telemetry ACK bit used to be sent every dang packet, meaning there were many opportunities for the ack to get to the RX before the next Telemetry send. Because it is only sent every 8 packets now, there's a higher chance that the bit won't make it to the RX and the RX will retransmit the previous telemetry packet, thus reducing the effective telemetry bandwidth.

## Docs
I haven't written any of the documentation yet, but this will reduce a lot of the existing documentation because 2-pos, 3-pos, and 6-pos switches work (although the center position is slightly off 1500 now) and they almost behave like real channels now so  people will be less confused by them.

## Testing
* Tested Team900 ES900TX / R9Mini (Betaflight) at 200/50Hz and 1:64 1:2 ratio
* Tested Team2.4 FM30 TX / FR Mini RX + EP2 RX (iNav) at 500/250/50Hz and 1:128, 1:64, 1:8, 1:4 ratio. 

## Conflicts
This conflicts with #750 (Simplify RX Config) and #538 (CRSF refactor) and #716 (Nonce recovery). I fully support those PRs so I'd recommend merging #750 for sure first and #538 if we can still, and I'll update this PR to deal with the conflicts. #716 I'm all for too, but I think there's still some work going on with the SPI RX part of that so this can go first and I'll fix that PR instead.

### CODE REVIEW

**Comment by JBKingdon** [comment]
This is very creative! Are we going to keep the existing switch behavior though? Personally I wouldn't choose the new function at the cost of increased fail-safes.

**Comment by CapnBry** [comment]
We will not be keeping the old switch behavior. There's only failsafe risk if the RX and TX get out of sync, which is not supposed to happen. If that happens, then we should fix that, not ignore enhancements because something that shouldn't be happening is.

**Comment by JBKingdon** [comment]
Yet we know it does happen and we haven't been able to fix it yet. I guess you mean we won't merge this change until we've proven that desync isn't possible. Sounds good to me.

**Comment by CapnBry** [comment]
I don't think anything is blocking this from being merged. I'd have to be convinced that the 75/50/25LQ bug is still a thing in mainline ELRS, because is it?

**Comment by JBKingdon** [comment]
The report by avsaase in #bug-reports sure looks like it's a desync. I don't recall us finding a definitive cause of why desyncs were happening, so I'm not sure how we can be confident that we actually fixed the problem rather than just made it less likely.

**Comment by CapnBry** [comment]
I fixed a bunch of contention problems during the RCs that would be directly responsible for causing the desync so I believe it is fixed. I've not been able to reproduce it for months.

avsaase's 42-45 LQ seems like a weird number, considering he flew within a meter or two of himself and it didn't go above 45 LQ. On his way out he had 100LQ for quite a while so I don't think it was 50 minus some lost packets.  He also said there was a huge delay in the mode switch doing anything, which should not be affected by a Nonce mismatch. Finally, he was able to reset the connection with the handset by switching rate, which means SYNC packets were getting through, which means that a Nonce reset would occur once every ~4 seconds which would have fixed the offset if there was one. It just doesn't show any signs that it was a Nonce mismatch.

**Comment by JBKingdon** [comment]
Those sounds like good arguments. I would have thought that switching rate would cause a full link drop and hence a new connection to be established, which still sounds consistent with a desync. Nonce mismatch implies a consistent and repeating pattern of dropped packets which may well cause a hybrid switch change to be greatly delayed. The odd LQ number he reported seems to be consistent with a 50LQ desync while running with telemetry enabled - the telemetry packets would get dropped once the tx and rx and disagreeing on the nonce. His LQ dropped immediately after a low LQ blip - again consistent with historical desync behaviour. Maybe we have very different ideas about how desyncs behave but it all sounds exactly like desync to me. On the flip side, it's the only report we've had in recent times, so maybe you're right and it's something else and desyncs are a thing of the past. I still don't think we should be trading reliability for features.

**Comment by CapnBry** [comment]
* Telemetry ratio of 1:8 at 150Hz would mean the max LQ should be around 47-48, so 45 still seems low.
* He had `LOCK_ON_FIRST_CONNECTION` on, so it would have been impossible to switch rates without replugging the RX, so 100% for sure still getting sync packets. It was not a Nonce mismatch if it was still getting sync packets.
* The LQ was 100, went down to 70ish then went back to 100, down to 70ish, then down to 40ish. That's would be a single Nonce desync, followed by recovery (which would cause a brief RXLOSS due to going back to tentative), then another Nonce desync, followed by a THIRD Nonce desync. Something that almost never happens to anyone happening three times in a row with a resync in the middle? Doesn't seem possible.
* If you believe the 50LQ bug is still a thing on 1.0, then we should probably create an issue for it and not be doing forensics on a single video in this PR.

I don't want to trade reliability for a feature either, but I believe the Nonce to be reliable at this point.

**Comment by JBKingdon** [comment]
Ok, I've made my position clear.

**Comment by JyeSmith** [comment]
This should make a lot of wing/gimbal users happy!

Im fine with this, and I would even be happy to scrap the 1bit switch option in the future BUT after we ask the community.

I also share James concerns but you make some good points.  Lets get this merged and then add some debug logging like my hack job linked below, or something similar.  We can then get a heap of logging done before v1.1.

As part of the AIO changes are you also able to look at the removal of multiple nonce location increments?

https://github.com/ExpressLRS/ExpressLRS/commit/79188a6acf60fa5c057fa32703f117d4b060b863

**Comment by NemesisXB** [comment]
It seems to have been decided allready. But I would have voted to have both the old and the new so I can select which one I want to use at build time. I understand where and why this is required but as a quad only pilot, it seems I am loosing more than I am gaining with this change. With regards to the desync, you know murphy... If it can happen, it will happen.

**Comment by hydra** [comment]
Cool to see my idea of removing the switch index from the packet implemented! Good work chaps!

**Comment by CapnBry** [comment]
This PR has been superceded by #821 "Wide Switches Mode" a whole new mode to alleviate the concerns of those who were worried about the Nonce sync requirement and maintain compatibility with SPI receivers.

**Pull request closed without merging**
