### PR TITLE
Add Analog VBAT to RX / PWMP7

### PR DESCRIPTION
**Pull request by CapnBry**
Enhancements for PWMP receivers:
* Adds a new device devAnalogVbat which is used to measure and send VBAT telemetry from the RX's analog input
* Adds support for 7ch PWMP output using BUSY and RST pins. **FOR EXPERIMENTATION ONLY** using RST seems to be unreliable, I'd like to see if we can make this work eventually, since it is just two pio targets (do not add to Configurator).

### Analog VBAT
This device is for any receiver that supports analogRead, and simply accumulates 5 samples over 500ms, throws out the highest and lowest and averages the rest, dividing by `ANALOG_VBAT_SCALE`. The default for PWMP target assumes the resistor values from [crteensy's PWM RX](https://github.com/crteensy/ELRS-8285-1280-5xPWM) on the ADC input of an ESP8266, which are 24k/1k. (EDIT: Although 34K has been suggested as a better value since 24k isn't enough for full 6S, and 34k is good up to 8S HV with only a 0.01V loss in precision)

The measurement and reporting interval may need some tweaking on this, but at the packet is 14 bytes so it takes like 3 seconds to send at 500Hz 1:128. I figured updating every 500ms was good.

Why not report cell voltage? The problem with report_cell_voltage is that CRSF protocol sucks donkey spit because there's only one decimal place for VBAT precision (but supports up to 6553.5V because of course TBS always has the best ideas). If you want two digits of precision you're going to have to take that request up the chain to TBS and everyone else everywhere that displays a VBAT value (or use ANALOG_VBAT_SCALE / 10).

### Up to 7ch output for PWMP
This also adds a new target `DIY_2400_RX_PWMPEX_via_XXX` which supports up to 7ch PWM output on ESP-based RX. The number of outputs is determined by the `PWMP_CH_CNT` define. (Note that GPIO 1, 3 are removed if compiled with DEBUG_LOG)
|Channels|GPIO|Remarks|
|---|---|---|
|5ch|{ 0, 1, 3, 9, 10 }||
|6ch|{ 0, 1, 3, 9, 10, 5 }|BUSY no longer connected to SX128x, uses BUSY emulation|
|7ch|{ 0, 1, 3, 9, 10, 5, 2 }|RST no longer connected to SX128x, needs additional capacitor to delay SX128x startup|

### CODE REVIEW

**Review by pkendall64 — APPROVED** [review]
Looks good.

**Review by StonedDawg — APPROVED** [review]

**Comment by cynfewl** [comment]
@CapnBry does this also work on the commercial PWM receivers that have an exposed ADC pad, like the JHEMCU ELRS-2G4-P?

If it does work, do you have any information on how to connect the resistor in order to get this working?

**Comment by CapnBry** [comment]
> If it does work, do you have any information on how to connect the resistor in order to get this working?

Yes it should work with anything that lets you pump in a voltage to the ADC. I do not know how the JHEMCU receiver is wired up (since that is one of the few unsupported ELRS RX due to them never having any contact with us), but VBAT should be wired in through a resistor divider:
www circuitlab

Where:
* VIN = VBAT
* R1 = 24k
* R2 = 1k
* C1 = 0.1uF

Any other values can work but you'd need to calculate your own `ANALOG_VBAT_SCALE` user_define.

**Comment by CapnBry** [comment]
> Understanding that you can't vouch for the internal wiring of the JHEMCU receiver, but assuming that the pad does in fact go to the ESP ADC pin, is the below wiring a correct practical application of the wiring diagram?

Yup, that should do it. Nice drawing!

**Comment by shaise** [comment]
> > Is this feature available in the latest release (2.5.1)? I use the JHEMCU receiver, but when auto detecting telemetry sensors, I do not see VBAT.
> 
> No it is in 3.0

Thanks.

**Comment by derFrickler** [comment]
Great, just flashed 3.0rc1 and i am getting VBAT Telemetry ;-)
Just 24k is such a strange value that i can't find any in my stock, will order some. 

Would be really great if the ANALOG_VBAT_SCALE could be set/calibrated via the webinterface at some point.

**Comment by pkendall64** [comment]
> Great, just flashed 3.0rc1 and i am getting VBAT Telemetry ;-) Just 24k is such a strange value that i can't find any in my stock, will order some.
> 
> Would be really great if the ANALOG_VBAT_SCALE could be set/calibrated via the webinterface at some point.

In 3.0 it can. It's in the /hardware.html page!

**Comment by shaise** [comment]
> In 3.0 it can. It's in the /hardware.html page!
OMG! This hidden page is great!! Wish I knew that before soldering 22K and 2.2K in series....

**Comment by derFrickler** [comment]
YES, Great!

**Comment by CapnBry** [comment]
It will be moved out of the hardware,html into a Lua option as well, there just wasn't enough time to get everything done before 3.0. I've stored config space for it already. Also yay to adjusting a value 0-10000 using the scrollwheel in EdgeTX haha. 

Yeah, 24k is a really weird value. Why u pick that value, crteensy?! 😄

**Comment by shaise** [comment]
> Yeah, 24k is a really weird value. Why u pick that value, crteensy?! 😄

Weird but obtainable: https://www.aliexpress.com/item/1005001436923851.html

**Pull request merged**
