### PR TITLE
Refactoring: remove ISM_2400 regulatory domain from user defines

### PR DESCRIPTION
**Pull request by cruwaller**
This PR removes dependency to `-DRegulatory_Domain_ISM_2400` definition since it is global band. It is defined per HW target now. 
User still has to define a regulatory domain to be used for 900MHz band.

This PR is based on #992 which needs to merged first.

### CODE REVIEW

**Comment by CapnBry** [comment]
Oh thank goodness! Every time I have to turn off Team2.4 to compile something for 915 I say to myself, why do we have this? I frown even more when I forget to turn it back and flash 5 things with 915 defined.

**Review by pkendall64 — DISMISSED** [review]

**Review by CapnBry — DISMISSED** [review]
Tested with Team900 stuff defined, I still get a Team2.4 binary. Success kid meme, I've wanted this for a while.

I think this may be what you're talking about above, but Is there any way to have it build with no Regulatory_Domain defined for Team2.4? Trying to build with nothing set I get `Please define a Regulatory_Domain in user_defines.txt`.

**Comment by cruwaller** [comment]
I had to update pio envs to support #Team2400 builds without Team900 flag. 
Also the SX127x driver lib is ignored for the SX128x builds and vice versa.

**Review by CapnBry — APPROVED** [review]

**Comment by CapnBry** [comment]
Works for me building Team2.4 with no domain defined, 2400 defined, or FCC_915 defined. Also works building Team900 with FCC_915 defined, bails if no Team900 define is set, and errors if 2400 is set. Seems to cover all the bases!

**Comment by JyeSmith** [comment]
Tested on 2.4 DIY Rx and HM Tx.  Flashed fine without the domain defined.

**Review by JyeSmith — APPROVED** [review]

**Pull request merged**
