### PR TITLE
Fix for 10KHz 0% and 100% on 8285 receivers

### LINKED ISSUE #2490: 10kHz PWM output does not go to 0% or 100% Duty on ESP8266 based receivers
I verified the behavior described below as well. 10kHz output works properly on ESP32 based receivers, but not on ESP8266 based receivers. Output initializes properly at zero, but once changed never goes below about 1% or above 99%. 

Original report:
I can now confirm that my Channel goes from 988-1884. Tested different elrs Versions and differed RX pins. 

The very strange thing is that the pwm signal on the receiver Pin is 0 (without any spikes) when the receiver is powered up and bound with the TX while the TX channel signal is low. As soon as the channel signal was above 1000µs once, the receiver output pwm will never go back to o again, it will always keep small positive spikes making to motor to spin slowly and never stop. 
For me this looks like a bug in the pwm generation, anyone can confirm this?  maybe @Ncerzzk ?

Feel free to contact me in Discord: https://discord.com/channels/596350022191415318/798006228450017290/1168851700002590751

_Originally posted by @derFrickler in https://github.com/ExpressLRS/ExpressLRS/issues/1850#issuecomment-1786970968_

### PR DESCRIPTION
**Pull request by pkendall64**
Would you folk like to test this please and comment here if it fixes it for you. @ot0tot @derFrickler 

Fixes #2490

### CODE REVIEW

**Comment by derFrickler** [comment]
Just tested the fix via the ELRS configurator (very handy!) and it seems to work just fine! Motor is now stopping when throttle is put back to zero. 

Here's my setup with a mini minimal "ESC"
IMG_20231204_190311

**Comment by pkendall64** [comment]
> Just tested the fix via the ELRS configurator (very handy!) and it seems to work just fine! Motor is now stopping when throttle is put back to zero.
> 

Thanks for testing.

**Comment by ot0tot** [comment]
Tested and confirmed working on a BetaFPV Nano RX (ESP8266 based) with a logic analyzer. 0% duty at 0, 100% duty at 100, and duty scales smoothly linearly with stick position between. Tested on two outputs simultaneously at F1000, all works as expected. 

Nice work @pkendall64 !

If you have a minute, could you briefly explain the issue and the fix?

**Comment by pkendall64** [comment]
> If you have a minute, could you briefly explain the issue and the fix?

There were 2 problems.
First when the timeHigh was zero it wouldn't update the timer values so would be stuck at the last value.
Secondly in the timer code when it detected the switching to LOW or HIGH state we can detect the zero time case there and not make the output for the pin change. The timing code remains unchanged and will do the right thing.

**Comment by CapnBry** [comment]
Oh boy you want me to review this? Now I gotta remember why the code was in a very very specific order and format when I made it.

**Comment by pkendall64** [comment]
> Oh boy you want me to review this? Now I gotta remember why the code was in a very very specific order and format when I made it. (laughing sweat emoji)

Of course... dig deep into those memories 😄

**Review by CapnBry — APPROVED** [review]
Aight, this seems legit. I did not check the 10khz output on the scope but seems to turn on and off and the code looks right. Shame on me for not ever expecting someone would want to generate a servo PWM waveform with 0 duty cycle!

**Review by deadbytefpv — APPROVED** [review]

**Comment by pkendall64** [comment]
> Good afternoon. Is it possible to use Duty cycle from 0 to 100 on other frequencies , for example , at 333 Hz?

Not in the current implementation.

**Comment by JDprofessional** [comment]
Is there a way to implement this?

**Comment by ot0tot** [comment]
> Is there a way to implement this?

What are you trying to accomplish?

**Comment by JDprofessional** [comment]
solenoid control on very large machines. Through the mosfet amplifier.

**Comment by ot0tot** [comment]
Sounds well beyond the scope of this project, but you should be able to modify https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lib/ServoOutput/devServoOutput.cpp to do what you want.

**Comment by CapnBry** [comment]
> solenoid control on very large machines. Through the mosfet amplifier

The solenoid runs at 333hz? Wouldn't on/off be better for solenoids because that react so slowly?

Can you provide a link for the solenoid specifications? I am curious about it

**Pull request merged**
