### PR TITLE
Downgrade wifi power for 8285 based devices

### LINKED ISSUE #2819: v3.4.0+ ESP8285 brownout when starting WIFI or when flashing thru WIFI
#2568 Increase the wifi power output on the ESP8285 devices from 13dBm to 20.5dBm.

Started updating my Happymodel EP1/2 to v3.4.3 from v3.3.X when I realized that after updating them, none of them could connect to WIFI anymore.

Tested 7x EP1 and 2x EP2 and they all stopped working.
Flashed them back to v3.3.0 and WIFI started to work again.

I downloaded v3.4.3 source code and changed the WIFI power level back to 13dBm and all the receivers started to work again.

I have 15x BAYCKRC 5xPWM receivers that started to corrupt firmware when flashing thru WIFI.
They connect to WIFI normally but after firmware upload they randomly fail to properly flash and this started with the WIFI power level change.
I think that there are brownouts when writing the flash memory while the WIFI is on.

All of my receivers work perfectly on older than v3.4.0 firmware.

### PR DESCRIPTION
**Pull request by pkendall64**
Harrumph, underpec'd  hardware!

Have to downgrade the wifi power as some devices are just rebooting when going into wifi mode!

Fixes #2819, #2733

### CODE REVIEW

**Review by JyeSmith — APPROVED** [review]
the-simpsons-homer-simpson

**Comment by pkendall64** [comment]
> Is 13.5 a valid value? It was 13 previously.

Yes it's a valid value. I know it was 13 before. I wasn't terribly worried about the extra power consumption of 0.5dB.

**Comment by kasatka60** [comment]
What if you make a separate point for selecting Wi-Fi power?

**Comment by pkendall64** [comment]
> What if you make a separate point for selecting Wi-Fi power?

I'll think about that for the future. If I do this then it would be in the hardware.html as it is target specific.

**Review by MUSTARDTIGERFPV — APPROVED** [review]

**Pull request merged**
