### PR TITLE
Added ELRS.bas, an ErskyTx Basic script providing a usable subset of ELRS.lua functionality

### PR DESCRIPTION
**Pull request by spinorkit**
It seems this is of interest to people other than myself, so pulling it into the main repo should make it more discoverable.
Currently does not support bind.
Currently does not check the lua version number.

### CODE REVIEW

**Comment by AlexZaiets** [comment]
@spinorkit Are you planning to add Lua 2.0 functionality to ELRS.bas?

**Comment by jurgelenas** [comment]
> @spinorkit Are you planning to add Lua 2.0 functionality to ELRS.bas?

I think CSRF lua will also work for 2.0 :) in the meantime you could use just that.

**Comment by AlexZaiets** [comment]
> > @spinorkit Are you planning to add Lua 2.0 functionality to ELRS.bas?
> 
> I think CSRF lua will also work for 2.0 :) in the meantime you could use just that.

But ErskyTX doesn't have lua support for AR9X board :). So AR9X will only work with Basic script

**Comment by jurgelenas** [comment]
> > > @spinorkit Are you planning to add Lua 2.0 functionality to ELRS.bas?
> > 
> > 
> > I think CSRF lua will also work for 2.0 :) in the meantime you could use just that.
> 
> But ErskyTX doesn't have lua support for AR9X board :). So AR9X will only work with Basic script

Sorry I meant you could use existing CSRF basic script if it exists

**Comment by spinorkit** [comment]
> @spinorkit Are you planning to add Lua 2.0 functionality to ELRS.bas?

Yes, but I am not sure how big a job it is yet. Probably won't get time to look at it until the Xmas break.

**Comment by AlexZaiets** [comment]
@spinorkit that's good news! I think there will be a lot of work, since the functionality of the LUA script has increased greatly. You may need Mike's help to expand the functionality of the Basic language in Erskytx. I was also going to watch this script after the new year. For now I am using your script with ELRS 1.0 on AR9X and R9M without problems!
If you need help with tests, I will be glad to help!

**Pull request merged**
