### PR TITLE
Simplify TX UART code

### PR DESCRIPTION
**Pull request by pkendall64**
Simplifies the serial out handling in CRSF TX code.

In the `handleUARTout` function we currently output as much data as we can up to `MAX_BYTES_SENT_IN_UART_OUT` and on the next round complete sending the packet from the FIFO.

Rather than storing a length prefix and the data in the serial FIFO, just store the data, and in `handleUARTout` output as much data as we can up to `MAX_BYTES_SENT_IN_UART_OUT`. This way we don't need to remember the last packet and all the state management around that.

On the R9M TX target this reduces the Flash space by another 128 bytes!

## Before
RAM:   [==        ]  23.9% (used 4892 bytes from 20480 bytes)
Flash: [=======   ]  72.5% (used 47524 bytes from 65536 bytes)

## After
RAM:   [==        ]  23.9% (used 4892 bytes from 20480 bytes)
Flash: [=======   ]  72.3% (used 47396 bytes from 65536 bytes)

### CODE REVIEW

**Comment by CapnBry** [comment]
This is a good idea because if we're not keeping packets intact there's no reason to store them that way and go to through the effort of splitting them to transfer.

I need to do some testing because on some hardware, switching between RX mode and TX mode generates a bit due to the fact that inverted halfduplex serial signals are really terrible looking on a scope. This generates an extra byte in OpenTX. If the byte arrives between packets, it isn't the CRSF_SYNC byte so it is discarded as a framing error, but if we switch mid-packet then that whole packet will be lost as a CRC error. This is a problem with our existing code as well but I don't think we run into it very often because we never have that much data to send.

I think we need to look into this more before we move further away from keeping the packets intact, although just streaming the bytes is a much cleaner and preferred solution. (shakes fist at half duplex inverted serial)

**Comment by AlessandroAU** [comment]
I feel unsure about this one, I think it's possible to get a bad state with the device on the other end if we just split up and spam out packets?, Like what happens if the receive logic is based on timeouts and we don't need a full packet?  I also liked being able to see the discrete chunks of packets on the scope, but that's only a cosmetic issue.

**Comment by pkendall64** [comment]
This doesn't materially change the way the data is sent to the TX.

The only difference to the current implementation is that the existing one will, on a long packet, send the first chunk of bytes, then the second, which could be a single byte. Any further bytes in the FIFO will wait till the next round. Whereas the new implementation would send the first chunk, then the single byte along with more bytes if there are any in the fifo.

As you say, if there were timeouts involved then we could run into problems because the start of packet is likely not aligned to the start of the receive window. I would have thought this would have been a problem with split packets as well if this were a problem.

I think this will be less of a problem going forward when the Radios have faster baud rates and we can change the size of the packet chunk based on the baud rate and packet rate.

**Comment by CapnBry** [comment]
I did a bunch of testing with this with me SIYI FM30, which likes to generate an extra bit a lot of times when switching from RX to TX mode. I ran it at high telemetry rate (1:8) with iNav connected to have a lot of data to send. What I found
* The throughput of the connection is higher with this than with the basic packet splitter. The splitter would almost always send one full packet even if there were two in the FIFO. This code sends as much as can fit in the 32 byte limit, so sometimes it would work in double packets. Win!
* When packets are split, they have a >50% chance of generating a CRC error on the handset. This is true for both the original packet splitter and this code, since any split packet has a high chance of generating the extra bit. This resulted in spacing between our 320ms linkstats packet becoming 640ms in most cases.
* Most our "splits" using the new code are when the fifo had 33 or 34 bytes in it, 1-2 more than our limit. pkendall did the math and at 500Hz 400kbit, we should be able to fit 36 bytes (assuming a 10% overhead). I would recommend that the limit be upped to 34 bytes to handle double packets without splitting them. Ideally this could use the OpenTX Sync micros counter and dynamically adjust how much is sent each period to fit in the window, but I am not sure if that would break things like Lua Config or MSP data because howwwwww does that work at all currently on half-duplex without us blasting over it?

So unfortunately this makes the CRC problem worse on this hardware due to the higher throughput splitting more packets. I flippin' hate half-duplex! If we upped it to 34 bytes max per transfer, it would be the same as the existing packet split implementation. I think we should do this? I dunno I am very 🤷‍♀️.

**Comment by pkendall64** [comment]
Ok, I'm down with not doing this. I think now that we can go at much faster UART speeds, the problem can be solved by dynamically adjusting the size of transmission bundle based on the baud-rate.

**Comment by CapnBry** [comment]
☹️

**Pull request closed without merging**
