### PR TITLE
BLETelemetry,Adapt the 2305 update to fit the current master version.

### PR DESCRIPTION
**Pull request by AlanAlger001**
Adapt the [#2305 ](https://github.com/ExpressLRS/ExpressLRS/pull/2305) update to fit the current master version.
My DIY ESP32-S3 device operates superbly across all rates and feedback ratios.Hope to merge into the mainline soon.
Test configuration
TX:DIANWEI PRO（DIY）
     ESP32-S3-Fn8
     Gemini
     F1000Hz
     1:2
     50mw
RX：YLWC（DIY）
     ESP32-PICO-D4
     Gemini
     500mw

dab82ae16e2a9085ed040fe74d82fcc
84ff2cb7fa00c321bd7009c9bb8b8e2
efa4b8620953504f4de5a1a5e6077ab
c4ff87b780f4f6fda341c1436d8f4ed

### CODE REVIEW

**Comment by konstkarapan** [comment]
Hope this merges soon🙏

**Comment by AlanAlger001** [comment]
@pkendall64

**Comment by MakeSomeFakeNews** [comment]
Hope this merges🙏

**Review by druckgott — APPROVED** [review]

**Comment by druckgott** [comment]
Is there a way to build again for testing:
grafik

**Comment by piotr-ryczek** [comment]
Currently unfortunatelly it is impossible to build firmware using Configurator. And some conflicts appeared.

**Review by arvet333 — APPROVED** [review]

**Comment by wvarty** [comment]
I have some good news and some bad news:

**The bad news:**
The bad news is that this wont be merged. The Bluetooth stack is far too heavy weight to have running at the same time as the RF timer without risking timing related issues, either now or in the future. This was mentioned on the last pull request, when this was originally proposed, but it doesn't appear to have sunk in.

**The good news:**
The good news is that there is an alternative approach that should achieve the exact same outcome as this PR. The ELRS Backpack functionality (see https://github.com/ExpressLRS/Backpack) is being steadily enhanced to provide telemetry streaming options to external devices, in a range of different RF flavours. So far, there are options for ESP-NOW, and WiFi, but the new ESP32C3-based Backpack modules also add Bluetooth capability as well. If wont take much work to forward the CRSF telem stream out from the Backpack via BT, so this is what we intend to aim for.

Closing this PR down, in favour of that solution.

**Comment by jiri-jirus** [comment]
240MHz chip is not able to cope with bluetooth? really?

**Comment by GT-Volk** [comment]
@wvarty This solution worked great on my T20 for a long time. Backpack is the most useless and pointless solution.

**Pull request closed without merging**
