### PR TITLE
Only call servo function if theres a change

### LINKED ISSUE #2548: [PWM receiver Firmware] frequently lost control.
## Current Behavior
PWM receiver lost control irregularly.
Once the receiver lost control, it will hold the last state for about 10 seconds and then regain control.
Since it does not enter failsafe, it seems that the problem is not the wireless connection being interrupted, but a malfunction of the receiver.

## Steps to Reproduce
Radiomaster MT12 EdgeTX2.10.0(dfaaad730)
BetaFPV nanoTXmodule ELRS3.3.2 (2d9891)
Happymodel EPW6 ELRS3.3.2(2d9891)

1. I was using the ELRS configurator, but after learning about #2156, I reset the PIO and decided to use only the WEB Flasher.
2. I flashed ELRS3.3.1 to EPW6 using a WEB Flasher, but the problem was not resolved.
3. The figure below shows the log data from the bench test. The second image is an enlarged view of 10 seconds when control is lost.
nanoTX332EPW6332
lost10sec

## Possible Solution (Not obligatory)
I flashed ELRS3.3.0 to EPW6 using a WEB flasher, and no problems have occurred in a 10-hour bench test. I don't think 10 hours is enough, so I'm continuing the test.

## Details

- TX hardware:BetaFPV nanoTXmodule ELRS3.3.2 (2d9891)
- RX hardware:Happymodel EPW6 ELRS3.3.2(2d9891)
- Handset model:Radiomaster MT12
- OpenTX version (including nightly number):EdgeTX2.10.0(dfaaad730)
- ExpressLRS version (TX & RX MUST MATCH):ELRS3.3.2(2d9891)
- Packet Rate:F1000
- Telemetry Ratio:1:32
- user_defines:

### PR DESCRIPTION
**Pull request by pkendall64**
Fixes #2548 

I managed to reproduce the issue on an 8285 based receiver.

The scenario used is to set the TX to F1000 mode and the PWM outputs to 333Hz, this will ensure that we are resetting the PWM values at 1000 times a second so it's setting the PWM to change multiple times during a single cycle.

Screenshot 2024-02-24 at 1 11 12 PM
As can be seen the LQ (TQly%) tanks for a 10 second period. The issue is that the receiver gets locked up in the PWM code and is then reset the by the WDT (watchdog timer). The timer fires after 10 seconds of not going going back to the main loop. This "fix" is just a workaround which only updates the servo signal only if the channel value has actually changed from the previous value.

After this change I ran a 48 hour test without any issues.

Screenshot 2024-02-24 at 1 20 30 PM

### CODE REVIEW

**Review by deadbytefpv — APPROVED** [review]
Tested with an ER3C-i (channels set to 333Hz) paired with an MT12 (set to f1000).

Prior to flashing the PR, I would get moments of lost control, receiver seems to hold position (broke a turnbuckle in the process; hurray for spares!). It was irregular and sporadic, so kinda hard to anticipate. Test is for one-pack (40min+) and issue happened 2-3 times.

Flashed the PR and redid the test (mainly going around in circles, figure 8s; sakura d5 drift car) with a fresh pack. No "lockups". Did the test almost the same duration and now I'm thinking of a few upgrades like wheel + tire combo, suspension/dampers and alu hop-ups.. And going to a track 5hours+ away..

**Review by CapnBry — APPROVED** [review]
Goodbye 32 more bytes of RAM for everyone :'(

I think you're getting a little out of control with `auto` though. Going out of your way to convert code that already has the fully specified type to auto? 🤔 What advantage did that bring?

**Comment by pkendall64** [comment]
> Goodbye 32 more bytes of RAM for everyone :'(

I know, I'm sorry 😢 

> I think you're getting a little out of control with `auto` though. Going out of your way to convert code that already has the fully specified type to auto? 🤔 What advantage did that bring?

I like auto when a variable is being created, assigned and used on the stack for a short time; especially if it's just for some tests or being passed as a parameter.

**Comment by chofchop** [comment]
Thank you for fixing the problem.
You yourself say that this is just a workaround, but are there any plans to fundamentally solve this problem in the future?
It's pretty clear that the change from 3.3.0 to 3.3.1 caused this problem. I'm afraid of crashes, so I'll stay with 3.3.0 for the time being.

**Comment by pkendall64** [comment]
There was no change from 3.3.0 to 3.3.1. There was a small from 3.3.1 to 3.3.2 which was designed to fix the problem of the duty cycle output not being able to go to 0% or 100%. You are not using the duty-cycle feature, so that will not be the cause of the problem you have been seeing.

**Comment by chofchop** [comment]
I'm not a software expert, but don't you think that bugs often hide in places you can't imagine?
The binaries for 3.3.0 and 3.3.1 are different, and it is clear that the problem has started with 3.3.1.

**Comment by jmxp69** [comment]
> Thank you for fixing the problem. You yourself say that this is just a workaround, but are there any plans to fundamentally solve this problem in the future? It's pretty clear that the change from 3.3.0 to 3.3.1 caused this problem. I'm afraid of crashes, so I'll stay with 3.3.0 for the time being.

It's unclear to me how we know the change from 3.3.0 to 3.3.1 introduced the issue. Please elaborate.

**Comment by chofchop** [comment]
> It's unclear to me how we know the change from 3.3.0 to 3.3.1 introduced the issue. Please elaborate.

It is a confirmed fact that the problem occurs with 3.3.1 and 3.3.2. In 3.3.0 it hasn't happened even once.
No further evidence is needed.

**Comment by jmxp69** [comment]
> > It's unclear to me how we know the change from 3.3.0 to 3.3.1 introduced the issue. Please elaborate.
> 
> It is a confirmed fact that the problem occurs with 3.3.1 and 3.3.2. In 3.3.0 it hasn't happened even once. No further evidence is needed.

Going to have to disagree no further evidence is needed. Just because it didn't happen doesn't mean the problem wasn't there. The developer stated there were no changes to this segment of code. "There was no change from 3.3.0 to 3.3.1"

**Comment by chofchop** [comment]
> Going to have to disagree no further evidence is needed. Just because it didn't happen doesn't mean the problem wasn't there. 

As you say, saying that no problems have occurred up until now does not mean that there have been no problems. It would be correct to say that the incidence is simply low.
But now that doesn't matter. My purpose is to have #2458 fundamentally resolved. To that end, I simply provided the information that #2458 occurs noticeably after 3.3.1.

>The developer stated there were no changes to this segment of code. "There was no change from 3.3.0 to 3.3.1" To borrow from your own logic "don't you think that bugs often hide in places you can't imagine?"

I understand that the developer is saying, "There are no changes **to this part**". With that in mind, I'm saying that the problem may be lurking in other areas that he doesn't think are relevant.
 
> Lets just shorten your own sentence by a few words: "don't you think that bugs often hide?"

Are you saying that #2458 could have been latent even before 3.3.0? Although that is certainly a possibility, it is true that #2458 was activated after 3.3.1. The correct way to find the cause of #2458 is to trace the changes from 3.3.0 to 3.3.1.

If you just want to play word games with me, don't bother me anymore.

**Comment by jmxp69** [comment]
I'm not trying to play word games. I'm simply trying to understand the true nature of what's going on here as I fly a LOT of ELRS on a LOT of expensive planes. You made an assertion the problem didn't exist prior to 3.3.0. The developer said there were no changes between 3.3.0 and 3.3.1 in this area. So I'm simply trying to reconcile the discrepancy. But I can tell by your tone, you're not someone I wish to conduct any further dialogue. So goodbye.

**Comment by pkendall64** [comment]
The problem has actually existed prior to 3.3.0. It was even seen in the 2.5 and earlier era of the code. It randomly appeared/disappeared. Prior to moving to pre-built binaries (3.0.0) it would appear for some users and not others i.e. users building on Windows would be affected but Mac or Linux would not see the issue.
It basically disappeared after moving to pre-built binaries and this is the first report of it coming back.

> The correct way to find the cause of https://github.com/ExpressLRS/ExpressLRS/pull/2458 is to trace the changes from 3.3.0 to 3.3.1.

I've been over the changes from 3.3.0 to 3.3.1 and cannot see anything that could cause the issue.
If you think the bug crept in between 3.3.0 and 3.3.1 then you are more than welcome to look at the diffs and see if you can spot the problem, and report back. Heres the diff https://github.com/ExpressLRS/ExpressLRS/compare/3.3.0...3.3.1

I am still investigating to see if I can find the root cause of the issue. As I said on the PR, the current "fix" is a workaround that I tested for 48 hours without an issue.

**Comment by chofchop** [comment]
Thank you for your detailed explanation.
Unfortunately, I don't have the skills to track the differences between 3.3.0 and 3.3.1.
Fortunately, I don't need the features introduced after 3.3.1, so I'm staying with 3.3.0 for now.

By the way, as Ocrap says in #2577, this problem is very dangerous, so I think all ELRS users should be made aware of it.

**Comment by VancouverUmbrella** [comment]
Hey there, everyone. 

First off, I'd like to thank all the participants here for their good work on this issue. 

I was alerted to the potential problem in an RCG post that I stumbled upon a little while ago. Having lost several models to apparently similar bugs in several other protocols, the report struck a chord. In fact, last autumn I moved to ELRS specifically to avoid such occurrences of loss of control without failsafe.

My hunch is that there's very unlikely to be a single mechanism behind the apparently similar failures across different protocols. From my own investigations, I believe that such failures may be difficult to trigger intentionally. In fact, in over 500 hours of bench testing with one of those suspect protocols (FrSky ACCeSS), I failed to produce a single definitive occurrence of the issue. Shortly thereafter, the problem occurred again in flight, a model was lost, and I called it quits.

I'm not sure I can bring much to the table in terms of practical help with ELRS. Still, I would like to voice support for a robust pursuit of the issue. Meanwhile, I'm tempted to stick with ELRS 3.3.0. Version 3.3.0 is the one I've been flying with exclusively for the past few months. In that time, in about 40 hours of flying, the RF link has been unwaveringly superb.

Kindly,
Andrew

**Comment by ropch** [comment]
> > The correct way to find the cause of #2458 is to trace the changes from 3.3.0 to 3.3.1.
> 
> I've been over the changes from 3.3.0 to 3.3.1 and cannot see anything that could cause the issue. If you think the bug crept in between 3.3.0 and 3.3.1 then you are more than welcome to look at the diffs and see if you can spot the problem, and report back. Heres the diff [3.3.0...3.3.1](https://github.com/ExpressLRS/ExpressLRS/compare/3.3.0...3.3.1)
> 
> I am still investigating to see if I can find the root cause of the issue. As I said on the PR, the current "fix" is a workaround that I tested for 48 hours without an issue.

I am new to ExpressLRS and jumped straight to 3.3.2, F1000, and PWM output to 333Hz on all channels with my first two PWM receivers (ER3C-i and ER5C-i).

With this configuration, I observed both steering and throttle being reset (into a non-failsafe state) within minutes of configuring both models.

Being installed in RC crawlers, the problematic behavior caused no real problems or damage.  However, the problem continued to happen very frequently with both of my models while running 3.3.2 on the receivers.

I eventually checked for problem reports here on GitHub and found issue #2548 and the suggestion to revert Rx to 3.3.0.

Since reverting to 3.3.0 a few weeks ago, I have experienced absolutely no problematic behavior with either model.

Although I happen to develop software professionally, I am not familiar with the ExpressLRS codebase.  So, I don't want to speak out of turn here... but since there are only 22 commits between 3.3.0 and 3.3.1, could we 'git bisect' to determine exactly when the problem starts to occur consistently?

Although this problem may very well be a side effect of a more ambient change (vs. a specific change that impacts loop behavior directly), I have also observed that 3.3.0 seems to be problem-free, whereas newer releases are not.

**Comment by chofchop** [comment]
> since there are only 22 commits between 3.3.0 and 3.3.1, could we 'git bisect' to determine exactly when the problem starts to occur consistently?

I manually performed the equivalent of 'git bisect' for these 22 commits (6 in fact).

Radio : MT12
TX module : EP1tcxo(Generic ESP8285 Full-duplex 2.4GHz RX as TX 3.3.2), F1000, 1:32
Receiver : EPW6, 333Hz(all ch)

a14b51f
e663ea3
3ee59ba
91cf151
40c23b3

I downloaded the above five repositories, built them with VS Code, uploaded them to the receiver, tested them for over 1.5 hours, and confirmed that #2548 did not occur. I understand that 1.5 hours is not enough.

Next, I built e051b89 (=3.3.1) using VS Code in the same way as above, uploaded it, and ran a 12-hour test, but #2548 did not occur.

Furthermore, when I flashed 3.3.1 (e051b89) using the WEB flasher and tested it, #2548 occurred many times within an hour.
I have confirmed that the web flasher and VScode generate different binaries (firmware.bin) for the same e051b89.

There are still many things I don't understand, so I will continue testing.
I'm not a software expert. I may have made some mistake.

**Comment by pkendall64** [comment]
The web flasher and configurator uses the binaries generated by the github docker linux based builds, which are published to an artefact repository.

If you are building from source it will generate a different binary as it has some date information stored in the binary, done by the platform. Windows builds are different to linux builds as well. The linker moves things around in the memory space in different ways and so the binary ends up quire different.

As I have said earlier, this bug has been around previously and just sometimes disappears/reappears. Also as mentioned before the problem was far more prevalent on builds from windows systems, no idea why though.

I have also been testing all this week and have found that the root cause is the NMI timer used by the PWM code (borrowed from the ESP base framework and modified slightly for our use). The NMI timer is causing the main loop code to get stuck or just stop running at random positions, then the watchdog reboots the MCU. I have tested this by adding code to flip a GPIO at certain positions and see if the pin is HIGH/LOW when the halt/reboot occurs. The halt never occurs in our interrupt handlers, it only ever occurs in the main loop code. I have also bisected this main loop code to see if it is in any particular part of this code, but this too appears random.

My current hunch is that we are setting the NMI timer to fire again too quickly given all the other interrupt code we have and this is causing the problem. If I extend the minimum timer callback time from 4 to 10us then the issue disappears. If I shorten this time from 4 to 2us then it appears a lot more frequently.

**Comment by chofchop** [comment]
I also did the same test above for 3.3.1>3.3.2.
Result is,

db960ff
12659fb > NG
ace9269 > NG

#2548 seems to originate from #2496(12659fb).
However, seeing that it also occurs in 3.3.1, there may be more than one cause.

**Comment by VancouverUmbrella** [comment]
The ongoing investigation and discussion here is reassuring. To my way of thinking, it shows that an Open Source project like ELRS has a big advantage over proprietary systems when it comes to solving tricky problems. Kudos to you all.

@pkendall64, I came across your remark below in https://github.com/ExpressLRS/ExpressLRS/issues/2577:

> The problem is that the 8285 based receivers do not have hardware PWM output like the ESP32 based receivers, so the PWM is controlled using a timer and an interrupt. The reboot occurs because somehow the receiver is blocking in the timer interrupt and not returning causing a watchdog timer to fire.


Do you still believe or know ESP32 receivers to be unaffected? The admittedly short testing I've done with 3.3.1 was all on an ESP32 receiver. No problems occurred.

Another thing popped out. Your comment, "somehow the receiver is blocking in the timer interrupt," brought to mind the apparently similar problem I encountered with Ghost several years ago. If I'm not mistaken, a Semtech 1280 series chipset was involved in both that case and in the current problem in ELRS. If so, I can pass on some information I received from IRC when they confronted -- and solved -- their bug. 

Specifically, IRC advised that developers facing such an issue should review the chipset errata and consider that there may be an undocumented problem. Further details are covered by an NDA. Plus, I'm in well above my depth here and wouldn't be of much help in a technical discussion of the nitty gritty details. This tack may be a red herring but I thought to mention it just in case.

**Comment by pkendall64** [comment]
@chofchop 
> [pkendall64](https://github.com/pkendall64) First of all, please allow me to explain so that there is no misunderstanding. I'm not blaming you in any way. I respect all of you who have created a wonderful ELRS system. I would like to cooperate to make ELRS even better. However, my skills are immature, so I may be doing something off-topic. In that case, just laugh and ignore it. Also, English is not my native language, so my wording may be strange sometimes. Please laugh and miss this too.

Certainly no offence taken here 😄. The more people looking at this issue, the more likely we are to find the cause and fix it properly. So I certainly welcome you looking into the code.

The code in https://github.com/ExpressLRS/ExpressLRS/commit/12659fb2b4dfb04154719f26e1b9ef2eef6a4b6c is no longer required as it was fixed in a better way in the master branch, so I think it should be reverted in the master branch as the less we do in the timerInterrupt the better.

@VancouverUmbrella 
> > The problem is that the 8285 based receivers do not have hardware PWM output like the ESP32 based receivers, so the PWM is controlled using a timer and an interrupt. The reboot occurs because somehow the receiver is blocking in the timer interrupt and not returning causing a watchdog timer to fire.

That was my working theory at the time... that has changed now with more testing. The NMI is firing, completing and resetting itself. When the rest of the code halts, the NMI is continuing to work until the WDT fires. So it appears to be causing the issue elsewhere in the code. As I said above, extending the trigger time makes the whole system work. I'm just trying to understand "why" it causes the freeze at this point.

> Do you still believe or know ESP32 receivers to be unaffected? The admittedly short testing I've done with 3.3.1 was all on an ESP32 receiver. No problems occurred.

ESP32 based receivers use hardware modules built into the MCU to do the PWM signal generation, both the MCPWM and RMT modules are used, depending on the number of PWM pins. They generate much more accurate PWM signals.

The devs have a contact at Semtech that we can call upon, but at this stage I do not believe this is an issue with the radio side of things.

**Comment by ParkJeff9** [comment]
I have been told to update all my equipment to v3.4 to avoid "random reboot in the air" caused by #2548. I'm just wondering if there has been a more permanent fix implemented in 3.4.0 such as the longer NMI trigger time? Forgive me if I have not understood this pull request properly as I'm new to GitHub.

**Pull request merged**
