### PR TITLE
6/7-bit (64/128 pos) Wide Switches Mode

### PR DESCRIPTION
**Pull request by CapnBry**
This PR adds a new switch mode similar to `HYBRID_SWITCHES_8` which I've called "HybridWide". The implementation has 1x 2-pos switch (AUX1, 1-bit) and 7x 6/7-bit (AUX2-7) switches. It does so by removing the switch index from the packet and relying on the Nonce to be synced with the transmitter. The resolution of the high res switches is determined by the Telemetry Ratio, where anything less frequent than 1:8 gets 7-bit and 1:2 and 1:4 ratios get 6-bit. This is a redo of #758 which adds the new mode instead of replacing the Hybrid mode.

In addition it adds the `uplink_TX_power` field in some newly unused bits. This field is only used in iNav OSD currently but is in Betaflight git.

Note: You can not change switch modes while connected to the RX. This is because it would rely on both the TX and RX switching at the exact same time, and due to the fact we can not guarantee delivery of the switch mode packet mid-stream, the RX must be disconnected before the Lua will let the switch mode be changed.

## Switch Priority Removed
No changes to OTA size, coding parameters, effective air rate, or any other performance compromise was made to achieve this. However, the "switch priority" (where if a switch changes, it is sent on the next packet) has been removed. This means there may be a delay of up to 7 packets before the new switch is sent, but, I mean, c'mon, 7 packets is 14-140ms. The AUX1 switch is still sent every packet so ARM status is not affected. This code was almost 200 bytes of flash and I think the difference is indistinguishable to users. The code should be slightly faster now due to not having to track the switch changes, and it also only calculates the switch value for the switch it is currently sending instead of calculating all of them, then throwing out all but one.

## OTA behavior changes
When the mode is set to smHybridWide, the low 2 bits of the Nonce is now added to the CRC by the transmitter on non-SYNC packets (the sync already has the whole nonce in it). This was added to provide a guarantee that the Nonce is correct since it is used to determine the switch index that's represented in the packet. This can create a **new Sudden Failsafe situation** if the RX and TX Nonces do not match where previously we'd instead go to a 75/50/25 LQ situation. This was plucked from @pkendall64's #716 (Nonce Recovery) PR, and @JyeSmith said we had 7 bits available in the CRC from our discussion of this feature back in May so this should not affect our CRC's performance [Discord Discussion](https://discord.com/channels/596350022191415318/744445841779064863/847234283143430244)

OTA for regular Hybrid mode is unchanged and does not use the Nonce in the CRC.

## Switch Encoding compared to HYBRID_8
* Remove SwitchIndex from switch encoding, saves 3 bits
* Remove the Telemetry State bit from every packet, and only send it every 8 packets to save 1 bit. Normally, we send the "ACK" bit hundreds of times between each telem interval and really it is only needed once. At telemetry rations of 1:2 and 1:4, the telemetry bandwidth would be effectively crippled waiting for the ACK, so at these ratios the bit is sent every packet again.
* Use the 6/7 available bits to send the switch, or maybe we can almost call it channel, data

The extra slot that would be taken by AUX1 is used to transmit the telemetry ACK bit and `uplink_TX_power`. We don't need to send that so often, so if anyone has any values they want to uplink to the RX of 6 bits or less, there's more space available. We have roughly 16 "slots" of 6 bits and the TX power can take just one instead of all of them.

## Caveats
The telemetry ACK bit used to be sent every dang packet, meaning there were many opportunities for the ack to get to the RX before the next Telemetry send. Because it is only sent every 8 packets now, there's a higher chance that the bit won't make it to the RX and the RX will retransmit the previous telemetry packet, thus reducing the effective telemetry bandwidth.

## Docs
I haven't written any of the documentation yet, but they almost behave like real channels now so people will be less confused by them.

## Testing
* Tested Team2.4 FM30 TX / FR Mini RX + EP2 RX (iNav) at 500/250/50Hz and 1:128, 1:64, 1:8, 1:4 ratio.

### CODE REVIEW

**Comment by avsaase** [comment]
Is the TX uplink power correctly passed to the flight controller? I am trying to add the 50mW power level by returning it as index 8 from `powerToCrsfPower()` and making the corresponding change in INAV. However I am not getting any changes in the TX power OSD element, it always stays at 0mW.

I know the protocol doesn't support 50mW. I figured I could just do it for myself.

**Comment by CapnBry** [comment]
Does it display the other power levels correctly? If so check your code.

**Comment by avsaase** [comment]
No it shows 0mW for all power levels.

**Comment by CapnBry** [comment]
Doesn't; sound like you're in wide switch mode then? It displays for me on iNav 2.6 and I can't think of why that would break on 3.0 but I have not tried it.

**Comment by avsaase** [comment]
Ah of course, no I'm not. I actually wasn't able to get that to work in the Lua script. It just switches back to the other setting.

**Comment by CapnBry** [comment]
> Ah of course, no I'm not. I actually wasn't able to get that to work in the Lua script. It just switches back to the other setting. I hadn't realized that meant the TX power would not be transmitted to the RX.

Disconnect the RX before changing the mode. We can't change switch modes safely with the RX connected.

**Comment by avsaase** [comment]
Thanks. Something to add to the docs once this is merged.

**Comment by CapnBry** [comment]
Yup literally **all** of it will need to be added to the docs!

**Comment by avsaase** [comment]
Wide Switches at work:

https://user-images.githubusercontent.com/880421/131232472-20cdfe6c-f217-4be5-9957-c57abca0c715.mp4

Channels 6-12 are now essentially higher-latency low-resolution channels.

Is the plan to (eventually) completely replace the "old" Hybrid Switch mode, or is there a reason to keep it? 

OSD TX power also working nicely (with 50mW power level added in INAV):

https://user-images.githubusercontent.com/880421/131232848-d9d3740b-b8a4-4237-9536-f8fd63f82d85.mp4

P.S.: I understand the technical reason but from a user perspective it's not obvious why TX uplink power is only sent to the RX when Wide Switches is enabled.

**Comment by CapnBry** [comment]
>P.S.: I understand the technical reason but from a user perspective it's not obvious why TX uplink power is only sent to the RX when Wide Switches is enabled.

What can you do though? It is like a user using Hybrid switches and complaining that their switches are only 2/3/6 pos. Each switch mode has its own set of features. If we had a byte to spare, we'd send it with Hybrid as well.

My plan was to replace Hybrid with Wide entirely, but requiring the Nonce to be synced was making people nervous and vocal so this mode was added alongside the existing Hybrid. See the other PR #758 for the discussion.

**Comment by mariansoban** [comment]
> 
> 
> Wide Switches at work:
> 2021-08-29_00-09-30.mp4
> 
> Channels 6-12 are now essentially higher-latency low-resolution channels.
> 
> Is the plan to (eventually) completely replace the "old" Hybrid Switch mode, or is there a reason to keep it?
> 
> OSD TX power also working nicely (with 50mW power level added in INAV):
> PICT0038_5_2.mp4
> 
> P.S.: I understand the technical reason but from a user perspective it's not obvious why TX uplink power is only sent to the RX when Wide Switches is enabled.

I'd like to test this feature too, but I have some issues with running it - I've built new firmware for HappyModel 2.4 TX and receiver from master - shortly after pull request was merged into the master. 
After flashing firmware, RC link worked, but the bevior of switch channel looked like hybrid switches - no wide channels. I also could not configure TX module in OpenTX radio - ELRS.lua script was unable to connect to HappyModel module. When I've tried to downgrade firmware to stable release 1.1.0 I had to do it with USB cable on TX side (because LUA script is unable to connect...) and I can't downgrade EP1 receiver via WIFI - I'm getting error "Wrong firmware uploaded, does not match Receiver module type". Anyway I can still upgrade receiver from current master sources via WIFI with no issue.
Any hints how to test wide switches before release?

**Comment by avsaase** [comment]
@mariansoban you need to use the Lua script from the GitHub repo for anything that's not 1.x (do not the one from the configurator) and then enable Wide switches in the Lua.

**Comment by mariansoban** [comment]
@avsaase Thanks for answer - from which branch should I get that ELRS.lua version? I've used one from master branch before, but it didn't work. (updated 19 days ago, commit 4182f4199c915309534482eb7646838f126df041). Or can you paste here working version here?

**Comment by CapnBry** [comment]
> @avsaase Thanks for answer - from which branch should I get that ELRS.lua version? I've used one from master branch before, but it didn't work. (updated 19 days ago, commit [4182f41](https://github.com/ExpressLRS/ExpressLRS/commit/4182f4199c915309534482eb7646838f126df041)). Or can you paste here working version here?

You get it from master bit maybe you should read the page:
https://github.com/ExpressLRS/ExpressLRS/tree/master/src/lua

**Comment by mariansoban** [comment]
Thanks for ponting me - I've used elrsV2.lua from master and consequently I was able to to get to ELRS module configuration menu in OpenTX on Jumper T16 TX.
I switched switch mode from HYBRID to WIDE, but unfortunately my TX restarted and got to emergency mode afterwards, so I need to find out what's going on...

**Comment by mariansoban** [comment]
Just for info - the issue was on my radio side - with new radio (Radiomaster TX16S) ELRS configuration with LUA script works at me.

**Pull request merged**
