### PR TITLE
One LUA For All handset

### PR DESCRIPTION
**Pull request by StonedDawg**
this PR removed the all 3 seperated LUA and combines them as 1 LUA for easier future LUA update and consistency.
this PR also add slight new changes to how the LUA is displayed.

test needed for : 

- [x] X9D or X9D+
- [x] qx7 or x9 lite or any other 128x64 screen
- [x] t16, t18, tx16s or any other colored screen
- [x] jumper t12

### CODE REVIEW

**Comment by pfeerick** [comment]
X9D+2019... script starts fine, and seems to work. 

Progress bar is nice whilst doing stuff - and now know (hope!) lua script is actually doing something when loading. 

Minor niggle - first row of print seems a fraction high... limitation of the screen height and number of lines of text?

https://youtu.be/Uk2J2d_UyNQ

**Comment by StonedDawg** [comment]
@pfeerick cool! thanks for helping to test this! I fixed the first row problem, also added a more "ELRS themed" color for the header bar and progressBar. :wink:

**Comment by pfeerick** [comment]
Perfect! TX16S is much better now, thank you! :)
https://youtu.be/vgnjplPKTAM

For the X9D+ / TX12, now the print goes off-screen...
X9D+ - https://youtu.be/eCzRIb4HNew
TX12  - https://youtu.be/wnHPwYTJmeY

Also, any idea why the TX power menu would sometimes not have any entries, or only have one line (i.e. TX12 did it, and X9D+ has)? It *seems* to come good if I restart the script two or three times... and other times won't play up several times in a row...

**Comment by StonedDawg** [comment]
@pfeerick thankyou very much for trying again! also with detailed videos! that's really helpful. I have updated the lua scripts for the scrolling fix, and also tweaked a little to help with some folder entries not showing up. it's hard to be certain for now, but I am suspecting that it was loosing its index somehow. let's see if it is fixed now.

**Comment by pfeerick** [comment]
No problem... 

Overflow text is good now, can scroll that bit further to see the bottom line now. Quick folder is good - and refresh happens when returning to main screen. Since you mention index, after that last commit (hopefully - github raw does sometimes take a few minutes to refresh) I still got a one line screen (only Dynamic entry)... but this time I tried scrolling and got both entries - so it does look like that was the problem. I'll play with it more tomorrow and will checkout the repo so I'm sure I'm using the right version. Let me know if there is anything specific you want tested. ;)

**Comment by StonedDawg** [comment]
@pfeerick I didn't check your comment earlier, but I pushed a commit to fix it right after. should be all fixed now :) ! thanks a lot for patiently testing this PR too!

**Comment by StonedDawg** [comment]
for now reloading all params after changing 1 param may seems to be unnecessary, but it would be best to keep the param screen in the lua as updated as possible incase we have a linked parameter. (although a linked parameter should have in the module code to request all params to be reloaded). crossfire original lua script does not need to do this since crossfire original lua script will keep on refreshing all parameter.

**Review by pkendall64 — APPROVED** [review]

**Comment by nangel0** [comment]
OLD JUMPER T12 here, (qx7 look a like)
 LUA starts most of the time, looks good
https://www.dropbox.com/s/9wbvqxscjvvtf9q/1631226931851.jpg?dl=0

Issues: 
Some times gives a syntax error and doesn't start.

On exit gives this error.
https://www.dropbox.com/s/na1k00sj2jpq87o/1631226931834.jpg?dl=0

Any values only increase, booth keys goes up (video).
https://www.dropbox.com/s/9hzs6ra303idc02/vid_20210909_225103.mp4?dl=0

**Comment by StonedDawg** [comment]
@nangel0 thanks for reporting! can I have more detail info of this T12? OpenTx or EdgeTx? version?

**Comment by nangel0** [comment]
> @nangel0 thanks for reporting! can I have more detail info of this T12? OpenTx or EdgeTx? version?

Sure.
It's EdgeTx, nightly from 2 days ago

**Comment by StonedDawg** [comment]
@nangel0 yeah this does seems like the button is not registered. is there any other lua script you use that the button works?

**Comment by nangel0** [comment]
> @nangel0 yeah this does seems like the button is not registered. is there any other lua script you use that the button works?

It works with the previous lua script

**Comment by StonedDawg** [comment]
> > @nangel0 yeah this does seems like the button is not registered. is there any other lua script you use that the button works?
> 
> It works with the previous lua script

do you mean the elrs.lua (v1) script or the v2 seperated script?

**Comment by pfeerick** [comment]
And a nice surprise at that! :) Just tried this again on the TX16 and X9D+ ... haven't noticed the menu shift on it at all...

**Comment by StonedDawg** [comment]
> And a nice surprise at that! :) Just tried this again on the TX16 and X9D+ ... haven't noticed the menu shift on it at all... looks like you clobbered it into submission.
> 
> So does selecting the version field do anything (as I'm currently too lazy to read through the code 😁 )

 thanks for checking back in! as certain as i can feel that i didn't break the code with x9d with the new commit, it's nice to be reassured 😁. nah it doesn't do anything other than just triggering the "write" command and makes the lua refresh the version params...

**Review by CapnBry — APPROVED** [review]

**Comment by CapnBry** [comment]
Works great for me on Q X7 and Mambo with both a SIYI FM30 and ES900TX. Also read the code and it looks good to me, nice to have this all integrated into one script again. A great convenience for the users!

**Pull request merged**
