### PR TITLE
Remove FEATURE_OPENTX_SYNC define

### PR DESCRIPTION
**Pull request by CapnBry**
Removes the define FEATURE_OPENTX_SYNC.

This define was really dumb. We always send OpenTX sync information packets no matter if this is defined or not. The only thing this define does is make the value accurate. If this define wasn't enabled, the Sync Offset is just never adjusted to our packet timing so the offset we send to OpenTX would just be (now - 0).

Also removed FEATURE_OPENTX_SYNC_AUTOTUNE entirely (code and all).

Unrelated change not worthy of its own PR: `DEBUG_FREERUN_TX` wouldn't compile due to code rearranging for devCRSF, so I just fixed it to compile again.

### CODE REVIEW

**Comment by AlessandroAU** [comment]
I agree, it's time to remove this option !

**Comment by CapnBry** [comment]
Also removed `FEATURE_OPENTX_SYNC_AUTOTUNE`  entirely (code and all) after discussion with Alessandro, since this was never actually production ready. Will probably take another crack at it down the line since we schedule OpenTX to have 400us of margin.

**Review by cruwaller — APPROVED** [review]

**Comment by AlessandroAU** [comment]
Need to double check with @jurgelenas that no configurator changes are needed

**Review by jurgelenas — APPROVED** [review]
All good on my side

**Review by pkendall64 — APPROVED** [review]

**Review by pkendall64 — APPROVED** [review]

**Pull request merged**
