### PR TITLE
puts fix for #2028 back into business

### PR DESCRIPTION
**Pull request by mha1**
as discussed with @JyeSmith

### CODE REVIEW

**Comment by JyeSmith** [comment]
A little background.

This PR essentially reverts https://github.com/ExpressLRS/ExpressLRS/pull/2271 and reintroduces the chance of missing a TLM packet because the radio will be in FS mode.  You could argue this doesnt matter because that the frequency already has interference and wouldn't have successfully received the packet (because the channel did not pass `ChannelIsClear()`).

Its still unclear why calling the functions in this order works, while previously it would cause a lock up.  There is no change to non-LBT users.

Thanks to @mha1 for persisting with this bug and his testers.

**Review by JyeSmith — APPROVED** [review]

**Comment by JyeSmith** [comment]
Oh this should probably target v3.x maintenance.

**Comment by mha1** [comment]
I can do a 3.x.x version of the PR if that helps

**Comment by mha1** [comment]
#2438 should do for 3.x.x-maintenance

**Comment by pkendall64** [comment]
I'll close this one then as 3.x.x will merge into master

**Comment by mha1** [comment]
thx

**Pull request closed without merging**
