### PR TITLE
Reduce Lua memory again, use nil instead of 0/false, free unused funcs

### PR DESCRIPTION
**Pull request by CapnBry**
This reduces Lua memory usage again, since my OpenTX 2.3.14 Q X7 likes to out of memory crash when refreshing. With this PR, my memory use after first load drops from 56737 to 49386, a 13% reduction.

### Details
* Instead of keeping the code for both the color and B&W screen in RAM at all times, break it up into two different functions and free the one that isn't going to be used. Also free functions only used during init(). Saves 3KB on B&W
* Removed "default" field value. We never use this.
* parent == 0 now is parent == nil. Storing nil in Lua takes no memory at all, but storing parent == 0 stores both a unique string key "parent" and a number 0 on every field.
* Similarly min and max are stored as nil now instead of 0.
* Selections no longer store min or max values since the value was overridden and thrown out anyway.

### Bugs
* runPopupPage was referencing a variable `status` that didn't exist, changed to `fieldPopup.status` after confirming with StonedDawg that this is what was intended.
* Even if fields_count was 0, we'd request field info, which would crash us if field info showed up. Now only requests field info if fields_count isn't 0.

### CODE REVIEW

**Comment by JyeSmith** [comment]
QX7 on EdgeTX build 2.6.0 b3da7772

Current LUA 41k and regularly hits 50k when changing settings.

New LUA 41k and occasionally hit 50k when changing.

**Review by StonedDawg — APPROVED** [review]
awesome optimization! and it's working flawless!

**Review by pkendall64 — APPROVED** [review]
I'd like to see a check after line 495
```lua
  if field == nil then
    return
  end
```
as I've see it blow up on line 514 accessing the `field` and it's nil.

**Comment by CapnBry** [comment]
I've also seen it blow up with field == nil. I am guessing that we somehow get a parameter info message before. It would seem we could get into this state if we send a device request and don't get a response before the next update loop and we send the field request with fields_count == 0 still. In addition to the change you requested, I've also modified it so it does not request field info if there are 0 fields.

**Comment by CapnBry** [comment]
> QX7 on EdgeTX build 2.6.0 b3da7772
> Current LUA 41k and regularly hits 50k when changing settings.
> New LUA 41k and occasionally hit 50k when changing.

This is so weird, I can't understand how it would not even make any difference considering there's less code and less data in use. Maybe whatever they do to lower the memory usage fixes some other issue that causes it to be too fat on OpenTX

**Comment by StonedDawg** [comment]
@CapnBry I have been trying to make the good packet count show up in freedomTX, at 1st after 4 commit I made, its intention is to revert back as how the current master ``lcd_title()``, but it seems it was not because of the attribute assigned in ``drawtext``, e.g. ``INVERS`` or `` RIGHT``. it seems like the ``goodBadPkt`` string doesn't even contain the ``goodpkt`` and the ``state``  string.

i revert back to how it was (1da0de5) on my latest commit here.

**Comment by CapnBry** [comment]
What the fuck?

**Comment by CapnBry** [comment]
Yeah I truly do not understand what is going on with FreedomTX. It has something to do with their Lua compiler or something. If I change the run code to just this:
```
  lcd.clear()
  local s = tostring(250)
  lcd.drawText(50, 1, string.format("%u", string.len(s)))
  lcd.drawText(50, 10, string.format("%s", s))
  lcd.drawText(50, 20, s)

  return 0
```
The first time you execute that script, it says that the length of the string "250" is 15 and the string itself is blank. If you exit the script and come back into it, it displays a length of 3 and properly displays "250". This happens for both the script in master and this PR.

If you copy a new script, execute the script, exit, go to the SDCARD menu and delete the luac file, running the Lua from the tools menu gives the bad behavior again. You can repeat this delete and reexecute and it works badly every time. However, the second time you execute the script from the tools menu, it always works after that, even if you delete the luac.

I do not understand what is happening, but I am not going to spend all day trying to figure out what's broken in FreedomTX. The string.format I pushed works every time, and if anyone experiences weirdness I encourage them to just exit the script and come back again until TBS releases EdgeTX/OpenTX for Mambo.

**Comment by wvarty** [comment]
Tested on Mambo and Tango, and confirmed no more issues with good/bad text being cut off.

**Pull request merged**
