### PR TITLE
clear all form data before updating hardware setting

### PR DESCRIPTION
**Pull request by Ncerzzk**
For now, if we upload a new pin.json file, it will not clear the old form data in html.

which would cause pin config leaving over conflict to new pin setting.

### CODE REVIEW

**Comment by Ncerzzk** [comment]
> Or just this...
> 
> ```js
>   _('upload_hardware').reset();
> ```

Thank you, this is a better way ^_^

**Review by pkendall64 — APPROVED** [review]

**Comment by frank26080115** [comment]
are you sure you want this? there might be people who have JSON files that only add PWM pins and want to leave the rest of the SPI alone

**Comment by pkendall64** [comment]
> are you sure you want this? there might be people who have JSON files that only add PWM pins and want to leave the rest of the SPI alone

Yes we do want it this way. It is far more obvious that the uploaded file is a replacement not an addition.

**Comment by frank26080115** [comment]
I do welcome the change, I have a collection of JSON files for my projects with a bunch of `""` blank entries to blank out certain entries. But I realize that there's a possibility that the file can be used in an "append" fashion by other people. I hope this change is  very prominently pointed out in the release notes.

**Review by JyeSmith — APPROVED** [review]

**Pull request merged**
