### PR TITLE
2.x to 3.0 Config Update

### PR DESCRIPTION
**Pull request by CapnBry**
This is the final config upgrade procedure from 2.5.0 TX and RX config storage, as well as adding some extra fields to have available for future development without changing the structure. If you have a feature for 3.x that you know the config storage requirements, this would be a great time to add the fields now to prevent having to make a new config version later to get a few bits!

### Update TX 5 to 6 to 7
We have a only-one-config-update policy but we also told most people that they didn't have to upgrade their ExpressLRS for pretty much all the 2.x versions. This means some people will still be on v5 (before the DVR fields) going to 3.0 so I've made the routine go anywhere 2.x to 3.0.

### Update RX 4 to 5
During development our RX version was already advanced to v5, but 2.5.0 is still v4. Therefore the update will not fire going from master to master. Just something to watch out for.

## Slight change in architecture
The original code would check the config version / load, then try to upgrade, and finally fall back on defaults if all that failed. I reordered it so defaults are always loaded first, then check the version / load, and upgrade if version is old. This allows the update process to just not touch fields the old config didn't have and prevents having to have the same code in SetDefaults *and* each update procedure to set the defaults as well (since SetDefaults was never called for an upgrade).

## Testing
For each source version + platform + team, as much non-default as possible. Rates are Team2.4/Team900
* Set Model 0 250Hz/100Hz, 1:64, Hybrid, 250mW Dyn
* Set Model 1 150Hz/50Hz, 1:8, Wide, 25mW, Fixed
* Fan Thresh 500mW, 
* VTX Admin: A2 Power 3 Pitmode On

* FM30 TX v2.0.0 to master
* FM30 TX v2.5.0 to master
* Namimno OLED v2.0.0 to master
* Namimno OLED v2.5.0 to master
* ES900TX v2.0.0 to master
* ES900TX v2.5.0 to master

For RX
* Set model id = 1
* Set PWM ch0=ch1 (988), ch1=ch2, ch3=ch4 (1500), ch4=ch5, ch5=ch6 (2011 inverted)

* PWMP v2.0.0 to master
* PWMP v2.5.0 to master
* DIY SX1280 v2.0.0 to master
* R9MM v2.0.0 to master (FAILED)
* Lost interest in testing, and living, after 12 hours of flashing, changing config, and struggling with R9MM

### Untested
Traditional binding RXes

## Bug
Note that R9MM failed, it always loads defaults on startup. This is happening in master and after going 2 hours at it and not seeing a cause apart from the extEEPROM is not loading or possibly not saving, that's a bug report for 3.0 RC and now outside the scope of this PR.

## New Fields
I've created some space in the config structures for features we probably will have early in 3.0. It is difficult to create storage space for features that haven't even been fully imagined yet, but maybe this will save us a config version. If you have a feature coming that needs storage space, bring it up here along with the default value if 0 isn't gonna work for you.
* TX custom button actions and RGB LED color - 2x 4 byte struct is added for using a byte 6-entry RGB color (e.g. #330000, #660000, #990000, #cc0000, #ff0000) and 2x button custom actions (1-long 1-short) and a spare byte
* TX per-model antenna selection - I made this per model because ? I'm not 100% on if this should be per-model or global. Let me know what you think. Global makes more sense in that if you only have one antenna on, you definitely don't want to switch to another model that is set to the other antenna and kill your TX. Global is safer, per-model more flexible. Let me know what you think.
* RX VBAT scale - For our PWM RXes putting the scale in a Lua variable and webui is better than having the user edit hardware.json I think.

### CODE REVIEW

**Comment by pkendall64** [comment]
In the fun-stuff branch, I have buttons and actions and leds for buttons.

Each button has a flag for long/short a count, which we could limit to 8, an action, which we could limit to 16 actions (theres 7 currently on a TX). Each button can have any number of action assigned, but we could limit it, on a RX the button currently has 2 long-press actions, and the TX has a long and short action on each button. So I think we could limit it to 2 actions per button, but we can't limit it a long and short.

Each button is also assignable an RGB color for the LED associated with that button.

So, for each button I think we need a 8 bits for the action * number of actions per button, so if we made it 2 thats a uint16_t, and we need 24bits a uint32_t for the color.

Then we need to think how many buttons there could be, and I think 2 is probably plenty enough.

**Comment by CapnBry** [comment]
Nice! I knew you had done some work on this already and you'd have some good insight. I feel like having some "system functions" that are always tied to specific key actions, like long x 3 always goes to wifi and long x 5 reboots makes a lot of consistency across the board. That means we have two custom and as many fixed per button as we want is the way I was thinking of it. I guess that means the activation has to work across actions though, since a single long press to like BIND would activate bind and on the 3x tick it would go into wifi+BIND and 5x would reboot while still in wifi mode and binding (although it would have all ended by them of course).

I feel like asking the user to set 1) Action 2) Long/Short 3) Repeat count is really flexible but also just a lot extra stuff where it turns the configuration into a grid spreadsheet of options. Instead, a more friendly `Button 1 Short Press: [Dropdown]` list where the user just chooses up to 4 actions, locked to 1 short 1 long for each button. It also works better if we want to expose it via Lua, as 2 selects for each button (4 total) vs 6 selects for each button (12 total).

32 bits I thought for the color would be more than enough, since we're really not getting 24 bit color from an RGB LED, but the more I think about it that's probably far too many bits. Even 6-level RGB (216 color) would be plenty and stored in a byte, leaving 40 entries for our own programmatic colors (like auto or "copy other led"). Ugh the UI for this is just a nightmare and certainly not Lua-able or OLED-able really.

**Comment by pkendall64** [comment]
> Ugh the UI for this is just a nightmare and certainly not Lua-able or OLED-able really.

Thats why I just did it in the WebUI and said, "stuff it, this can be just for ESP based modules..."

**Comment by CapnBry** [comment]
Hehe yeah you're right, there's not many modules out there with STM32 and a button / RGB LED. FM30 has a button but no LED, does Ghost have both?

> And didn't put it in the config, but put it in the options.
I think this is a bad direction to go in, unless 100% of our config moves to options. Then you have to deal with options needing an updater and/or it exploding in size. For example a TX model definition currently takes 4 bytes of storage * 64 = 256 bytes, but as a JSON array of objects with 8 string items each it is huge and our SPIFFS storage is not all that big. I think we'll quickly run out of space if every item that would take 1-4 bytes becomes 30-40.

We're approaching the point of Maximum Fragmentation and Confusion now with compile options that can not have any effect because there is an options.json, and settings in the Lua but also more settings in the webui (with some overlap), some of those settings on the Display but mostly not, and now some settings which were never compile options going into options with no chance of being set from Lua. If the user changes their bind phrase from the webui, "clearing" that to go back to their normal phase would also delete a patchwork of their settings as now some are stored in options too? It's just becoming more of a mess instead of easy to use.

That said there is a case for using the richer webui for some edits, such as color. If this was done using CRSF Config, that would have to be view presenters that automatically replace the Lua items by name. It is of course much easier to have fixed edit views like PWM has based on their presence in the JSON so I also see the merits of that, but having all the config available in one list fed by the CRSF Config means not having to check multiple config systems to find where you can change the value.

### On Topic
Back to this PR though, how about I just change those button and color future fields to 2x 4 byte structs that aren't defined yet. 4 bytes means 8 bits for a button short, 8 bits for button long, 8 bits for 6-level color (+40 entries for symbolic colors), and 8 bits free if the implementation needs more. I'd remove the color and button items and just add 2x of these structures.

**Comment by pkendall64** [comment]
> Hehe yeah you're right, there's not many modules out there with STM32 and a button / RGB LED. FM30 has a button but no LED, does Ghost have both?

Ghost has RGB and an OLED/Joystick, but no other buttons.

> 
> > And didn't put it in the config, but put it in the options.
> > I think this is a bad direction to go in, unless 100% of our config moves to options. Then you have to deal with options needing an updater and/or it exploding in size. For example a TX model definition currently takes 4 bytes of storage * 64 = 256 bytes, but as a JSON array of objects with 8 string items each it is huge and our SPIFFS storage is not all that big. I think we'll quickly run out of space if every item that would take 1-4 bytes becomes 30-40.
> 
> We're approaching the point of Maximum Fragmentation and Confusion now with compile options that can not have any effect because there is an options.json, and settings in the Lua but also more settings in the webui (with some overlap), some of those settings on the Display but mostly not, and now some settings which were never compile options going into options with no chance of being set from Lua. If the user changes their bind phrase from the webui, "clearing" that to go back to their normal phase would also delete a patchwork of their settings as now some are stored in options too? It's just becoming more of a mess instead of easy to use.

I do agree with you on this be a fragmented patchwork of options all over the show, but I can't think of clean way of handling it when we have to support both STM and ESP.

> 
> That said there is a case for using the richer webui for some edits, such as color. If this was done using CRSF Config, that would have to be view presenters that automatically replace the Lua items by name. It is of course much easier to have fixed edit views like PWM has based on their presence in the JSON so I also see the merits of that, but having all the config available in one list fed by the CRSF Config means not having to check multiple config systems to find where you can change the value.
> 
> ### On Topic
> Back to this PR though, how about I just change those button and color future fields to 2x 4 byte structs that aren't defined yet. 4 bytes means 8 bits for a button short, 8 bits for button long, 8 bits for 6-level color (+40 entries for symbolic colors), and 8 bits free if the implementation needs more. I'd remove the color and button items and just add 2x of these structures.

Sounds like a sensible plan to me.

**Comment by CapnBry** [comment]
> Sounds like a sensible plan to me.

I've made this change so the space will be there for if this gets figured out. I know I am complaining about an implementation without any suggestion for how to do it, so I am sorry about that. I'm not sure how the heck we can configure that on something without a webui, but I do feel like the config value should be stored in config, not options. We have a place where user settings are stored and accessed, it is in config and I feel like options.json should be deprecated eventually instead of increasing fragmentation of where settings come from.

### punning fixes
When I was testing this I kept getting what seemed to be some weird values from nvs for the model config. After spending a little more time looking at it this morning, the weird values are the values we are putting in there! The nvs code casts `model_config_t` to and from `uint32_t` as if this just works properly, but it really does not. The integer you get on a v6 model config is only 16 bits so depending on what you're casting, you can also get the next 16 bits of RAM into the integer as well (compiler: you told me you wanted to dereference 4 bytes so 🤷‍♀️). This can also create some weird interaction going from a v6 (16 bit) to v7 (24 bit) model structure using the same integer.

I've implemented actual functions to convert one from the other using an intermediate 4 byte chunk of storage so this should work safely. It works in testing when loading v6 model uint32_t (which often have high bits set from this bug in 2.x) and storing them, and somehow works out to be 4 bytes less code. Works properly and is smaller than `*((uint32_t *)&model)`? Something must be wrong! It doesn't seem to be, I am as surprised as you.

**Review by pkendall64 — APPROVED** [review]

**Comment by CapnBry** [comment]
This should get merged after #1626 because I made a conflicting definition for where the forcedTlmDisable field went so I'll fix that once 1626 is merged.

**Pull request merged**
