### PR TITLE
Handset Communication Optimisations

### PR DESCRIPTION
**Pull request by pkendall64**
# Problem

1. It's bothered me for some that we lost 500Hz mode on 400kbaud
2. @JyeSmith mentioned that the main loop time looked inconsistent on the TX module

# Changes
1. Simplify the code reading the data from handset.
2. We used to assume that we could only output a maximum of 1/2 of the packet window, but we can actually calculate how much of the window is left by counting the number bytes sent to us in the transmit part of the window.
3. When sending data don't flush as that waits for the TX buffer to empty before returning. No we just set a flag to indicate we are transmitting and we check if the TX queue is empty before going back to receive mode.

With these changes it is possible to use 500Hz on 400kbaud, sadly, 250Hz on 115kbaud cannot work as there is just not enough time left in the window to send any telemetry/Lua response data back to the handset.

The following traces have 4 pins indicating which state/processing is happening on the transmitter module, when the pin is in the HIGH state.
1. `loop` - The main loop is executing
2. `timer in` - The timer interrupt has fired and is executing
3. `handset` - The handset processing function is executing (this is a sub-part of the main loop code
4. `radio int` - The radio interrupt has fired and is being processed

All traces taken on packet rate 333Hz at 400kbaud

## Before changes
400k 333Hz Before

This trace shows the time taken to process an incoming packet and send (and wait for completion) of a telemetry packet hack to the handset. This is evidenced by the long high time on the `handset` pin. This trace was taken whilst refreshing the Lua script.

## After changes
400k 333Hz After

In this trace it can be seen that not waiting for the send to complete, the processing of the handset message is much shorter and the loop processing is able to execute many more times. This trace was also taken while refreshing the Lua script.

## Lua refresh with serial data
The `crsf` pin is triggered when the serial devices informs us that data is available for processing. And the `serial` pin is the s.port pin connected to the handset.

400k 333Hz Lua Refresh

This trace shows the serial data being received along with the processing and then a response packet being sent back. As can be seen the window available for sending data back is quite a lot larger than half the period, so we can now utitilse that.

## Processing RC packets
400k 333Hz Main

Plenty of time for processing and sending back telemetry information.

## 500Hz at 400k baud
400k 500Hz connected

Still plenty of time

### CODE REVIEW

**Comment by JyeSmith** [comment]
Looking good.

This is current master.
image

And this PR.
image

**Comment by JyeSmith** [comment]
Im not sure about displaying blanks on the unavailable rf modes, particularly since they can still be selected.  It might be ok if the warning then didnt pop up... Im not sure.  Happy to merge though and get some user feedback before release.

**Review by JyeSmith — APPROVED** [review]

**Comment by pkendall64** [comment]
> Im not sure about displaying blanks on the unavailable rf modes, particularly since they can still be selected. It might be ok if the warning then didnt pop up... Im not sure. Happy to merge though and get some user feedback before release.

You don't have the latest Lua script! 😮‍💨

**Comment by JyeSmith** [comment]
> > Im not sure about displaying blanks on the unavailable rf modes, particularly since they can still be selected. It might be ok if the warning then didnt pop up... Im not sure. Happy to merge though and get some user feedback before release.
> 
> You don't have the latest Lua script! 😮‍💨

Im emulating a user 😄

**Review by wchnflr — APPROVED** [review]
These changes fixed a LUA script loading problem I encountered with 3.4.0, 3.4.1, and 3.4.2 on a DIY 2400 ESP32 SX1280 module in a TBS Tango II.

**Comment by pkendall64** [comment]
> These changes fixed a LUA script loading problem I encountered with 3.4.0, 3.4.1, and 3.4.2 on a DIY 2400 ESP32 SX1280 module in a TBS Tango II.

Thanks for the feedback

**Review by wvarty — APPROVED** [review]

**Pull request merged**
