### PR TITLE
Include unchecked checkboxes in options submit

### PR DESCRIPTION
**Pull request by CapnBry**
This adds unchecked checkboxes to options, which is preventing them from being saved with "false" values. Currently you can not uncheck an Options value in the webui and have it stick. (The individual checkboxes on the model settings page are fine)

### Details
Reported by @robustini [Discord](https://discord.com/channels/596350022191415318/797109686285107241/999907879647707156). If you try to uncheck the box it stays checked.

The issue is because in HTML, always and forever, unchecked checkboxes are not considered to exist at all. Someone in like 1991 thought this would be a brilliant way to save bandwidth or something and we're still saddled with it. When constructing a `new FormData` from a form, only checked checkboxes will be in the new object. Our side when it loads the json, if the value is not in the document, it gets the default value, not "false", so lock-on-first-connection is always true. In order for the value to be false it must be in the JSON.

This code just takes the FormData-derived object and appends all unchecked checkboxes to it manually. The other option would be to add hidden input fields with the same name and value=false, but then they'd be in the JSON twice if checked. HTML checkboxes are a real Pippin.

### Extra
Note that after setting the Options value, the RX/TX code expects to be rebooted, so if the page is reloaded it will have the old values. This is because the string is only updated on init, so just setting the SPIFFS file does nothing until the module is rebooted and the string is recreated.

### CODE REVIEW

**Review by pkendall64 — APPROVED** [review]

**Comment by robustini** [comment]
Tested on BetaFPV 900 rx and it seems not to work.
after flashing the firmware via web I found the "Lock on first conenction" option enabled, I deselected it and did a save and reboot.
Once reconnected this is the result, as well as finding it always enabled it is also "Invert TX pin".

immagine

**Comment by robustini** [comment]
Tested on BetaFPV 900 rx and here it seems not to work, indeed worse than before.
After flashing the firmware via web I found the "Lock on first conenction" option enabled, I deselected it and did a save and reboot.
Once reconnected this is the result, as well as finding it always enabled it is also "Invert TX pin".

Cattura

**Comment by CapnBry** [comment]
Dangit, you're right! This is what happens when I throw in a last minute "optimization". It ended up always checking all the boxes. 😂

Ahhh try it now with d71d67f, you'll need to uncheck the checkboxes and Save and Reboot (actually reboot) then it appears to be as working as it was before I optimized it.

**Review by deadbytefpv — APPROVED** [review]

**Comment by robustini** [comment]
> Dangit, you're right! This is what happens when I throw in a last minute "optimization". It ended up always checking all the boxes. 😂
> 
> Ahhh try it now with [d71d67f](https://github.com/ExpressLRS/ExpressLRS/commit/d71d67fb7c29249934ec1aa107346df07a519f93), you'll need to uncheck the checkboxes and Save and Reboot (actually reboot) then it appears to be as working as it was before I optimized it.

Fixed, thanks.

**Pull request merged**
