### PR TITLE
Show version string instead of commit hash for release versions.

### PR DESCRIPTION
**Pull request by netmute**
IMG_1453

### CODE REVIEW

**Comment by CapnBry** [comment]
This is great but unless I am missing something, there would be no way to have the ELRS.lua support displaying the version number for the version it is supposed to support. That is, if we plan to release with commit xxxxxx, then ELRS.lua will have to be updated with that commit sha as being 1.0, which changes the sha for the release so the LUA won't recognize it as being the version any more.

I can't think of any workaround to make that work-- the LUA will never report a version number for the SHA of the actual release it came with. I don't think this is a valid solution.

**Comment by netmute** [comment]
The thought occurred to me as well after I submitted this.

**Comment by CapnBry** [comment]
This will be a moot point after ELRS v1.1, because the lua is being reworked entirely and we'll be able to send a full SHA string or version string without the 6 byte limit. A good solution though other than the chicken-egg problem.

**Comment by netmute** [comment]
I have read your discussion on the Discord about that 👍
I will close this PR then.

**Pull request closed without merging**
