### PR TITLE
Query the user about force flashing on mismatched firmware upload

### PR DESCRIPTION
**Pull request by pkendall64**
Add a popup in the web UI if the user uploads a mismatching firmware file and ask the user if they wish to force flash the firmware.

### CODE REVIEW

**Comment by JyeSmith** [comment]
Should Yes be red?  That will sort of indicate danger.

image

**Review by JyeSmith — APPROVED** [review]

**Comment by pkendall64** [comment]
> Yeah this is awesome. I'm with Jye though, the coloring is all crazy. Is this the only place we use the question type popup? If so we can change the CSS to be the warning color instead. Also the JS should be updated so the CONFIRM button is red instead of the CANCEL being red.
> 
I can change the colours easily enough, and will do.

> Can you also include the target name in the confirm message too? Doesn't hurt to throw that up in the user's face right before they click the button one last time. The message right now is so milquetoast and generic that it is worthless. Some thing you did or plan to do may do things. THINGS!

The problem with this is we do know the current running firmware target, but not the target of the firmware being uploaded, as it's (maybe) some string in the code with a magic part in front. So the message can only tell you what firmware you are running and thats on the screen already. I agree that the text is a bit wishy-washy.

> I am not sure how much use it will get after 2.0 and people needing to flash back to 1.2, but doesn't hurt to let people hang themselves with the wrong target more easily without the `?force=1` option.

It's useful if folk start flashing their RXs with backpack code etc.

> 
> EDIT: For snark and to trigger Wez, where are the tabs for the webui?!

Patience, I'm biding my time.

**Comment by pkendall64** [comment]
How's this look
Screen Shot 2021-11-05 at 9 11 49 AM

**Comment by pkendall64** [comment]
And when uploading a backpack target to an RX
Screen Shot 2021-11-05 at 9 46 05 AM

**Comment by CapnBry** [comment]
That looks amazing! 😍

How about if it can't figure out the name for the uploaded target, it just doesn't have that line? That would prevent people from thinking that the only reason it is complaining is because the upload was unknown?
```
      if (target_found.length() !=0 ) {
        message += "<b>Uploaded image:</b> " + target_found + ".<br/>"; // removed one BR
      }
      message += "<br/>Flashing the wrong firmware may lock or damage your device.\"}"; // added one BR
```

**Review by CapnBry — APPROVED** [review]

**Pull request merged**
