### PR TITLE
Add support for PWM receiver output

### PR DESCRIPTION
**Pull request by CapnBry**
This is a basic framework for doing PWM output directly on the receiver. Only ESP8266 output is implemented, but the framework will work for other architectures if the servo pulse output code is adapted to those platforms as well.

## Details
I keep saying "_ExpressLRS will get PWM output when hardware exists for it_" but let's face it, nobody is going to make a receiver for me and just hope I come through for them. I'm a pretty unreliable guy, all my ex-wives say. 
[Video Demonstration](https://youtu.be/JlNLxnsRACE)

Yes, it uses the standard Servo library from the ESP platform which might raise some eyebrows. I feel like the Servo implementation itself is a relatively minor part, and considering I've freed up timer1 if the implementation ends up being dodgy it is easy to swap it out.

The outputs only update at 50Hz, so the most recent channels are used every 20ms. The ESP waveform library used to create the outputs buffers every output change, so the PWM output is guaranteed to be exactly 20ms behind the latest update after the initial sync.

The failsafe for PWM is shorter than the disconnect timeout: 1 second without a channels packet. This is close to what my FlySky RX does (somewhere between 1-1.5s it seems). The ELRS disconnect timeout is far too long to wait to center the servos. I do not force a disconnect event (`LostConnection()`) because link recovery is much easier if the timer is still running, so the outputs go to failsafe and they can just resume operation if the link recovers before the timeout (3s currently).

### New Targets
`DIY_2400_RX_PWMP_via_UART` and `DIY_900_RX_PWMP_via_UART` The reference hardware is using an EP1/EP2 style receiver (or ES900RX), and I have created a new target called the DIY PWMP (pronounced like PIMP if the pimp said their Ps like Pwwwes). This is a 5 channel target, but only 3 of the channels are brought out on the EP2, so you only get 3 channels. The only thing needed here is to bring out pins 9 and 10 from the ESP8285 to the pinheader and add some inline safety resistors on the outputs. That would make it a 18mm x 13mm 5ch receiver.

### New Defines
`GPIO_PIN_PWM_OUTPUTS` is the one that makes the magic happen. Added to a target.h (or the appropriate file once pkendall64's refactor is merged) it attaches a servo to each of those pins. The config store has mappings for each pin.

`CRSF_RCVR_NO_SERIAL` because the hardware I am debuting this on doesn't have enough pins to run CRSF output as well as PWM. This is like `DEBUG_CRSF_NO_OUTPUT` except it blocks all the CRSF input and output on the RX. Nothing going in or out any more.

### Config Updates
The RX config store now has fields to store up to 8x input channels, failsafe values, and invert flags. I do not adjust this size based on the number of servos actually present, but it is only 16 bytes so I don't think it is a problem. I didn't go with 16 outputs because 8x outputs may be the most we ever use? The data in these is 'undefined' on platforms without PWM output (to save code space, you can't even get the values), but the EEPROM space is always used.

The webui was updated to allow setting the input channel / invert / failsafe values. It only shows the number of servo outputs currently defined and not all 8 all the time. In this image I only have 3 because I am using 2x of the channels for debug logging (which works just by defining `DEBUG_LOG`!) I have fixed the misspelling of "Output" so I am offering this rare one-of-a-kind blooper as an NFT you can buy to remember that one time I made a mistake.
PWM UI

## Risks
I've rewritten the hwTimer_ESP8266 to use timer0 vs timer1. timer1 has a lot more functionality and is used by the waveform library that's part of the platform, so this was a necessity if I didn't want to rewrite that instead. The wifi uses this timer, but we do not run PWM and wifi at the same time so that should not be a problem until we forget about that and break it at some point. Timer0 runs strictly off the ESP's main clock and can't stop won't stop. The changes were relatively minor: do our own prescaler'ing based on CPU clock, and just keep pushing the alarm time down the street as we go. I thought this was going to be a real challenge but I got it right on the first try. I think it may track even better than the other one, my freqOffset is 0 or 1 every time I force the connection to drop.

It behaves the same way as it did, so the code that interfaces it should not notice any differences. This mitigates most of the risk and if it starts/stops/changes interval as reliably as the old code did (I checked this like 100x in and it does), then there shouldn't be any latent risk.

## Other fixes
* Setting Model Match modelid from the webui was setting it to 0 every time (the POST wasn't passing any values to us!)

## Reference hardware
I need someone to draw up a schematic or some sort of guidelines for the reference design. It just needs the standard 5x SIGNAL/5V/GND pads like a PWM receiver would have, and GPIO 0, 1, 3, 9, 10 connected for the signal. It is literally an EP1/EP2 with two extra traces. It can also **still be used as a FC-capable receiver**, because the original 4 pads you need are still there: RX/TX/5V/GND! This this is all wins.
| Function | ESP GPIO | EP2 Pad |
|---|---|---|
| Servo Channel 1 | 0 | Boot Pad / Pulled up |
| Servo Channel 2 | 1 | TX |
| Servo Channel 3 | 3 | RX |
| Servo Channel 4 | 9 | Not connected currently |
| Servo Channel 5 | 10 | Not connected currently |
| 5V | NC | + |
| GND | GND | GND | 

No-effort render of the design. Note that the left-most and right-most pinheader are castelated here, but the PCB could be wider there if desired. There's no reason to make the whole board wider though. u.fl used in place of ceramic, but either works.
image

### CODE REVIEW

**Comment by skorokithakis** [comment]
This is excellent, well done! Thank you for all your work.

**Comment by crteensy** [comment]
see here for my ESP8285/SX1280/5xPWM design: https://github.com/crteensy/ELRS-8285-1280-5xPWM


> > @billgroft I'm currently drafting a design in KiCad. We can certainly collaborate on this.
> > crteensy,
> > I saw your board on Github, looks good.  Could I see your schematic please?  Are you planning to put the EP2 on the top of your board and jumper the unconnected outputs to your board?
> > You need to be careful plugging in the servos to the connector because if you plug the servo in backwards the output pin of the micro is connected to ground of the servo and you can blow up the output.  Commercial receivers have a resistor in each output to limit the current.
> > Bill

Are you on the ELRS discord server? What exactly did you look at?

**Comment by billgroft** [comment]
Crteensy,

I was on the discord server and saw this



Now that I looked again I see that it was by Jupa Creations and not you.

Bill

**Comment by StonedDawg** [comment]
just tested this! awesome! especially the more assertive way to configure failsafe than the PWM converter. I can see and set the value from the web UI. 

I don't know how many more RX (with pin configuration differ from DIY) will support the PWMP, but do you think having the servo channel output in the web UI, as how the pad is described would be easier to remember on the field? for e.g. ``CH2 - TX Pad``?

**Review by StonedDawg — APPROVED** [review]

**Comment by CapnBry** [comment]
> I don't know how many more RX (with pin configuration differ from DIY) will support the PWMP, but do you think having the servo channel output in the web UI, as how the pad is described would be easier to remember on the field? for e.g. `CH2 - TX Pad`?

The pin config will be identical in full 5ch PWMP receivers, but I am not sure about adding the pin labels to the webui. The webui is generic for any PWM target, so the names won't match up across platforms. crteensy is having a full 5ch PWMP board made which will use this target as well. The goal of this PR isn't to use EP2 as PWM receivers, but the EP2 can be used currently to prove that it works. I'm hoping that using them directly as PWM receivers will quickly not be a thing as updated hardware comes out. The docs website definitely can show which pins are boot, TX, and RX though just in case someone wants to via_UART flash.

I've got two testers working on testing in Discord currently, one on EP2 Team2.4 and one on ES900RX Team900 so hoping to get some good feedback soon. So far I can just confirm that they both do output PWM as expected, but am waiting for them to have a few flights to get some real use feedback.

**Comment by JyeSmith** [comment]
I don't have servos for testing, but have done a soak test of the timer changes.

DIY 2.4 Rx target, -105dbm, 500hz, with zero problems to report.

**Review by JyeSmith — APPROVED** [review]

**Comment by svpetar** [comment]
Maybe this could help:

https://rutracker.org/forum/viewtopic.php?t=6126184

**Comment by i-am-pradhumya** [comment]
Hello Sir, Can u add this support in elrs v3, cuz i have an Jumper AION Mini 2.4ghz reciever flasehd with elrs v3.5.3. and I want to use this PWMP capability on it. please make it available for elrs V3

**Pull request merged**
