### PR TITLE
Fix PWM RX lua

### PR DESCRIPTION
**Pull request by pkendall64**
Moving the folder elements to the end of the LUA code fixes the problem.
I think this is a workaround as I believe the root of the problem is actually in the Lua script.

### CODE REVIEW

**Comment by gjhaynes** [comment]
No LUA error on Matek R24-D with this pull request. Channel mapping works. Tx Module running 3.0.1.

**Comment by JyeSmith** [comment]
Tested in a mashup of current PRs.

I wasnt having issues, but this PR still look fine on a Pico PWM Rx.

**Review by JyeSmith — APPROVED** [review]

**Comment by JyeSmith** [comment]
Flashed a Dual with 3.0.1 and changed the tlm power and model number.  Flashed with a mashup of current PRs and all setting were preserved.

**Comment by ajjjjjjjj** [comment]
I have tested previous revision again just to make sure that Serial speed or Packet Rate have any influence on that but no.
After flashing this revision error went away.

Regarding your comment on Lua:
I'm not using Lua but custom C implementation and error was exactly in the same place and now is gone.
My investigation result on what is wrong is in the related issue.

**Comment by wvarty** [comment]
Tested on:
- TX16S internal
- HM EPW5

Confirmed I could reproduce the syntax error on a different branch, flashed this branch and error no longer occurs.
Good to go.

**Review by wvarty — APPROVED** [review]

**Comment by paulkidd68** [comment]
Tested

.TX16s with BetaFPV external 
.BetaFPV PWM rx

Flashed with the Maintenance branch and all working.

**Pull request merged**
