### PR TITLE
Allow auto-wifi to be disabled on the TX

### PR DESCRIPTION
**Pull request by wvarty**
Auto wifi on the TX is going to get super annoying when you have multiple models set up, some which dont use ELRS.
It will also be frustrating for users who are configuring the TX for the first time, and have not yet set up CRSF as the protocol. Currently, if someone takes >30s to enable CRSF in the model, the TX will then no longer respond in LUA (since it will be in wifi), which will look like it's broken (this is assuming the external module is set to something other than CRSF at power on).

### CODE REVIEW

**Comment by CapnBry** [comment]
But if the External Module is set to Off, the module is off so therefore the timer isn't ticking. When module is powered, it is getting packets and therefore won't go into wifi mode ever. A new model won't have any External Module selected, so that's not an issue. Even editing the External Module type (being in EDIT mode) powers down the module while the selection is being made.

I'm not sure how the timer could ever expire in any use case at all apart from if the module is running the wrong settings that prevent it from communicating at all?

**Comment by wvarty** [comment]
> But if the External Module is set to Off, the module is off so therefore the timer isn't ticking. When module is powered, it is getting packets and therefore won't go into wifi mode ever. A new model won't have any External Module selected, so that's not an issue. Even editing the External Module type (being in EDIT mode) powers down the module while the selection is being made.
> 
> I'm not sure how the timer could ever expire in any use case at all apart from if the module is running the wrong settings that prevent it from communicating at all?

Scenario:
1. User has any other non-CRSF external module
2. User has non-CRSF module installed, so has the appropriate model selected
3. Power off handset, and later decides to fly ELRS
4. Swaps modules, powers up handset
5. Quad doesnt bind (wrong model selected), and 30s has elapsed at this point
6. TX goes into wifi
7. User selects the ELRS model, but module is still in wifi

Regardless, it would be nice not be forced to adopt this feature, thus the ability to disable it if you don't want it, without impacting those that want it.

**Comment by wvarty** [comment]
@CapnBry this is also hugely annoying in dev, since the timer still runs while the TX module is powered via USB. If I flash my TX via USB with the handset powered off, then power up the handset, the TX module is already in wifi by the time its trying to connect.

**Comment by CapnBry** [comment]
Your scenario above is not how it works though. The timeout in the TX is not for "Has it ever connected to an RX" like the RX's timeout is, it is "Has the handset every sent me a valid CRSF packet?". 

* If the wrong model is selected in the handset, the handset cycles power when switching from one model profile to another. There will be no timeout because the model was just booted. Even if the incorrect model in OpenTX is CRSF, we'd have received packets and therefore prevented the module from going into wifi mode due to the "haseverconnected" being true, we did connect to the handset.
* If the External Module setting was wrong, say MULTI was selected. The instant you go into EDIT mode to change it, OpenTX powers down the module. As soon as CRSF is selected and committed, the module is powered, OpenTX starts sending CRSF packets to us, "haseverconnected" is true at that moment and will never go to wifi

The only scenario where it will go to wifi is if you've got the handset off and flash it externally and then power up the radio more than 30 seconds later. This is not any sort of normal usage scenario where the user will both keep USB plugged AND turn on the radio.

I do agree that there should be a way to disable it, but your reasons aren't how it behaves currently so that's not any supporting reason. I'd go for this if you remove the change to user_defines.txt because 120 seconds is a flippin' lifetime to wait for wifi by default. If you want to change this in your system, use super_defines.txt

**Comment by StonedDawg** [comment]
It's a small failsafe to at least still provide some user to flash through wifi in case : 
1. User flashed with UART_INVERTED while their handset is not INVERTED
2. User flashed without UART_INVERTED while their handset is INVERTED
3.  they can access LUA, they could go to set the external module as PPM, it will power up the TX module without sending any crsf signal.

**Comment by wvarty** [comment]
> Your scenario above is not how it works though. The timeout in the TX is not for "Has it ever connected to an RX" like the RX's timeout is, it is "Has the handset every sent me a valid CRSF packet?".
> 
> * If the wrong model is selected in the handset, the handset cycles power when switching from one model profile to another. There will be no timeout because the model was just booted. Even if the incorrect model in OpenTX is CRSF, we'd have received packets and therefore prevented the module from going into wifi mode due to the "haseverconnected" being true, we did connect to the handset.
> * If the External Module setting was wrong, say MULTI was selected. The instant you go into EDIT mode to change it, OpenTX powers down the module. As soon as CRSF is selected and committed, the module is powered, OpenTX starts sending CRSF packets to us, "haseverconnected" is true at that moment and will never go to wifi
> 
> The only scenario where it will go to wifi is if you've got the handset off and flash it externally and then power up the radio more than 30 seconds later. This is not any sort of normal usage scenario where the user will both keep USB plugged AND turn on the radio.
> 
> I do agree that there should be a way to disable it, but your reasons aren't how it behaves currently so that's not any supporting reason. I'd go for this if you remove the change to user_defines.txt because 120 seconds is a flippin' lifetime to wait for wifi by default. If you want to change this in your system, use super_defines.txt

@CapnBry I just tested the MULTI -> ELRS model swap, and the TX stays in WiFi. It does not power down the TX on swap if both are set to external, and if it does, the time between power off -> on again is not long enough to cause the TX to drop back out of wifi.

Regardless of the above (and the fact that it is, in fact, a supporting reason), I'm not sure what you are arguing about if you agree there should be a way to turn it off? Why should this feature be forced down everyone's throats when it's an easy fix (that has already been written in this PR) to disable it?

As for your last comment on the timeout, the only time this feature becomes useful is if you've flashed the wrong FW to the module, and in that rare case, someone can wait 2 mins for wifi.

**Comment by CapnBry** [comment]
> As for your last comment on the timeout, the only time this feature becomes useful is if you've flashed the wrong FW to the module, and in that rare case, someone can wait 2 mins for wifi.

Because the same value is used on the RX and TX for when to go into wifi, and we don't want the RX to have to wait 2 minutes without a connection before it goes to wifi.

**Comment by wvarty** [comment]
> Because the same value is used on the RX and TX for when to go into wifi, and we don't want the RX to have to wait 2 minutes without a connection before it goes to wifi.
Ugh. Gross. These really should be separate.

> And I guess we have different OpenTX versions because mine immediately disables the external module when you go into edit mode on the External Module type. I'm on 2.3.14?
Since your performing a different operation to the one I described above, I'm not surprised it behaved differently.

**Review by CapnBry — APPROVED** [review]

**Review by StonedDawg — APPROVED** [review]

**Pull request merged**
